feat(data-manage): edit pages for definitions
PostHog/posthog pull request #10087
Opened 2022-05-31 18:09 UTC by alexkim205

## Changes

Implements edit pages for event and event property definition detail pages.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2022-06-06 14:55 UTC, liyiy commented
changing the name doesn't work 

https://user-images.githubusercontent.com/25164963/172186488-5aa4e28a-b436-4b59-9f9d-aa113aa23dea.mov

2022-06-06 15:11 UTC, liyiy requested changes, later dismissed
Are definition property pages supposed to have events? There's also a double border line here and the name editing also doesn't work

<img width="896" alt="Screen Shot 2022-06-06 at 11 08 03 AM" src="https://user-images.githubusercontent.com/25164963/172189090-e38854c6-6f07-4c8f-8003-9b6569717d32.png">

2022-06-06 15:12 UTC, liyiy commented on frontend/src/scenes/data-management/definition/definitionEditLogic.test.ts
> +describe('definitionEditLogic', () => {
👍 nice

2022-06-06 18:08 UTC, alexkim205 commented
Good catch, custom names for event definitions isn't available yet, so I'll make that input read only for now. Also going to hide it from property definitions as well.

> Are definition property pages supposed to have events?

Yup you should now be able to see the list of raw events that match the definition name. We had this in the previous version of definition drawers but it was removed when we removed detail views of definitions.

2022-06-06 19:22 UTC, clarkus approved these changes
Looks good to me. The only things I'd consider changing are those items that @alexkim205 brought up in [figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=11060%3A50972). 

For read only views, including some representation of "verified" status and the raw event name. We can borrow from the experiments feature header patterns to include a high-levle status pill but also an alternate name value for the item being described. 

![data management - detail view](https://user-images.githubusercontent.com/254612/172232176-e527c686-6a6b-4160-b3e1-594eb236dd4c.png)

2022-06-06 20:05 UTC, alexkim205 commented
Thanks @liyiy for clarifying offline. You're 100% correct matching events should be hidden in property definition details. Made that fix

2022-06-06 22:42 UTC, liyiy commented
@alexkim205 looks like something is bugging out?

https://user-images.githubusercontent.com/25164963/172261132-12489415-39ad-4fbc-881a-f0be77d08909.mov

2022-06-07 15:09 UTC, liyiy approved these changes
looks good after that edit button removal is in for non-licensed instances

2022-06-07 15:12 UTC, merged