refactor: move event util
PostHog/posthog pull request #10108
Opened 2022-06-01 20:53 UTC by EDsCODE

## Problem

- move event util from /clickhouse to /posthog

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2022-06-07 10:46 UTC, neilkakkar commented on posthog/demo/__init__.py
> +    from posthog.models.event.util import get_events_by_team
these can probably move to top of file now

2022-06-07 10:47 UTC, neilkakkar commented on posthog/models/event/event.py
> +from ..team import Team
make this absolute import?

2022-06-07 10:48 UTC, neilkakkar commented on posthog/tasks/status_report.py
> +            from posthog.models.event.util import (
Hmm, some of these imports are at the top, others here. Worth moving all to the top now? (including the `posthog.models.person` ones right below

2022-06-07 10:48 UTC, neilkakkar approved these changes
minor nits!

2022-06-07 10:49 UTC, neilkakkar commented
oh - although the failing test seems valid - a borked import

2022-06-07 10:49 UTC, neilkakkar requested changes
just switching so we don't miss the failed test!

2022-06-15 20:03 UTC, EDsCODE commented
Merging because the import was fixed by the accompanying cloud PR

2022-06-15 20:03 UTC, merged