feat(Funnels): show number of users that entered/completed funnel
PostHog/posthog pull request #10169
Opened 2022-06-07 11:21 UTC by timgl

## Problem

The calculation of funnel trends is different to normal funnels. Users can enter the funnel multiple times, whereas in a normal funnel they can only do this once. This means percentages can be very different. This change at least will make it easier for users to understand why this happens

## Changes

On hover, display the # of users that entered and completed funnel 
<img width="808" alt="image" src="https://user-images.githubusercontent.com/1727427/172367365-6d118d91-1c42-499d-9bcf-a4a493c86590.png">

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

unit tests + manual QA:
- create funnel trends and hover

2022-06-07 11:23 UTC, timgl commented on frontend/src/scenes/funnels/FunnelLineGraph.tsx
> +                        <div style={{ paddingTop: 20, height: 68 }}>
this is quite hacky but couldn't find a better way

2022-06-09 17:41 UTC, alexkim205 requested changes
left some inline comments

2022-06-09 17:41 UTC, alexkim205 commented on frontend/src/scenes/insights/InsightTooltip/insightTooltipUtils.tsx
> -    renderCount?: (value: number, seriesDatum: SeriesDatum | InvertedSeriesDatum, idx: number) => React.ReactNode
What's the reasoning for removing this type?

2022-06-09 17:41 UTC, alexkim205 commented on frontend/src/scenes/funnels/FunnelLineGraph.tsx
> +                    }
This introduces a bug where series labels are displayed but counts are omitted where percentage is 0.

<img width="467" alt="Screen Shot 2022-06-09 at 1 37 21 PM" src="https://user-images.githubusercontent.com/13460330/172910184-10e37136-3dd2-4e0b-9e0f-cb652d37f2c1.png">

2022-06-27 16:06 UTC, alexkim205 commented
@timgl I'm going to remove the stale label since you were out last week

2022-07-12 07:32 UTC, closed without merging