fix: ensure finished_at is reset back to none when an async migration is restarted
PostHog/posthog pull request #11334
Opened 2022-08-16 20:07 UTC by yakkomajuri

It has caused some confusion to see e.g. finished at < started at or finished at set when the migration is running.

This fixes that

2022-08-17 10:51 UTC, tiina303 requested changes
This feels awkward, I'd also like to land my huge pr first, can take a look at this afterwards for how to do it well.

2022-08-17 14:24 UTC, yakkomajuri commented
here's a new approach.

I'm just worried this will slip through the cracks

2022-08-17 15:39 UTC, tiina303 commented
I'll take this once my other PR lands, just don't want to deal with conflicts in that one.

2022-08-18 15:13 UTC, tiina303 commented
The problem was actually already fixed in https://github.com/PostHog/posthog/pull/10912 - when we start the migration now we set all the fields (finished_at, current_index, progress) to what they need to be https://github.com/PostHog/posthog/blob/3514cf786cf5e8c88fa7f7432f7263857b1f287c/posthog/async_migrations/utils.py#L310

2022-08-18 15:13 UTC, closed without merging