fix: show only valid property definition fields
PostHog/posthog pull request #11677
Opened 2022-09-06 10:59 UTC by pauldambra

## Problem

We show property definitions and events as if they have the same data available. But they don't

We don't have first and last seen at for property definitions, and we deprecated volume for property definitions

## Changes

* Hides first and last seen at, and volume when showing a property definition. 
* Changes `raw event name` to `raw event property name`
* Makes property type visible on the view page for a property definition
* moves property type to the same location in the popup card as in the view page

| before | after|
|-|-|
|<img width="344" alt="Screenshot 2022-09-06 at 11 58 42" src="https://user-images.githubusercontent.com/984817/188618490-e0740d03-aa56-4963-b887-ba602d029b65.png">|<img width="358" alt="Screenshot 2022-09-06 at 11 51 08" src="https://user-images.githubusercontent.com/984817/188617747-985ce196-e64a-40a3-91a8-33a38d33bbff.png">|
|<img width="815" alt="Screenshot 2022-09-06 at 11 56 06" src="https://user-images.githubusercontent.com/984817/188618015-8715e000-ed44-45ec-b2d0-cc1ba6f54ff4.png">|<img width="808" alt="Screenshot 2022-09-06 at 11 47 07" src="https://user-images.githubusercontent.com/984817/188617822-3ddba8db-4c11-478b-adc1-ae96010ea848.png">|

## How did you test this code?

with my eyes 👀

2022-09-06 16:08 UTC, alexkim205 requested changes
Everything looks good except one comment. Also, this is simply the best kind of testing!

2022-09-06 16:08 UTC, alexkim205 commented on frontend/src/scenes/data-management/definition/DefinitionView.tsx
> +                        )}
Could we place all of these under one conditional?

```
{isEvent && (
    <>
        ...
    </>
)}
```

2022-09-06 16:39 UTC, alexkim205 approved these changes

2022-09-07 16:05 UTC, pauldambra commented
@clarkus does this work for you? 

Longer term it would be great to add these values for properties but need to get celery under control first

2022-09-07 23:16 UTC, clarkus approved these changes
Thanks for working on this. Previous concepts had the property type adjacent to the property name. If we show it in the placement you have now, I'd probably drop the pill / label pattern and show it as simple text. That way it's more aligned with other attributes and has equal priority. Thoughts?

Does this PR also update the detail view for the property? We show the same attributes there.

2022-09-08 10:15 UTC, pauldambra commented
@clarkus if detail view is e.g. https://app.posthog.com/data-management/event-properties/01790132-ed31-0000-6a3c-3b28470485fa then yep, that's covered. If I'm missing a view I'll follow up there too!

2022-09-08 10:33 UTC, merged