fix: Lemonize all funnel filters
PostHog/posthog pull request #11746
Opened 2022-09-08 18:07 UTC by EDsCODE

## Problem

- lemonizes all filters except "chart type" which requires a custom lemon component

## Changes

<img width="318" alt="Screen Shot 2022-09-08 at 2 06 38 PM" src="https://user-images.githubusercontent.com/13127476/189194509-91da280f-3ad9-40f3-ade9-b6911b51d3d8.png">
<img width="394" alt="Screen Shot 2022-09-09 at 2 07 38 PM" src="https://user-images.githubusercontent.com/13127476/189416221-125fd05f-f53a-4991-920d-ee033f9adbf9.png">
<img width="391" alt="Screen Shot 2022-09-09 at 2 08 39 PM" src="https://user-images.githubusercontent.com/13127476/189416345-5230d10a-1b1b-41c7-84c5-166e6c7ccf19.png">

<img width="184" alt="Screen Shot 2022-09-09 at 11 21 07 AM" src="https://user-images.githubusercontent.com/13127476/189385213-2faf7268-b1ec-4aee-afd8-2ba0f2842f4a.png">

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2022-09-08 19:11 UTC, clarkus requested changes
There are updated icons for the funnel ordering. Those are available here:

- [Left to right](https://www.figma.com/file/Y9G24U4r04nEjIDGIEGuKI/PostHog-Design-System-One?node-id=3139%3A4638)
- [Top to bottom](https://www.figma.com/file/Y9G24U4r04nEjIDGIEGuKI/PostHog-Design-System-One?node-id=3977%3A2036)

![funnel-ltr](https://user-images.githubusercontent.com/254612/189206412-3a6f6020-edef-49dc-9a8d-38570b16d8cd.svg)
![funnel-ttb](https://user-images.githubusercontent.com/254612/189206413-6eb14dea-c0f1-464d-b6be-9d4129e4c75d.svg)

2022-09-09 09:12 UTC, benjackwhite requested changes

2022-09-09 14:53 UTC, EDsCODE commented on frontend/src/scenes/insights/filters/AggregationSelect.tsx
> +        [GroupsAccessStatus.HasAccess, GroupsAccessStatus.HasGroupTypes, GroupsAccessStatus.NoAccess].includes(
yeah, replied to other comment. HasAccess doesn't mean it's used yet. `AlreadyUsing` is the enabled state which is basically HasAccess + HasGroupTypes together

2022-09-09 15:25 UTC, benjackwhite approved these changes
More of a quick look but all seems good to me :shipit:

2022-09-09 16:52 UTC, clarkus requested changes
Generally looks right to me. We should use sentence-case for all the menu item labels. Right now we have a mix of title-case and sentence. https://posthog.com/handbook/company/communication

2022-09-09 18:12 UTC, EDsCODE commented
Should be updated now @clarkus

2022-09-09 18:19 UTC, clarkus approved these changes

2022-09-09 19:31 UTC, merged