feat: slimmer doughnut
PostHog/posthog pull request #11842
Opened 2022-09-15 15:51 UTC by pauldambra

## Problem

relates to #11433 

As a first step 

* slims the donut
* makes the total underneath it larger
* starts splitting out the doughnut chart from the linegraph
* magnifies an arc on hover

### without legend

<img width="733" alt="Screenshot 2022-09-15 at 16 48 46" src="https://user-images.githubusercontent.com/984817/190449856-52213123-7276-41a1-9ad5-c38e1e2bc6ee.png">

### with legend

<img width="732" alt="Screenshot 2022-09-15 at 16 48 56" src="https://user-images.githubusercontent.com/984817/190449853-361ea10c-e6e0-429d-9074-f19880593d28.png">

### hover

![2022-09-15 16 49 04](https://user-images.githubusercontent.com/984817/190449832-a196d68d-f5de-47c0-a1f9-00673a7012a1.gif)

2022-09-16 13:25 UTC, benjackwhite commented
I think this _looks_ better but I find the small hover area somewhat frustrating... I almost wonder if this isn't better as an option rather than the default? I dunno maybe thats just me

2022-09-16 13:40 UTC, pauldambra commented
|-|-|
----
|![Screenshot 2022-09-16 at 14 37 49](https://user-images.githubusercontent.com/984817/190652012-6c569af1-eb03-4bc7-b2d5-860d2c7fbf91.png)|![Screenshot 2022-09-16 at 14 38 40](https://user-images.githubusercontent.com/984817/190652135-8e31b8f4-cf15-441a-b79c-24aad1336dc7.png)|

Yep, I went almost all the other way from chunky to slim :)

chartjs expresses it as a percentage of the circle cut out so we can pick a different cutout amount

Pie charts are a bad way of displaying data (IMHO) so the next steps of making the breakdown easier to read are the important ones

2022-09-19 11:29 UTC, mariusandra requested changes
**tldr**: style 📈 , usability 📉📉 ... can someone convince me otherwise?

*(I realise I could have voiced this in the design phase, but here we are...)*

I'm having doubts when looking at these screenshots:

|chunky|slim|
|-|-|
|![Screenshot 2022-09-16 at 14 37 49](https://user-images.githubusercontent.com/984817/190652012-6c569af1-eb03-4bc7-b2d5-860d2c7fbf91.png)|![Screenshot 2022-09-16 at 14 38 40](https://user-images.githubusercontent.com/984817/190652135-8e31b8f4-cf15-441a-b79c-24aad1336dc7.png)|

I find it much easier to conceptualise the fraction when looking at a chunkier donut... versus when looking at the slim ring. I feel like the information loses fidelity the thinner it gets. With a chunkier donut, I find it much easier to conceptualise the fractions. 

Take the sectors next to the red lines:

<img width="374" alt="Screenshot 2022-09-19 at 13 24 17" src="https://user-images.githubusercontent.com/53387/191007076-85bb8601-d9c3-46b8-9508-5dbb5fdb23ee.png">

I can't tell which one is the smallest by glancing at them. I have to stare and measure (I have to [think](https://www.amazon.com/Dont-Make-Think-Revisited-Usability/dp/0321965515)). 

With a chunkier donut, there's much. more for my eyes to hold on to, and the size difference is easier to grasp.

Perhaps they're just *too* thin now, and there's a happy middle ground?

2022-09-20 09:42 UTC, lottiecoxon commented
I agree with you guys on this - the usability has massively done down hill in the aim of looking good- need to go back to the drawing board and see what we can do to fix this. Would people be open to having a filled pie chart? this would help with the visibility as well as usability ?

2022-09-21 08:55 UTC, pauldambra commented
0 to 100 cutout in 10% steps


cc @lottiecoxon 

<img width="877" alt="0-cutout" src="https://user-images.githubusercontent.com/984817/191460638-0dfffa36-ddb1-46ef-9be8-edd64905abf7.png">
<img width="885" alt="10-cutout" src="https://user-images.githubusercontent.com/984817/191460845-832b71a9-a326-4d54-a698-d95c8c684ed8.png">
<img width="883" alt="20-cutout" src="https://user-images.githubusercontent.com/984817/191460856-f6d75d6b-83da-4705-bc00-d71e9e2664e2.png">
<img width="886" alt="30-cutout" src="https://user-images.githubusercontent.com/984817/191460888-6c0845fe-5fa7-4df5-9afd-f2125db527a6.png">
<img width="883" alt="40-cutout" src="https://user-images.githubusercontent.com/984817/191460904-8f61ca2e-63db-42d1-ba36-706a8b86aa7a.png">
<img width="882" alt="50-cutout" src="https://user-images.githubusercontent.com/984817/191460924-e4b5ee35-3447-4e08-9da6-4680e99c6172.png">
<img width="885" alt="60-cutout" src="https://user-images.githubusercontent.com/984817/191460936-4ca9c04a-e1ea-49a8-9b07-57793607bc5e.png">
<img width="889" alt="70-cutout" src="https://user-images.githubusercontent.com/984817/191460983-41e1f02b-0bd8-473c-a9cd-842ed471e978.png">
<img width="885" alt="80-cutout" src="https://user-images.githubusercontent.com/984817/191461022-15d14965-f802-4dc4-b132-033a8b689e92.png">
<img width="892" alt="90-cutout" src="https://user-images.githubusercontent.com/984817/191461064-a59f820a-2695-4822-b8e6-a0ee91851a65.png">
<img width="886" alt="100-cutout" src="https://user-images.githubusercontent.com/984817/191461097-8531ef6c-b19c-4f73-b03e-fbe19505c451.png">

2022-09-23 10:02 UTC, lottiecoxon commented
0%, 60% and 70% I am happy with 

I was thinking about how to fix our hover issue with the super skinny charts and I was wondering would a layering method help or just be confusing and difficult to implement. (Feel free to pushback- these are just experimental ideas for now)

### Having an invisible selection area 
Idea: when you would hover over the invisible boundary for one of these sections it would react on the visible colour section. 

![Untitled_Artwork 116](https://user-images.githubusercontent.com/65415371/191936634-7c0e208d-7919-4696-93a9-e61d5a2906e0.jpg)

### Having a slightly faded area filled and a thinner section full 
This would basically create more space for hovering/reacting but with less of the intense colour?

![Untitled_Artwork 219](https://user-images.githubusercontent.com/65415371/191937245-e2493949-3b53-42dc-b8e4-b0a432a0ddb8.png)

2022-09-23 15:02 UTC, pauldambra commented
cc @mariusandra @lottiecoxon as a pie as agreed in https://posthog.slack.com/archives/C0368RPHLQH/p1663942196109679

![2022-09-23 16 00 59](https://user-images.githubusercontent.com/984817/191991517-a15cec60-e983-4343-8460-add1ee810a86.gif)

2022-09-26 10:39 UTC, lottiecoxon commented
I love the pie ❤️

2022-09-26 20:03 UTC, mariusandra approved these changes
Cakes at 100% look slightly broken when hovering:

![2022-09-26 22 02 12](https://user-images.githubusercontent.com/53387/192369133-0ff5f0ce-fe92-4325-b165-1d0edbeb2a48.gif)

otherwise, LGTM

2022-09-26 20:43 UTC, pauldambra commented on frontend/src/scenes/insights/views/LineGraph/PieChart.tsx
> +Chart.defaults.animation['duration'] = 0
we can at least move this to an included file... so at least we don't accidentally change it on one place without realising it's "required" by two

2022-09-26 20:43 UTC, pauldambra commented on frontend/src/scenes/insights/views/LineGraph/PieChart.tsx
> +                } as _DeepPartialObject<PluginOptionsByType<keyof ChartTypeRegistry>> & ChartPluginsOptions,
And turns out at some point in the changes has become unnecessary 🤷 🤣

2022-09-26 20:43 UTC, pauldambra commented
without hover offset when 100%

![pie2](https://user-images.githubusercontent.com/984817/192376201-89398f17-d4d7-4e75-af96-2737e8c9fcaf.gif)

2022-09-27 15:16 UTC, merged