feat: group capture customers
PostHog/posthog pull request #12553
Opened 2022-11-01 14:25 UTC by kappa90

## Problem
We need to group identify events for customers who are on billing v2, for better reporting.

Needs https://github.com/PostHog/billing/pull/23 to be merged

## Changes
- Add group identify when billing v2 is received from the billing service

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?
Tested locally

2022-11-02 07:43 UTC, benjackwhite requested changes

2022-11-02 07:43 UTC, benjackwhite commented on frontend/src/scenes/billing/v2/billingLogic.ts
> +    }),
Do we have to do this on the frontend? Seems like overkill to be sending the stripe_customer_id all the way through to the frontend just to track the group. Why don't we do this in the backend when we load from the billing service?

2022-11-03 08:19 UTC, benjackwhite approved these changes

2022-11-03 08:25 UTC, merged

2022-11-07 14:15 UTC, neilkakkar commented on ee/api/billing.py
> +            posthoganalytics.identify(
Good to know, thank you!

Good catch regarding properties, completely missed that here!

I remember adding a new group being necessary for some reason, so you should turn this into a capture call, at minimum.

I'd be curious to know how you plan to query this group, as if there's limited events with this new group type, there's limited analysis you can do on it.

Also, for the new group to show up in the UI, you'll need to do a `groupIdentify` somewhere atleast once.

2022-11-07 14:18 UTC, benjackwhite commented on ee/api/billing.py
> +            posthoganalytics.identify(
Hmmm personally I find this super confusing. It's pretty common that one wants to sync properties from a backend to your CRM (or analytics in this case). There is no related event rather we are just ensuring that the user is a attributed to that customer?

The `groupIdentify` part happens in the billing service