feat: dashboard templates
PostHog/posthog pull request #12753
Opened 2022-11-12 19:31 UTC by pauldambra

## Problem

I made a dashboard template in #12343. It was manual and difficult

And now @joethreepwood has asked for two more templates in #12732

This would be slow, fiddly and so error-prone.

Quoting Kent Beck: "for each desired change, make the change easy (warning: this may be hard), then make the easy change" (https://twitter.com/kentbeck/status/250733358307500032?lang=en)

## Changes

* adds dashboard templates as a concept
* lets you save a dashboard templates from a dashboard (behind a flag)
* adds a tab to the dashboards page to show templates and let you rename and delete them (behind a flag)

Once this is merged the two templates in #12732 can be saved as templates and then copied into a migration

## How did you test this code?

* added developer tests
* ran it locally
* TODO write cypress tests

2022-11-12 19:44 UTC, pauldambra commented on frontend/src/scenes/dashboard/dashboards/dashboardsLogic.ts
> +        filteredDashboardTemplates: [
GitHub really needs semantic diff. This file shows as all added but it's only this selector that has been added

2022-11-12 19:44 UTC, pauldambra commented on frontend/src/scenes/dashboard/dashboards/dashboardsLogic.ts
> +                let listToFilter: DashboardType[]
and this variable has been renamed

2022-11-12 19:44 UTC, pauldambra commented on frontend/src/scenes/dashboard/dashboards/dashboardsLogic.ts
> +                if (currentTab === DashboardsTab.Templates) {
and this guard for the new tab

2022-11-12 19:45 UTC, pauldambra commented on frontend/src/scenes/dashboard/newDashboardLogic.ts
> +            actions.getAllDashboardTemplates()
don't reset the modal when opening it, or you can't set values on the form when opening it

2022-11-12 19:48 UTC, pauldambra commented on posthog/api/test/dashboards/test_dashboard.py
> -    def test_dashboard_from_template(self):
deletions in this file are because the tests are moved to a new file

2022-11-14 10:55 UTC, andyvan-ph commented
Sounds good. Feature suggestions... Templates for insights as well. 😁

2022-11-15 13:08 UTC, pauldambra commented
![exporting-templates](https://user-images.githubusercontent.com/984817/201927300-9483c249-1d06-4bad-87db-68770e0b1b97.gif)

2022-11-16 13:10 UTC, mariusandra approved these changes
Sweet!

That's a lot of code though 😅. I definitely didn't follow every line of every test in detail. Overall looks good to me, just some small things:

1. The "save as template" menu option is there if you don't have the flag enabled.
2. In this interface:
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/53387/202186466-31ccae28-2ade-456a-bbdf-d7dfef5cf929.png">

- the first column is really wide... not sure what to do here if anything
- when we have just one export option, let's just call it "export as json" without the second level?

3. The first button "Create dashboard using this template" needs more line height to breathe. This is way too cramped. A two-line text button can't be the same height as a online text button

2022-11-18 13:07 UTC, pauldambra commented
@mariusandra thinking more on the "import from github"

Shall I do the laziest thing and dump the entire JSON into one field in the DB? 

Occurs to me I can then make a unique key on that field...... 🤔

2022-11-18 14:49 UTC, mariusandra commented
> @mariusandra thinking more on the "import from github"
> 
> Shall I do the laziest thing and dump the entire JSON into one field in the DB?
> 
> Occurs to me I can then make a unique key on that field...... 🤔

You can't get lazier than this:

https://github.com/PostHog/posthog/blob/d6bc434f98f67db06acf4fcf71845862e50c4783/posthog/api/plugin.py#L289-L293

... and it has worked just fine so far, so totally up to you. Don't over think it, it's a MVP after all. Later on we can make an optimised `https://respository.posthog.com/dashboards.json` endpoint, but for now, 🤷

2022-11-21 08:50 UTC, pauldambra commented
* users can save templates
    * in project or organization scope
    * dependent on permissions
* users can export templates 
* and import templates
* when a project is created a dashboard is created using a template
    * so at least one template has to be present before a team is created
    * so one template is included in the original migration that creates the templates

* we need to get templates into self-hosted instances
* and we want some templates to be global for cloud

other global templates are stored in a git repo

celery periodically retrieves templates from that repo and stores them
users can trigger a synchronous refresh from the repo

2022-11-24 18:30 UTC, pauldambra commented
## global templates can't be renamed or deleted

<img width="341" alt="Screenshot 2022-11-24 at 18 28 18" src="https://user-images.githubusercontent.com/984817/203848033-1ac7c7c7-5cb8-41cc-9e38-714c85dc7ad1.png">

## organization templates can't be renamed or deleted by non-org admins

<img width="326" alt="Screenshot 2022-11-24 at 18 29 12" src="https://user-images.githubusercontent.com/984817/203848059-9e1aaead-0d4a-47cc-a712-82adb05a1a62.png">

## project templates can be renamed or deleted

<img width="311" alt="Screenshot 2022-11-24 at 18 28 38" src="https://user-images.githubusercontent.com/984817/203848095-04c6f73c-bcaf-49ab-930a-8ae1578cebec.png">

2022-11-24 23:18 UTC, pauldambra commented
global templates are here: https://github.com/PostHog/templates-repository

2022-11-25 09:43 UTC, mariusandra requested changes
So, as we spoke, it'd be great to make this into a system similar to plugins, where we just download one `.json`, show it in an interface with a bunch of "install template" buttons. 

Rough and raw comment below and inline.

---------

I'm not really sure what should happen here:

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/53387/203942977-dbd5b73c-0311-49a6-af53-6b75d3452fd0.png">

Restarting Celery made this happen:

<img width="1444" alt="image" src="https://user-images.githubusercontent.com/53387/203943212-facf7f5c-f5a9-435d-a3c1-78b60f0a38e2.png">

... and it's not clear what are my dashboards, what got added, etc. I also have no idea what do the new templates contain -> the label "website traffic" gives me limited info. 

Something that would help is a description line under the template name. Alternatively, "preview mode" that shows what the template contains before you create a real tempalte with it.

I think this doesn't need to be a submenu:

<img width="396" alt="image" src="https://user-images.githubusercontent.com/53387/203943735-7b5e0ae1-f4c0-46b3-ad26-2a4e93d5da20.png">

Exports fail for me:
![2022-11-25 09 13 34](https://user-images.githubusercontent.com/53387/203944293-18b4173d-8bcf-421f-b6e8-ec7278163d41.gif)

<img width="916" alt="image" src="https://user-images.githubusercontent.com/53387/203944275-284cd6db-133f-4e3b-9062-685b24d7909b.png">

I did `pip install -r requirements.txt` and restarted celery, but that didn't bring those itertools into the game.

2022-11-25 09:43 UTC, mariusandra commented on frontend/src/scenes/dashboard/dashboardTemplates/dashboardTemplateLogic.tsx
> +export async function pollTemplateRefreshStatus(task_id: string): Promise<void> {
This feels like a lot of complexity. Imagine time goes on and we have 30 dashboard templates. I understand in that case why we need to do this in a task, but... why would we want to automatically download and install all of them? I imagined the "repository" to work similar to plugins -> you get a list of templates, and click "download" next to the templates you care about. You know, like a repository :).

And in this case, if the only thing the backend does is to refresh one JSON file (and store it in redis like we do for plugins), all this queying and fetching falls off.

2023-01-06 07:31 UTC, closed without merging