feat(data-exploration): person and cohort tables
PostHog/posthog pull request #13136
Opened 2022-12-05 15:34 UTC by mariusandra

## Problem

Follow up to https://github.com/PostHog/posthog/pull/13116

## Changes

Replaces persons and cohort tables with data exploration versions.

![2022-12-05 16 28 45](https://user-images.githubusercontent.com/53387/205676272-843962fa-4f1f-42b2-a3eb-a4d9f48002fc.gif)
![2022-12-05 16 29 05](https://user-images.githubusercontent.com/53387/205676344-e08d5e27-8a21-4d2f-a6a8-b853be1d27c9.gif)

## TODO

- Add `copy` button for `id`
- Add delete button

## How did you test this code?

2022-12-07 14:40 UTC, mariusandra commented
Actually ready for a look!

2022-12-08 12:15 UTC, thmsobrmlr requested changes
Great! Only one real issue that I ran into: The delete button for persons in cohorts does not show up for me.

Besides that some UX details regarding exports on the persons page, and a few inline comments. Nothing that needs to change, just observations:
- The exported CSV for "selected columns" contains a `person.$delete` column, which is probably unnecessary.
- The exported CSV for "all columns" contains a `value_at_data_point` column, which is probably unnecessary.
- Not related to this PR, but we might be able to improve this with data exploration - The exported CSV contains columns `id` and `distinct_ids.0`, but I can't filter for these columns (unclear what property I should use).
- The export button does not reflect the number of selected columns this any more:
    
    Before
    <img width="187" alt="Screenshot 2022-12-08 at 12 00 58" src="https://user-images.githubusercontent.com/1851359/206430405-d7239799-b6ef-4593-8393-1d1b149fbff4.png">

    After
    <img width="145" alt="Screenshot 2022-12-08 at 12 00 54" src="https://user-images.githubusercontent.com/1851359/206430408-9cc31fc5-0fd8-42b5-9eb8-6e36724ec9e7.png">

2022-12-08 12:15 UTC, thmsobrmlr commented on frontend/src/scenes/persons/PersonsScene.tsx
> +            <PersonPageHeader />
Can we remove this header from `Persons`?

2022-12-08 12:15 UTC, thmsobrmlr commented on frontend/src/scenes/persons/PersonsScene.tsx
> +    component: PersonsScene,
Can we remove the scene export from `Persons`?

2022-12-09 22:57 UTC, mariusandra commented on frontend/src/scenes/cohorts/CohortEdit.tsx
> +                {typeof cohort.id === 'number' && (
Unfortunately this is needed for typing below when passing the cohort id to the query :/

2022-12-09 23:00 UTC, mariusandra commented
Thanks for the review! Fixed all the feedback, I hope. Would love to get this in to help move along work on the two [stacked](https://github.com/PostHog/posthog/pull/13203) [PRs](https://github.com/PostHog/posthog/pull/13233) on top of this, plus the [event table regressions](https://github.com/PostHog/posthog/issues/13223)... 

> * The exported CSV for "selected columns" contains a `person.$delete` column, which is probably unnecessary.
Removed!

> * The exported CSV for "all columns" contains a `value_at_data_point` column, which is probably unnecessary.
This is there also on the current live persons table export. I propose we deal with it later 🙃 

> * Not related to this PR, but we might be able to improve this with data exploration - The exported CSV contains columns `id` and `distinct_ids.0`, but I can't filter for these columns (unclear what property I should use).

Hopefully HogQL will help here

> * The export button does not reflect the number of selected columns this any more:

Fixed!

2022-12-12 11:33 UTC, thmsobrmlr approved these changes
🚢  it!

2022-12-12 11:33 UTC, thmsobrmlr commented on frontend/src/scenes/cohorts/CohortEdit.tsx
> +                {typeof cohort.id === 'number' && (
I think a comment would be great in that case :)

2022-12-12 13:42 UTC, merged