fix (webhooks): Add shorter timeouts for webhooks
PostHog/posthog pull request #13309
Opened 2022-12-13 19:15 UTC by timgl

## Problem

Webhooks can take a long time to time out, causing issues elsewhere

## Changes

Reduce timeout to 10 seconds

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2022-12-13 19:39 UTC, Twixes requested changes
I wrote this a while ago, so took a look 👀

2022-12-13 19:39 UTC, Twixes commented on plugin-server/src/worker/ingestion/hooks.ts
> +            signal: (AbortSignal as any).timeout(HOOK_TIMEOUT),
Why `as any`? It's a bad code smell

2022-12-13 19:39 UTC, Twixes commented on plugin-server/src/worker/ingestion/hooks.ts
> +        ;(AbortSignal as any).timeout ??= function timeout(ms: number) {
Monkey-patching `AbortSignal` globally makes me feel dirty… Let's just use `addEventListener`  for monitoring (https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/abort_event#examples)

2022-12-13 19:42 UTC, Twixes commented
100% in favor of reducing the timeout, my only point is we can do this without overriding built-ins :)

2022-12-14 19:42 UTC, Twixes commented
Annoyingly we cannot quite _track_ those timeouts because all the options are blocked :/

1. Monkey-patching removes all safety guarantees and it's hard to say if it actually works.
2. `node-fetch` v2 doesn't support Node 18's native `AbortSignal.timeout()` .
3. `node-fetch` v3 does support `AbortSignal.timeout()`, but it's an ES module, and the rest of the plugin server is CommonJS. We _could_ migrate the plugin server to ES modules, but this is definitely beyond the scope of this PR (+ this would affect plugins).
4. As we're on Node 18 now, we can also ditch `node-fetch` and use the native `fetch` API – this is probably best long-term, but this would require a slightly different approach to mocking in hook tests, which I don't wanna spend time on now.

So let's just use the `timeout` argument to `fetch`, which achieves our goal, the only downside being lack of timeout metrics.

2022-12-14 21:48 UTC, hazzadous commented
> So let's just use the timeout argument to fetch, which achieves our goal, the only downside being lack of timeout metrics.

Better than nothing. btw what response do we get from `fetch` on timeouts? Is there nothing we can infer from this?

2022-12-15 11:27 UTC, Twixes commented
Ah of course, that's an `error.name == "AbortError"`. Theoretically that should be captured by Sentry, right?

2022-12-15 14:58 UTC, Twixes approved these changes
Looks like this should work, let's just get it in.

2022-12-15 14:58 UTC, merged