feat: capture performance opt in
PostHog/posthog pull request #13348
Opened 2022-12-15 11:23 UTC by pauldambra

## Problem

set up for enabling capturing performance alongside enabling performance logs

## Changes

![optin](https://user-images.githubusercontent.com/984817/207847043-08d04c1a-2b58-4ef1-8b9a-34045a94aade.gif)

## How did you test this code?

👀

2022-12-15 21:12 UTC, benjackwhite commented on frontend/src/scenes/session-recordings/settings/SessionRecordingSettings.tsx
> +                        disabled={!currentTeam?.session_recording_opt_in}
I think we could just remove this disabled line as the performance capture is not tightly coupled in the JS

2022-12-16 00:03 UTC, pauldambra commented on frontend/src/scenes/session-recordings/settings/SessionRecordingSettings.tsx
> +                        disabled={!currentTeam?.session_recording_opt_in}
```suggestion
```

2022-12-21 11:59 UTC, benjackwhite approved these changes

2022-12-21 12:04 UTC, benjackwhite requested changes
Started fixing the test and realised - we should not include the web performance as part of recordings. It limits us too much for the future. I'm going to move it out to a top-level property

2022-12-21 12:11 UTC, benjackwhite approved these changes
I approve of my changes

2022-12-21 13:53 UTC, merged