fix: cannot create an insight onto a dashboard when no permissions
PostHog/posthog pull request #13435
Opened 2022-12-20 17:23 UTC by pauldambra

## Problem

see this community slack thread: https://posthogusers.slack.com/archives/C01GLBKHKQT/p1671547613708909

When duplicating an insight we POST the insight to the insight API. One of the results is a tile is created to link the new insight to any dashboard the existing insight was on.

In the thread we discuss that may not be desired... but also that you can duplicate an insight onto a dashboard you don't have permissions to change. It turns out permissions were enforced when PATCHing an insight but not when POSTing

## Changes

* checks dashboard permissions on insight create
* checks dashboard permissions on dashboard duplication
* shows a toast when duplication fails

<img width="601" alt="Screenshot 2022-12-20 at 16 49 26" src="https://user-images.githubusercontent.com/984817/208721417-6cd93961-90d8-4ae1-8dc1-ec7cee9448d4.png">

## How did you test this code?

running it locally

2022-12-21 11:06 UTC, Twixes requested changes
Definitely deserves to be fixed! Overall this makes sense, I left some notes on the details though

2022-12-21 11:06 UTC, Twixes commented on posthog/api/dashboards/dashboard.py
> +                raise PermissionDenied(f"You don't have permission to add insights to dashboard: {use_dashboard}")
To be in line with `insight.py`:
```suggestion
                raise PermissionDenied(f"You don't have permission to add insights to dashboard: {existing_dashboard.name}")
```

2022-12-21 11:06 UTC, Twixes commented on posthog/api/insight.py
> +            insight.last_refresh = now()  # set last refresh if the insight is on at least one dashboard
This is only a refactor, but I wonder, do we actually refresh the data when this happens?

2022-12-21 11:06 UTC, Twixes commented on posthog/api/test/dashboards/test_dashboard.py
> +        ]
Considering `test_cannot_duplicate_dashboard_with_no_permissions_to_edit_it` requires these, it should probably be in `ee/api/test/test_dashboard.py` (there all the features are already available)

2022-12-29 15:53 UTC, pauldambra commented
going to queue this behind #13492

2023-01-16 07:31 UTC, closed without merging

2023-01-16 15:46 UTC, Twixes commented
Has this been queued somewhere else? @pauldambra 👀