feat: Add support for ?team_id to switch to that team if allowed
PostHog/posthog pull request #13453
Opened 2022-12-21 17:25 UTC by benjackwhite

## Problem

Issues like this occur as we have no way of making sure the person opening a URL is on the correct project.

## Changes

* Adds universal support for `team_id` as a search param that will check if the user has permissions for that team and switch them to it if it is different to their current team
* Adds support for this to the recordings Share modal.

We could start adding this all over the place, at the very least for links that get sent around like via emails / slack etc. We could consider having some routing magic in the frontend to always append this to URLs and all of a sudden the problem is almost completely solved 😉

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

No tests yet

2022-12-21 20:26 UTC, mariusandra reviewed
I think this is fine to add and use as an escape hatch when we can't get the project ID any other way. I'd rename it to `projectId`, because 1) camelcase and frontend, 2) we call these things projects in the UI, and users see query parameters (remember, they build websites for a living).

However... why not send the session recording ID as a regular `?search` query param instead? That way the backend knows what to do, and life is easy.

> We could start adding this all over the place, at the very least for links that get sent around like via emails / slack etc. We could consider having some routing magic in the frontend to always append this to URLs and all of a sudden the problem is almost completely solved 😉

Well, no, please let's not add `?yukyuk` _everywhere_. In this scenario, let's just add it in front of the URL, like `https://app.posthog.com/projects/2/insights/:shortid`.

Also CC @Twixes who has been a keen team lead in "Team Nail Team IDs in API URLs"

2022-12-21 20:26 UTC, mariusandra commented on frontend/src/scenes/session-recordings/player/share/playerShareLogic.ts
> +                    team_id: values.currentTeam?.id,
```suggestion
                    projectId: values.currentTeam?.id,
```

2022-12-21 20:26 UTC, mariusandra commented on posthog/middleware.py
> +            team_id = request.GET.get("team_id")
```suggestion
            team_id = request.GET.get("projectId")
```

2022-12-21 21:45 UTC, mariusandra commented
To implement `/project/:id`, I suggest updating `kea-router`-s [configuration](https://keajs.org/docs/plugins/router/#configuration-options) and adding some variation of:

```
  pathFromRoutesToWindow: (path) => `/project/${getDefaultTeamId()}/${path}`,
  pathFromWindowToRoutes: (path) => path.replace(/^\/project/\d+/, ''),
```

Then somewhere higher up in the logic tree (sceneLogic? appLogic?), read the actual project ID from the URL and do magic if it's not the same one that's in the app context (aka the session).

2022-12-21 22:41 UTC, benjackwhite commented
I don't care too much about whether it is `/project/1/resource/foo` or `/resource/foo?pid=1`. I've seen both all over the internet and they seem to work fine either way 🤷 this solution can likely be tweaked pretty easily to suite either format.

I think the hash param recoridng ID was done basically due to the PersonsModal as there is so much nasty navigation stuff in there already which the Recordings modal didn't want to get away with. Either way I think the projectId in the URL is the RightWay™️ to go which removes any real need for the Auto switching based on resource type I think.

2022-12-21 22:51 UTC, mariusandra commented
One of the two is slicker than the other ;).

2022-12-22 14:26 UTC, Twixes requested changes
I'm still of a strong opinion that if we want to include project/org ID in the URL, it'd be much better to do it this way:
`https://app.posthog.com/<:org_slug>/<:team_id>/recordings/1853a2b9f3cf55-071c57e8202081-18525635-384000-1853a2b9f3d2a2e`.

This PR is really about routing instead of just some page params, and routing-wise solutions like `?pid=3997` don't look great, but also make it harder to reason about how organizations and projects are structured.

We did have a project to move over to `/<:org_slug>/<:team_id>/...`, but put it on pause when we solved the burning user pain by switching based on resource ID. However, that definitely is just a hack (as is `@current`), and we still need a more scalable solution for the whole app (recordings, settings, project home. etc.) Perhaps it's time to pick that up again?

I think initially the scope of the migration was too ambitious, because it involved moving over all the logics to be keyed by project ID for reload-less project-changing. It should be relatively straightforward if we always just reload the page though – only need some URL prefix handling.

2022-12-22 14:26 UTC, Twixes commented on frontend/src/layout/navigation/ProjectSwitcher.tsx
> +function CurrentProjectButton({ onClose }: OnCloseProps): JSX.Element | null {
This is a button, it can't be closed, it should just have `onClick`

2022-12-22 14:26 UTC, Twixes commented on frontend/src/layout/navigation/ProjectSwitcher.tsx
> +function OtherProjectButton({ team, onClose }: { team: TeamBasicType } & OnCloseProps): JSX.Element {
Same here for `onClose`

2022-12-22 14:26 UTC, Twixes commented on frontend/src/layout/navigation/ProjectSwitcher.tsx
> +type OnCloseProps = {
We generally use a convention where `FooProps` means props of component `Foo`, and there is no `OnClose` component, so this break that. Maybe this'd be like `OnClosePropsMixin`. But probably the clearest way is just naming it `ProjectSwitcherOverlayProps`.

2022-12-22 15:17 UTC, benjackwhite commented
> I'm still of a strong opinion that if we want to include project/org ID in the URL, it'd be much better to do it this way: `https://app.posthog.com/<:org_slug>/<:team_id>/recordings/1853a2b9f3cf55-071c57e8202081-18525635-384000-1853a2b9f3d2a2e`.

I _think_ I'm strongly against that opinion 😉 - I think it is a "technically correct but practically terrible" decision. Even just in your example we would have a url like: `https://app.posthog.com/1853a2b9f3cf55-071c57e8202081-18525635-384000-1853a2b9f3d2a2e/13459/recordings/1853a2b9f3cf55-071c57e8202081-18525635-384000-1853a2b9f3d2a2e` which is long and scary and unreadable. 

Even if we had "shortId" style slugs we would still end up with something like `https://app.posthog.com/a34ds7gn/0skiz84/recordings/1853a2b9f3cf55-071c57e8202081-18525635-384000-1853a2b9f3d2a2e` which _still_ looks dodgy and unreadable.

 
> This PR is really about routing instead of just some page params, and routing-wise solutions like `?pid=3997` don't look great, but also make it harder to reason about how organizations and projects are structured.

I don't disagree with the argument that this stuff should be coded in the path and not a param but I don't see any need to include org. We could go for something like
```
https://app.posthog.com/p/13245/recordings/foobar
```

There is never a case where we don't know the org (it is always the org that that project belongs to) and most people only have one org anyways...

> We did have a project (so-to-speak) to move over to `/<:org_slug>/<:team_id>/...`, but put it on pause when we solved the burning user pain by switching based on resource ID. However, that definitely is just a hack (as is `@current`), and we still need a more scalable solution for the whole app (recordings, settings, project home. etc.) Perhaps it's time to pick that up again?
> I think initially the scope of the migration was too ambitious, because it involved moving over all the logics to be keyed by project ID for reload-less project-changing. It should be relatively straightforward if we always just reload the page though – only need some URL prefix handling.

I'm happy to revert this PR down to a minimal "if we see `pid`, change the team so that we can at least get shared links working with this as "hack" before the proper solution. Although it makes me sad to have a practically workable solution that is better than what we currently have, even if it might be just a stepping stone towards the "real" solution.

@mariusandra @Twixes if you feel strongly enough that this should not go ahead, even as an interim solution, I'm happy to back out and leave it broken until there is the energy to tackle it "properly" 👍

2022-12-22 17:00 UTC, benjackwhite commented
Removed the auto-adding param code so we still get the improvements without making this a prominent feature (leaving it as an "escape hatch")

2022-12-22 20:33 UTC, mariusandra requested changes
There's a test failing with some URL oddity that won't be the last one we'll see:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/53387/209220218-7297cd44-594a-4596-8ca9-c6b6eba78de0.png">

Gonna request changes because I _strongly_ believe we should fix this problem only once. The task of "switch the project when the ID is in the URL" is an easy one, but the follow up of "make sure the project is always in the URL" is an uphill struggle if we use search params. This struggle will involve everyone, and I don't want to climb it :).

Think of all the logics, `urlToActions`, `router.actions.push`-s, scenes that assume full ownership over all search params, etc. We'll be in a very annoying state where a million tiny fixes will be needed to get everything working just right. It's not worth it.

Let's just go for `https://app.posthog.com/p/:id/events`.

Like I wrote above, kea-router has built in support for automagically making part of the URL disappear for the rest of the app. We wouldn't have to change _any_ client side code other than some higher level routing initialization for this to work. 

We don't need the organization in the URL, the project is enough. I'm a bit worried about numeric IDs (security risk, will get flagged by tools), so a `shortId` approach will be better. However even a two-fold `/project/:numeric-id` and `/p/:short-id` stopgap would be great.

2022-12-23 08:02 UTC, benjackwhite commented
Alrighty then. I will leave this PR up I could do with someone like yourself taking it over as you seem to have more understanding of how to get this stuff done. It can wait till the New Year I guess.

2022-12-23 08:06 UTC, benjackwhite commented
> There's a test failing with some URL oddity that won't be the last one we'll see:

@mariusandra in fairness that tests should have been updated because it's testing exactly where we **do** want to have the URL including the pid 😅

2023-01-10 07:31 UTC, closed without merging