feat: add billing rate limiter to plugin server
PostHog/posthog pull request #13519
Opened 2022-12-30 12:51 UTC by kappa90

## Problem
We want to rate limit organizations that are above their billing limit.

## Changes
Introduce a `RateLimiter` that checks if an organization_id is stored in either an event limited or session recording limited set of ids in Redis.
For now, we just log the rate limiting to `statsd`, we don't drop anything.

@benjackwhite the way you had created the rate limiter using promises didn't work so I simplified it, let me know if you think something is fishy

## How did you test this code?
Added tests for the rate limiter

2023-01-03 08:14 UTC, benjackwhite requested changes
I'm happy to be challenged here but I think that this code means that every 60 seconds we have the danger of hanging whilst we contact redis AND contacting redis 100s of times until the first request completes. 

Before we had a local promise object so that we could synchronously "cache" the in-progress call" as well as a check to return the existing localCache once it was loaded once (we don't care about it being 100% up to date). 

Ping me if you want some support with this but I would strongly NOT recommend merging as it is currently.

2023-01-03 08:14 UTC, benjackwhite commented on plugin-server/src/utils/rate-limiter.ts
> +    }
I notice you got rid of the local promise object. If 20 requests came in at once, would this not trigger 40 parallel redisZrange calls that are all doing the same thing?

2023-01-03 08:15 UTC, benjackwhite commented
Also this should definitely get a review from the pipeline team as this path is quite sensitive to any increase in delays

2023-01-05 14:25 UTC, benjackwhite requested changes

2023-01-05 14:25 UTC, benjackwhite commented on plugin-server/src/utils/rate-limiter.ts
> +                this.localCacheRefreshingPromise = this.refreshCaches().then(() => {
This might want to be `.finally()` instead of `.then`

2023-01-05 14:25 UTC, benjackwhite commented on plugin-server/src/utils/rate-limiter.ts
> +            if (!this.localCacheExpiresAt) {
Comment here might help for the future
```suggestion
            if (!this.localCacheExpiresAt) {
              // We only want to wait for the cache if we haven't at least once loaded the cache
```

2023-01-05 20:16 UTC, hazzadous commented on plugin-server/src/utils/db/db.ts
> +            const timeout = timeoutGuard('ZRANGE delayed. Waiting over 30 sec to perform ZRANGE', {
It doesn't look like this actually times anything out, but just delays logging a message? Is there any way to set zrange to timeout?

2023-01-30 08:19 UTC, kappa90 commented
We can close this one as @benjackwhite has been working on a different approach

2023-01-30 08:19 UTC, closed without merging