feat: data management activity log - event definition backend
PostHog/posthog pull request #14886
Opened 2023-03-23 18:41 UTC by pauldambra

## Problem

We can change things in data management. But what did we change? And who?!

stacked on top of  #14877 

## Changes

Adds the backend work for activity logging in event definitions only

![2023-03-23 18 21 22](https://user-images.githubusercontent.com/984817/227315516-882d45cb-34dd-4905-b0d6-43bf772f736a.gif)

## How did you test this code?

a few developer tests and 👀 locally

2023-03-23 18:41 UTC, pauldambra commented on posthog/api/routing.py
> +        add_organization_id = {"organization_id": self.organization_id} if self.organization_id else {}
I needed organization_id in the serializer and assumed it's cheap to add here...

2023-04-05 22:20 UTC, Twixes requested changes
This is great! Found just two issues:

The first, smaller one is that the definition activities (at least deletion ones) seem to omit the acting user's name:
<img width="204" alt="Screenshot 2023-04-06 at 00 10 14" src="https://user-images.githubusercontent.com/4550621/230223799-65f9157f-5929-4ba4-9b62-1913d41daaf4.png">
(e.g. insights history on this branch looks like this: "**Employee 427** created the insight: Pageview")

The second, bigger issue is that the logs don't show when the definition was _created_. We need to register those activities from the plugin server for that. Or we can just add an `AlertMessage` to the `History` scene. It seems confusing to expose this behavior with no explanation though.

2023-04-18 10:45 UTC, pauldambra commented
Added a caption to explain auto changes aren't captured. It'd be nice but my guess is it would be a pain, so better as a follow-up

<img width="853" alt="Screenshot 2023-04-18 at 11 43 47" src="https://user-images.githubusercontent.com/984817/232753810-bd51088d-b5e5-4950-aa0e-05047d6fd826.png">

2023-04-20 18:06 UTC, Twixes approved these changes

2023-04-20 19:28 UTC, merged