Changes to make person editable #89
PostHog/posthog pull request #1491
Opened 2020-08-24 07:46 UTC by cr33dx

## Changes

Make the person's table data editable(Front-end)

<img width="1440" alt="Screenshot 2020-08-24 at 1 14 33 PM" src="https://user-images.githubusercontent.com/8844755/91017357-c60d2380-e60b-11ea-8c42-7c2b63fb6612.png">

## Checklist

- [x] All querysets/queries filter by Team (if this PR affects any querysets/queries)
- [x] Backend tests (if this PR affects the backend)
- [x] Cypress E2E tests (if this PR affects the front and/or backend)

Cannot Run Cypress tests on docker environment.

2020-08-24 10:26 UTC, yakkomajuri commented
Hey @cr33dx! First of all, thanks for this! I know how you had some trouble setting up a local instance so I appreciate you taking the time. 

However, I believe this doesn't address the issue in full. I think the idea is that one could edit the properties on the frontend but have those changes be reflected in the backend and saved in the database. I think perhaps the name of the issue could have led to some confusion, but the idea is the same PR makes it so that the properties can be edited on the PostHog UI by making changes to both our frontend and backend. I believe the approach here is to establish a new endpoint for the API that allows properties to be changed for a given user.

2020-08-24 10:28 UTC, yakkomajuri requested changes
Backend changes needed

2020-08-24 11:51 UTC, cr33dx commented
Got it @yakkomajuri

2020-08-24 12:02 UTC, yakkomajuri commented
If you have any questions feel free to send them over!

2020-08-24 13:25 UTC, cr33dx commented
How does the front end code look?

On Mon, 24 Aug 2020 at 17:33, Yakko Majuri <notifications@github.com> wrote:

>
>
> If you have any questions feel free to send them over!
>
>
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PostHog/posthog/pull/1491#issuecomment-679085206>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACDPLU75DDBU5P6JXDNLH3TSCJJIDANCNFSM4QJGRIYQ>
> .
>
>
>

2020-08-25 16:48 UTC, yakkomajuri commented
Seems ok, but I haven't looked in too deep, would rather put out a full review once this is all done!

2020-08-25 23:09 UTC, Twixes commented
Happy to review as soon as this covers the backend in addition to the frontend!

2020-09-01 13:53 UTC, timgl commented
@cr33dx Hey, did you get a chance to take another look at the backend for this?

2020-09-01 14:06 UTC, cr33dx commented
@timgl was busy over the week will work on it this weekend plus I’m new to django so took a while to get around the concepts.

2020-09-01 14:08 UTC, timgl commented
No worries at all! Let me know when you get stuck or need any help :)

2020-09-07 08:28 UTC, cr33dx commented
Hi Team apologies for the delay not getting time to look at the backend cause of work at job.

2020-09-07 10:43 UTC, timgl commented
@cr33dx I just double checked, there's no need to make any backend changes. All you need to do is send a PATCH request to `api/person/:person_id` with the new properties. That should work!

2020-09-07 19:48 UTC, cr33dx commented
don't know why the cypress tests are failing things are working on my end when i checked few of the failed checks.
one of them was 
`data-attr=funnel-viz is expected to be on DOM` 
and it was there

<img width="1680" alt="Screenshot 2020-09-08 at 1 15 58 AM" src="https://user-images.githubusercontent.com/8844755/92414260-24d8ae00-f171-11ea-837f-09a7ac7b6967.png">

2020-09-09 13:38 UTC, yakkomajuri commented
Cypress tests might not have anything to do with you @cr33dx - I'll aim to review this today or tomorrow

2020-09-09 14:56 UTC, yakkomajuri commented
Hey @cr33dx this isn't working just yet - You need to pass the data to be updated along with your PATCH request

2020-09-09 16:11 UTC, cr33dx commented
hi @yakkomajuri i'm passing req with the new data and getting 200 on backend. i'll replace the front end with the modal though.

2020-09-09 17:51 UTC, yakkomajuri commented on frontend/src/lib/utils.js
> +        api.update('api/person/' + person.id).then(() => {
@cr33dx You will get a 200 on the PATCH request even if you do not send any data. Here, `update` takes `data` as a second parameter

2020-09-09 17:52 UTC, yakkomajuri commented
To make sure this is working, you should refresh the page after making the changes and see if they persist

2020-09-09 18:15 UTC, cr33dx commented
@yakkomajuri really sorry did not saw that the latest commit is updating the person's data in backend.

2020-09-09 20:16 UTC, cr33dx commented
<img width="1680" alt="Screenshot 2020-09-10 at 1 40 17 AM" src="https://user-images.githubusercontent.com/8844755/92648650-5e432200-f307-11ea-91dd-c898f080b46d.png">
<img width="1680" alt="Screenshot 2020-09-10 at 1 40 00 AM" src="https://user-images.githubusercontent.com/8844755/92648664-64d19980-f307-11ea-9fad-62ad253aa052.png">

2020-09-14 10:04 UTC, yakkomajuri requested changes
Thanks @cr33dx! This is great, but there are still some issues here:

1. I'm unable to load the profiles of people who only have the `is_demo` property and nothing else
2. I'm unable to edit `is_demo`
3. The button for saving the person's data does not work for me when I change the screen's dimensions with DevTools. The delete button right above it works just fine.
4. The system for checking if the person's details were updated is not "smart" - this _isn't a big deal_ but it would be nice if it knew that I changed and then went back, rather than just setting `personChanged` blindly on every change. 
5. Also not a _requirement_, but I feel like I would prefer clicking a button to toggle on editing rather than being able to edit by default. No need to worry about this before points 1-3 are solved, however.

2020-09-14 14:08 UTC, cr33dx commented
Hi, i did not get the first point.

On Mon, 14 Sep 2020 at 15:34, Yakko Majuri <notifications@github.com> wrote:

>
>
> *@yakkomajuri* requested changes on this pull request.
>
>
>
>
> Thanks @cr33dx <https://github.com/cr33dx>! This is great, but there are
> still some issues here:
>
>
>
>
>
>    1. I'm unable to load the profiles of people who only have the is_demo
>    property and nothing else
>
>    2. I'm unable to edit is_demo
>
>    3. The button for saving the person's data does not work for me when I
>    change the screen's dimensions with DevTools. The delete button right above
>    it works just fine.
>
>    4. The system for checking if the person's details were updated is not
>    "smart" - this *isn't a big deal* but it would be nice if it knew that
>    I changed and then went back, rather than just setting personChanged
>    blindly on every change.
>
>    5. Also not a *requirement*, but I feel like I would prefer clicking a
>    button to toggle on editing rather than being able to edit by default. No
>    need to worry about this before points 1-3 are solved, however.
>
>
>
>
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/PostHog/posthog/pull/1491#pullrequestreview-487604528>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACDPLU6RYNJ7WCKXHGHQMNLSFXTEDANCNFSM4QJGRIYQ>
> .
>
>
>

2020-09-18 11:19 UTC, yakkomajuri requested changes
@cr33dx thanks once more! This is almost there and I'm so excited for this feature. I put out some minor fixes to wording and style (mostly responsiveness-related), but there's one thing that's still going wrong: We can now handle strings and booleans as properties, but numbers for example don't work. You can refer to [this comment and PR](https://github.com/PostHog/posthog/pull/1666#issuecomment-694030031) for the types of the properties we support. Once we make sure all those properties are correctly handled, this should be good to go!

2020-09-18 11:26 UTC, yakkomajuri commented
Note to self: 

**On new PRs** implement adding a property, deleting a property, and update the delete person confirm to a modal.

2020-09-23 18:14 UTC, cr33dx commented
- If a property is left empty by user we mark it as null.
- Using this (object)[https://github.com/PostHog/posthog/blob/master/frontend/src/lib/components/PropertyKeyInfo.js], disable posthog's internal key value pair.

2020-09-28 15:00 UTC, cr33dx commented
hi guys any update?

2020-09-28 15:33 UTC, Twixes commented
Yep, will take a look in a moment!

2020-09-30 15:22 UTC, Twixes approved these changes
A bit rough around the edges, but it's pretty practical and we can always improve it.

2020-09-30 15:22 UTC, merged