feat: Add filing Zendesk tickets from the app help
PostHog/posthog pull request #15018
Opened 2023-04-10 15:34 UTC by tiina303

## Problem

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2023-04-11 14:44 UTC, benjackwhite requested changes

2023-04-11 15:29 UTC, corywatilo commented on frontend/src/lib/components/HelpButton/HelpButton.tsx
Strongly against pushing people away from asking a question through Squeak! One of the main goals is to _reduce_ the 1:1 support burden. The more public questions/answers we have, the more likely people can self-support.

Also not sure why we'd kill the feedback tool in lieu of this. Why don't we just relabel to _Report a bug_? Leaving under the menu seems fine as we don't want to make it _too_ easy to spin up a ticket when really they may be able to self-support using other methods.

2023-04-12 17:44 UTC, tiina303 commented
Discussed with @pjhul  and came to the conclusion that we should make it be "Bug / Feedback" (pending @lharries  thoughts on the feedback side). We'll remove the "Ask us a Question" part too as that links to posthog.com/questions, which means we lose all the context (the user likely meant to submit bug/feedback or check the docs).
We don't need nor want bug reports to be a squeak question, it's probably better to just fix the issue. Later once docs are inline we might have access to squeak there, which again will allow us to have all the context needed.

We likely want to remove filing GH issues link too, so we don't lose context and make the menu shorter and nicer.

2023-04-13 01:29 UTC, lharries commented
Adding my input as requested by Tiina but realize there's quite a few people giving input here

Agreed with the suggestion of "Bug / Feedback" if it's in the topbar too. 

We could still keep the "Question" dropdown but for free users remove the form and instead show a message telling them to add a question on the docs via Squeak?

One extra thing - I'd suggest we add in a variant of this code so that the session recording link with the timestamp is added inline to the support ticket and slack ticket. This helps jump directly to the issue and often comes in handy during longer session recordings

https://github.com/PostHog/posthog/pull/14627/files 

```
const LOOK_BACK = 30
const recordingStartTime = Math.max(
  Math.floor(
      (new Date().getTime() - (posthog?.sessionManager?._sessionStartTimestamp || 0)) / 1000
  ) - LOOK_BACK,
  0
)
const sessionRecordingLink = `${window.location.origin}/recordings/${posthog?.sessionRecording?.sessionId}?t=${recordingStartTime}`
```

2023-04-13 01:32 UTC, lharries commented on frontend/src/lib/components/Support/supportLogic.ts
> +            },
if it's feedback, can we also log it as feedback with this:

```
posthog.capture('Feedback Sent', {
    '$feedback': 'Can you make the logo bigger?'
})
```

2023-04-13 01:33 UTC, lharries commented on frontend/src/lib/components/Support/supportLogic.ts
> +                    posthog.capture('support_ticket', properties)
Will this also be forwarded onto slack?

2023-04-13 03:52 UTC, corywatilo commented
> show a message [to free users] telling them to add a question on the docs via Squeak?

Only problem with that is since we de-prioritize responding to free users, we could end up with a higher percentage of unanswered questions which may make the website look like a ghost town.

2023-04-13 12:04 UTC, tiina303 commented
Reordered the menu to remove GH issue link (no context problem) and remove question from the form for now (so we can ship this asap and address that in follow-up PRs).

2023-04-13 12:54 UTC, timgl approved these changes

2023-04-13 13:19 UTC, benjackwhite requested changes
I think this needs to replace the "Feedback" button in the top bar before it can be merged personally. Once we have that removed, then I'm fine with this

2023-04-13 13:21 UTC, benjackwhite approved these changes

2023-04-13 13:21 UTC, merged