refactor(lemon-ui): Build `LemonSelect` on top of `LemonMenu`
PostHog/posthog pull request #15116
Opened 2023-04-17 14:41 UTC by Twixes

## Changes

#15084 introduced a new `LemonMenu` abstraction for all sorts of menus. `LemonSelect` is a menu. So this refactors `LemonSelect` to use `LemonMenu`.

## How did you test this code?

Relying on E2E and visual regression tests.

2023-04-19 14:07 UTC, benjackwhite requested changes
Flyby - seems from the snapshots that the fullwidth view is borked?

2023-04-19 16:11 UTC, thmsobrmlr approved these changes
👌 

Don't see what you're seeing @benjackwhite. Maybe you know more @Twixes.

2023-04-19 16:40 UTC, Twixes commented on frontend/__snapshots__/components-subscriptions--subscription-no-integrations.png
I take it you're referring to this snapshot @benjackwhite? In this case, this is actually more of a fix, because previously `LemonSelect` behaved differently from `LemonButton` or `LemonInput` in fitting content width while being a flex item. It now behaves in a more standard manner.

There _might_ be some case where the previous sizing looked better, but across the board this should be more predictable.

2023-04-24 12:12 UTC, benjackwhite commented on frontend/__snapshots__/components-subscriptions--subscription-no-integrations.png
To be clear - I was referring to the image snapshots. The Subscription modal's dropdown is no longer fullwidth

2023-04-24 12:40 UTC, benjackwhite approved these changes
Ignore me - my brain wasn't engaged fully and didn't realise that the diff is actually the desired improvement

2023-04-24 13:08 UTC, merged