feat(3000): Connect all navbar items to sidebar logics
PostHog/posthog pull request #15293
Opened 2023-04-28 11:24 UTC by Twixes

## Changes

This adds sidebars for all the remaining PostHog 3000 navbar items.

2023-05-24 13:47 UTC, Twixes commented on frontend/src/scenes/groups/groupsList.test.ts
This suite only tested things that shouldn't actually be the responsibility of the logic. It should be handled at the scene system level – which is the case now.

2023-05-25 10:15 UTC, Twixes commented on frontend/src/scenes/groups/groupsListLogic.ts
> +    key: (props: GroupsListLogicProps) => props.groupTypeIndex,
Previously there could only be one instance of `groupsListLogic` globally, so we couldn't load multiple group types at once. Now that this is keyed, we can

2023-05-25 13:54 UTC, thmsobrmlr requested changes
Switching between Cohorts and People & Groups leads to an unmounted logic issue
https://github.com/PostHog/posthog/assets/1851359/4d0208d9-ff7d-49a6-b443-1a97875a5740

2023-05-26 17:18 UTC, Twixes commented
Thanks for catching, that is resolved now!

2023-05-30 11:29 UTC, thmsobrmlr approved these changes
Looks good and soon we'll have the new navigation finished!

A couple of things I noticed (in order of what I think is more important):
- One thing I'd like to change is that the groups should be displayed by name and not by id, as "Hedgebox Inc." will mean more to the user than "01879987-a532-0000-967f-4503bf0fc283".
- Seems there is a small styling regression - see the frontend/__snapshots__/posthog-3000-sidebar--feature-flags.png snapshot.
- The persons endpoint is quite slow for me and I see the loading spinner every time I switch tabs - should probably have a more lightweight search and/or caching here.

2023-05-30 11:29 UTC, thmsobrmlr commented on frontend/src/layout/navigation-3000/navbarItems.tsx
> +            label: 'Analytics',
That name is way more understandable. We should also change the name throughout the rest of the UI at some point.

2023-05-30 14:39 UTC, Twixes commented
Very good points, added support for group names and fixed the styling issues. As for persons loading, it's a general performance issue I suppose.

2023-05-30 16:03 UTC, merged