feat(insights): funnel on sessions
PostHog/posthog pull request #15317
Opened 2023-05-02 10:11 UTC by mariusandra

## Problem

People would like to aggregate their funnels based on `properties.$session_id`

## Changes

Now they can, except for the bugs and missing tests:

![2023-05-02 12 10 43](https://user-images.githubusercontent.com/53387/235639749-820dea93-3512-4104-8dc1-b601eb691c59.gif)

## How did you test this code?

WIP

2023-05-03 09:45 UTC, thmsobrmlr requested changes
Nice! People have been asking for this a lot lately.

Some of the things should be based on the query for data exploration to work once we stop converting queries to filters. Funnels are already fully converted and thus work without it (but other visualizations are not, which is why we still have the conversion).

You can disable the conversion by commenting out [line 223 in insightVizDataLogic](https://github.com/PostHog/posthog/blob/b74dd435f83bfc3db77bccbc8c1d35f693dbffd4/frontend/src/scenes/insights/insightVizDataLogic.ts#L223).

Basically what this needs is:
- Implementing `canOpenPersonModal` in `funnelDataLogic` as well and using it in the data exploration variants
- Implementing the changes to `aggregationTargetLabel` in `funnelDataLogic` as well

The person modal isn't deactivated when clicking on the bar chart as well. I think this is because we replace the openPersonsModalForSeries with a no-op where we deactivate it right now. Should probably be based in `canOpenPersonModal` as well.

2023-05-03 09:45 UTC, thmsobrmlr commented on frontend/src/scenes/funnels/FunnelBarChart/FunnelBarChart.tsx
> +    const { canOpenPersonModal } = useValues(funnelLogic)
This should be implemented in `funnelDataLogic` and based on the query.

2023-05-04 15:14 UTC, mariusandra commented
This could use a re-review

2023-05-04 23:09 UTC, thmsobrmlr approved these changes
Works like a charm now.

2023-05-05 08:32 UTC, merged