fix(breakdown): gracefully handle histogram without values
PostHog/posthog pull request #15416
Opened 2023-05-05 21:11 UTC by thmsobrmlr

## Problem

The breakdown for a numeric property breaks when there are no values for the given event. Example: file_size_b for $pageview event in the demo data.

## Changes

This PR gracefully handles this case on the frontend and backend.

## How did you test this code?

Verified that the above mentioned case works

2023-05-08 12:47 UTC, Twixes reviewed
If there are no values, then I think I'd expect the breakdown series to not appear at all. A `null` bin seems just confusing.
On a different note, it would be very useful to have a backend test for this.

2023-05-08 12:47 UTC, Twixes requested changes
Gonna leave a changes request for the testing part.

2023-05-09 13:24 UTC, thmsobrmlr commented
I've added the requested test, which we should definitely have here.

For me having the empty breakdown appear is quite useful, as it can aid in debugging if there are issues with the insight configuration and it doesn't strike me as too strange.

Only missing properties:
<img width="1363" alt="Screenshot 2023-05-09 at 15 17 50" src="https://github.com/PostHog/posthog/assets/1851359/0fc4b4f4-0b99-4b2a-8c05-96c0b68c949f">

Mixed with present properties:
<img width="1368" alt="Screenshot 2023-05-09 at 15 17 37" src="https://github.com/PostHog/posthog/assets/1851359/f1c52f53-77b6-4ad2-b74b-d7838bf68169">

2023-05-09 14:34 UTC, Twixes approved these changes
Fair, if this is displayed in an understandable way then should be alright

2023-05-10 07:48 UTC, merged