feat(experiments): Bring funnel options to the experiment
PostHog/posthog pull request #16263
Opened 2023-06-27 14:17 UTC by neilkakkar

## Problem

This PR brings a few enhancements to experiments:

1. Moves participant selection and flag targeting type to the feature flag. As we add new features, keeping these in sync is a losing battle, so from now on, all changes for the flag will happen on the flag itself. This also helps cleanup lots of code in experiments.
<img width="783" alt="image" src="https://github.com/PostHog/posthog/assets/7115141/bf2b08a5-473b-4659-9256-e1dee21693e1">

2. Add funnel conversion window, aggregation type, test account filter, attribution type options
<img width="1240" alt="image" src="https://github.com/PostHog/posthog/assets/7115141/c623e0fa-651e-42c2-920a-b8c67a3b18aa">
3. Reconcile the same in the metric selector, so this selection happens only in one place
4. Disallow having global properties on experiments (which were used to create feature flags). 

This kind of funnel now works:

<img width="1042" alt="image" src="https://github.com/PostHog/posthog/assets/7115141/b57a1408-5c40-4854-9a2e-bc9e58d6a30f">

TODO: 

~~1. fix hogql aggregation update: it's not submitting / not changing the name of the aggregation label~~
~~3. Fix / write tests for hogql aggregation~~
4. Check with @thmsobrmlr whether the metric consolidation I've done is correct, and whether I can use a `querySource` in place of a `query` / `setQuery` pair. (P.s: Great work with building all the query compatible components, made adding these few new ones so seamless!)

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2023-06-28 08:23 UTC, neilkakkar commented
@thmsobrmlr I still have some hogql testing to do, but was hoping to get an early review from you on the queryNodes usage, and if this makes sense to you

2023-06-28 12:04 UTC, neilkakkar commented on ee/clickhouse/views/test/__snapshots__/test_clickhouse_experiments.ambr
> +                           pdi.person_id as person_id ,
@mariusandra the aggregation by hogql seems to unnecessarily query & join the pdi table in funnels.

2023-06-28 15:59 UTC, thmsobrmlr approved these changes
> 4. Check with @thmsobrmlr whether the metric consolidation I've done is correct, and whether I can use a querySource in place of a query / setQuery pair. (P.s: Great work with building all the query compatible components, made adding these few new ones so seamless!)

Cool to see more options for the funnel here! I've had a look at that part of the code an all seems great to me.

With regard to the insights filters - the broader plan is to create some "official" query components that either take `insightProps` or a `query / setQuery` pair and can then be reused in other parts of the app. 

Background is that I gradually want to get away from importing components from random parts of the app. The components then would be marked as official e.g. by including them in a Storybook section and importing other components would be discouraged.

Just meant as an FYI and components used here would be good candidates for this.

2023-06-29 01:13 UTC, liyiy commented
1. Nice work including the extra funnel options

2. I like that we're consolidating the person properties rollout to the feature flag! It'll give users a lot more flexibility if they don't want a 50/50 experiment for example, etc. 

It would be really nice though if you could just edit the flag directly in the experiment so you'd have context the entire time. That's probably a bit of work so in the meantime I'd recommend at least a simpler explanation on redirecting users to the feature flag, something like:
 
`Experiments use feature flags to select participants. For more advanced options like changing rollout percentages or targeting specific users, update the <name> feature flag for it.` (shorter is even better)

3. Below is an experiment I created and I edited the feature flag conditions for it. However the flag conditions displayed on the experiment shows `100% of users` which isn't super helpful/accurate and it'd also be nice to have the feature flag linked to it.

<img width="854" alt="Screen Shot 2023-06-28 at 9 06 58 PM" src="https://github.com/PostHog/posthog/assets/25164963/47a7d0d2-8047-490e-82d3-18f246323b9f">


4. To keep it consistent with the other Feature Success features, let's do a `Save as draft` instead of the initial `Save`
<img width="858" alt="Screen Shot 2023-06-28 at 9 11 11 PM" src="https://github.com/PostHog/posthog/assets/25164963/58f3e4e8-0f71-49e8-ab1d-4e2ad24be512">

2023-06-29 01:14 UTC, liyiy requested changes, later dismissed
1. Nice work including the extra funnel options

2. I like that we're consolidating the person properties rollout to the feature flag! It'll give users a lot more flexibility if they don't want a 50/50 experiment for example, etc. 

It would be really nice though if you could just edit the flag directly in the experiment so you'd have context the entire time. That's probably a bit of work so in the meantime I'd recommend at least a simpler explanation on redirecting users to the feature flag, something like:
 
`Experiments use feature flags to select participants. For more advanced options like changing rollout percentages or targeting specific users, update the <name> feature flag for it.` (shorter is even better)

3. Below is an experiment I created and I edited the feature flag conditions for it. However the flag conditions displayed on the experiment shows `100% of users` which isn't super helpful/accurate and it'd also be nice to have the feature flag linked to it.

<img width="854" alt="Screen Shot 2023-06-28 at 9 06 58 PM" src="https://github.com/PostHog/posthog/assets/25164963/47a7d0d2-8047-490e-82d3-18f246323b9f">


4. To keep it consistent with the other Feature Success features, let's do a `Save as draft` instead of the initial `Save`
<img width="858" alt="Screen Shot 2023-06-28 at 9 11 11 PM" src="https://github.com/PostHog/posthog/assets/25164963/58f3e4e8-0f71-49e8-ab1d-4e2ad24be512">

2023-06-29 08:53 UTC, neilkakkar commented
For (2): the link is generated once you save the experiment, because the flag is created only on save.

Will update the text to make this clearer.

The others are issues that existed before this PR, so will fix in a follow up :)

2023-06-29 09:04 UTC, neilkakkar commented
Actually, will fix participants in this PR too, since that confusion will excaberate with this change

2023-06-29 10:35 UTC, neilkakkar commented
It now accurately gets participants info from the flag:

<img width="587" alt="image" src="https://github.com/PostHog/posthog/assets/7115141/289a8df1-0ed8-4e84-9376-e1a78709b86c">

and defers to flag when too many groups:

<img width="617" alt="image" src="https://github.com/PostHog/posthog/assets/7115141/7fe37f6e-03a9-4552-8ad1-6a60bd3b86ad">




Also fixed the same on the feature flag list table

2023-06-29 10:35 UTC, neilkakkar commented
Also added some backwards compatibility so existing experiments in draft mode aren't borked

2023-06-29 15:01 UTC, liyiy approved these changes

2023-06-29 16:11 UTC, merged