feat: notebook timestamp nodes
PostHog/posthog pull request #16613
Opened 2023-07-17 18:03 UTC by daibhin

## Problem

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2023-07-18 14:11 UTC, daibhin commented
Conscious that notebooks don't have a lot of tests in them. Would love to pair with someone if there is a way to start adding them in this PR

2023-07-19 11:15 UTC, benjackwhite requested changes

2023-07-19 11:15 UTC, benjackwhite commented on frontend/src/scenes/notebooks/Nodes/NotebookNodeTimestamp.tsx
> +        </NodeViewWrapper>
Maybe more specific? `NotebookRecordingTimestamp` or something.

Timestamp feels to generic and could end up clashing with something else I would imagine...

2023-07-19 11:15 UTC, benjackwhite commented on frontend/src/scenes/notebooks/Nodes/NotebookNodeTimestamp.tsx
> +    name: NotebookNodeType.Timestamp,
Same here - maybe `ReplayTimestamp` so its super clear what it is for?

2023-07-19 11:15 UTC, benjackwhite commented on frontend/src/scenes/notebooks/Nodes/NotebookNodeTimestamp.tsx
> +
This is a great solution. 
We could after follow up with hover and click handlers to call the related logic and set some styles to indicate that it is related to the timestamp in question...

2023-07-19 11:15 UTC, benjackwhite commented on frontend/src/scenes/notebooks/Notebook/Editor.tsx
> +                            attributes: { notebookShortId: { default: notebookId } },
Hmmmm not sure that I love this... Could we not just use the notebookLogic instead? Every node is mounted within a notebookLogic so you should be able to easily grab the currently mounted notebookLogic and pull out the Id from that?

If I've missed something we can look at it together

2023-07-19 14:40 UTC, benjackwhite commented
@daibhin resolved the comments that were sorted from our pairing. Just some small follow up stuff left 👍

2023-07-20 09:21 UTC, benjackwhite approved these changes
Very nice!

2023-07-20 12:12 UTC, merged