chore(ingestion): add 'backend' to anon IDs
PostHog/posthog pull request #16720
Opened 2023-07-21 14:11 UTC by xvello

## Problem

Messages sent with `distinct_id:backend` should not benefit from our locality guarantees, to avoid overwhelming a single partition 

## Changes

- Add to capture's `LIKELY_ANONYMOUS_IDS` to remove the locality constraint
- Add to `CASE_INSENSITIVE_ILLEGAL_IDS` to forbid merges to that ID

## How did you test this code?

2023-07-21 14:12 UTC, tomasfarias approved these changes

2023-07-24 14:09 UTC, tomasfarias approved these changes
Great work with the early return, just made a question regarding historical data tokens.

2023-07-24 14:23 UTC, xvello commented
- The historical queue allows customers to backfill aggressively, while we control pressure on the data stores by scaling up/down the dedicated ingestion deploy
- This is why the overflow mechanism is disabled for this topic, to make sure props and merges are processed in the proper order
- I think we'll want to have some overflow/limit mechanism, with a higher threshold than the real-time use case
- My goal here is to protect ourselves against an obviously egregious case, then circle back with Tiina next week

2023-08-01 08:10 UTC, xvello commented
Heya @tiina303 could you please review this?

2023-08-01 12:55 UTC, tiina303 requested changes
We discussed this briefly yesterday. Given this is historical backfill (i.e. users can redo it). I'd say we should drop bad events in the historical backfill inside the ingestion pod (giving us better control rather than at capture) and send an ingestion warning.

2023-08-17 07:31 UTC, closed without merging