fix: Freeze 'Series column' on detailed results table (11800)
PostHog/posthog pull request #16758
Opened 2023-07-25 17:47 UTC by Arun-chaitanya

## Problem
Freeze 'Series column' on detailed results table (#11800)

## Changes
Added sticky feature to the table and enabled sticky prop for series column

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2023-07-28 14:12 UTC, Twixes requested changes
This is very cool! There is just one major issue: stickiness is wonky if more than one column is sticky, see below. 
![2023-07-28 15 58 32](https://github.com/PostHog/posthog/assets/4550621/ed31c441-cfad-494b-9585-60e98724b6f1)
The checkbox and series name should be sticky _together_. In this case this can be fixed easily by combining those two columns – there are no column alignment considerations because checkboxes are always the same width. However, the API should not allow this situation. I think it may be better to do things this way: remove `sticky` param from columns, and instead add a `LemonTable` prop called `firstColumnSticky`.

Also, it would be worth having a border-right on the sticky column when scrolled, to make the stickiness clear interface-wise.

2023-07-28 14:16 UTC, Twixes commented
(Also, merge your branch with PostHog/posthog master, as we've fixed an issue with checks failing on external PRs)

2023-07-28 14:25 UTC, Arun-chaitanya commented on frontend/src/lib/lemon-ui/LemonTable/LemonTable.scss
> +.LemonTable__td--sticky {
Sure. Will do the required changes and keep the conversation going.

2023-07-29 12:04 UTC, Arun-chaitanya commented
@Twixes, I made all the changes as recommended. Please check.

2023-07-29 12:30 UTC, Arun-chaitanya commented
I messed up with this PR, so closing this and opening a PR (https://github.com/PostHog/posthog/pull/16825). @Twixes I did all the changes recommended by you in that PR.

2023-07-29 12:31 UTC, closed without merging