feat(data-warehouse): extend person definition backend
PostHog/posthog pull request #16877
Opened 2023-08-01 20:12 UTC by EDsCODE

## Problem

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2023-08-15 18:09 UTC, EDsCODE commented on posthog/warehouse/models/view_link.py
> +class DataWarehouseViewLink(CreatedMetaFields, UUIDModel, DeletedMetaFields):
Data model seems a bit flimsy as it's a bunch of string matching (as opposed to having an Enum of possible tables/fields)

2023-08-17 12:08 UTC, Twixes requested changes
A few small rough edges, and a safety concern

2023-08-17 12:08 UTC, Twixes commented on posthog/hogql/database/database.py
> +        )
Nit: These can be just provided to the `ast.JoinExpr()` constructor, same as `table`

2023-08-17 12:08 UTC, Twixes commented on posthog/hogql/database/database.py
> +def determine_join_function(view):
Given this is so tightly coupled with the `view`, might be better as a
```python
@property
def join_function
```
on `DataWarehouseViewLink`?

2023-08-17 15:49 UTC, EDsCODE commented on posthog/warehouse/query.py
No idea, it was there for a while for no reason so I'm deleting it

2023-08-17 15:49 UTC, EDsCODE commented on posthog/hogql/database/models.py
> +        return self.name
done

2023-08-17 19:34 UTC, EDsCODE commented on posthog/hogql/database/database.py
> +        table = database.get_table(view.table)
Added logic/update data model to be able to cascade deletion of s3table to all related views. Will account for this in UI so it doesn't seem buggy

2023-08-21 13:02 UTC, Twixes approved these changes
LGTM!

2023-08-21 13:02 UTC, Twixes commented on posthog/warehouse/models/datawarehouse_saved_query.py
> +        from posthog.models.property.util import S3TableVisitor
Do _all_ of these need to be imported here? A bit suspicious

2023-08-24 09:26 UTC, mariusandra approved these changes
Generally looking good! Some comments below, but non blocking:

- If I just see a "save as view" button, I don't know what that does. Perhaps a "(i)" next to it with a tooltip explaining what's what?
- The error discards the unsaved state:
![2023-08-24 11 14 22](https://github.com/PostHog/posthog/assets/53387/9f18ac43-0b2b-49a4-8136-40394ee3451b)
- We could add an alias automatically for simple field/property access

2023-08-28 17:45 UTC, EDsCODE commented
@mariusandra Added comments to https://github.com/PostHog/posthog/pull/16993 to address UI issues together

2023-08-28 18:17 UTC, EDsCODE commented
Will let this test run again but should be irrelevant. Looks like a cache failure. Also, this PR has near 0 impact on UI

2023-08-28 18:26 UTC, merged