Ingestion third party swap redshift for rss
PostHog/posthog pull request #17306
Opened 2023-09-04 16:54 UTC by tiina303

## Problem

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2023-09-05 21:12 UTC, raquelmsmith requested changes
Oof, the existing ingestion logic is a beast, nice work picking through it.

This view will be going away hopefully soon but good to know about this new one, and it's good to update here until the new onboarding is released.

A few comments 👍

2023-09-05 21:12 UTC, raquelmsmith commented on frontend/src/scenes/ingestion/panels/ThirdPartyPanel.tsx
> +                <h1 className="ingestion-title pb-4">Set up third party integrations</h1>
```suggestion
                <h1 className="ingestion-title pb-4">Set up third-party integrations</h1>
```

2023-09-06 11:57 UTC, tiina303 commented
> This view will be going away hopefully soon

I assume we'll still keep the third-party option next to other libraries in some way, no?

2023-09-06 12:06 UTC, tiina303 commented on frontend/src/scenes/ingestion/panels/ThirdPartyIcons.tsx
> +            <rect x="0" y="0" fill="#F78422" width="455.731" height="455.731" />
I don't know how to do this nor where I'm actually supposed to get these icons?

2023-09-06 12:09 UTC, tiina303 commented on frontend/src/scenes/ingestion/panels/ThirdPartyPanel.tsx
> +            {thirdPartyIntegrationSource?.name && (
I didn't change this part, seems like the value could be null otherwise

2023-09-06 12:11 UTC, tiina303 commented on frontend/src/scenes/ingestion/panels/ThirdPartyPanel.tsx
> +                                onClick={() => window.open(`https://${thirdPartyIntegrationSource.name}.com`)}
I'm with you on that, didn't change that part 😅

2023-09-06 16:46 UTC, raquelmsmith approved these changes

2023-09-06 18:03 UTC, merged