feat: Save $last_ as well as $initial_
PostHog/posthog pull request #17393
Opened 2023-09-12 13:17 UTC by benjackwhite

## Problem

The `$last_X` is also useful for a lot of people, so this adds it as well as adding some missing app based properties

## Changes

* As it says.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2023-09-12 15:00 UTC, tiina303 approved these changes
I'd be consistent with both params (i.e. make campaignParams also do `$last_`, can't think of a reason why these would be different & as a user I'd find that confusing.

Otherwise this seems good, but we might need to do a few things before we can ship it:
1. make sure we don't break folks's existing insights <- they might be using browser etc
2. maybe some user communication that Joe/marketing can help us with 🤷‍♀️

2023-09-12 15:01 UTC, tiina303 requested changes
meant to comment

2023-09-12 15:02 UTC, benjackwhite commented
> I'd be consistent with both params (i.e. make campaignParams also do `$last_`, can't think of a reason why these would be different & as a user I'd find that confusing.
> 
> 
> 
> Otherwise this seems good, but we might need to do a few things before we can ship it:
> 
> 1. make sure we don't break folks's existing insights <- they might be using browser etc (I think there's a way to query that ... Tim did it for something else similar)
> 
> 2. maybe some user communication that Joe/marketing can help us with 🤷‍♀️ 

Regarding 1 - this change doesn't break that. It has been broken a long time so I don't think we need to be concerned about it. 

2 makes sense if we rename the campaign params but couldn't we do that _after_ ?

2023-09-13 07:33 UTC, pauldambra approved these changes
looks good to me

> maybe some user communication that Joe/marketing can help us with 🤷‍♀️

As it is I think the changelog is a good place for something additive like this... 

I think we could add $last_blah for campaign params rather than renaming and breaking things or needing to migrate them... but then you'd have both which is arguably more confusing for a user.

As a compromise you could not add the $last_ to things here so that the $initial_ is the only qualifier but I don't have strong feelings on what's better there

2023-09-13 15:19 UTC, tiina303 commented
No-one has time to revisit things at PostHog & migrating/user communication several times is extremely annoying, so why don't we just make the change and add it to the release notes like we want to have it in the future.
By make the change I mean: event properties that we add to the person will be in the format of `$initial_` & `$last_` for all of the properties the same way.

2023-09-13 15:30 UTC, tiina303 commented
https://github.com/PostHog/posthog/blob/bee0b07c41914ed43d006816620b8284084ab9ac/frontend/src/lib/taxonomy.tsx#L63 or somewhere we need to update too for them to show up nicely 🤷‍♀️

2023-09-14 10:56 UTC, tiina303 approved these changes
🙇‍♀️  Thanks for making the code more readable too :)

2023-09-14 10:57 UTC, merged