feat: deprecate ClickHouse recordings ingestion
PostHog/posthog pull request #17464
Opened 2023-09-15 10:39 UTC by pauldambra

We want to stop ingesting recordings into ClickHouse.

This has three components

1) doing this for PostHog cloud
2) doing this in tests/debug
3) doing this for self-hosted

As a first step we add an environment variable `SESSION_RECORDING_ALLOW_V1_INGESTION` which both the plugin server and django app read as config.

When it is true we:
* warn in the console
* start recordings ingestion capability 
* ingest to the `session_recordings_events` topic as well as the `session_recording_snapshot_items_events` topic

When it is false we:
* do not start the recordings ingestion capability
* drop events that would otherwise be ingested to the `session_recordings_events`

This would let us set the environment variable for cloud whenever we want as it wouldn't change behavior for us but would stop us writing to a topic we ignore

But would also give us a stepping stone to deprecating self hosted. 

This version warns
A future version is the final image that supports ClickHouse ingestion
And any self-hosted deployment that needed to continue that ingestion would have to pin to that docker image tag

That gives us a line in the sand after which we can tidy up our code

2023-09-15 10:47 UTC, benjackwhite requested changes
I think there is literally one line that is not correct. Otherwise looks good

2023-09-15 10:47 UTC, benjackwhite commented on posthog/api/capture.py
>                  processed_replay_events = legacy_preprocess_session_recording_events_for_clickhouse(replay_events)
I think we need to do something about the line above as this change simply doesn't preprocess...

2023-09-15 10:47 UTC, benjackwhite commented on posthog/api/capture.py
>              processed_replay_events = replay_events
this is the line i mean

2023-09-21 13:24 UTC, pauldambra commented
gonna nuke this and pick it up in https://github.com/PostHog/posthog/pull/17572

2023-09-21 13:24 UTC, closed without merging