fix: remove content width toggle from popover
PostHog/posthog pull request #17775
Opened 2023-10-04 15:05 UTC by daibhin

## Problem

Toggle does nothing in the popover

## Changes

Remove the toggle

## How did you test this code?

Toggle is gone

2023-10-05 07:05 UTC, benjackwhite commented
Does it do nothing? It still toggles, and if you open the notebook in full screen it still makes a difference 🤔  
Maybe we just want to hide it when the sidebar isn't big enough (i.e. not full screen or even better based on its content size?

2023-10-05 13:41 UTC, benjackwhite requested changes

2023-10-09 10:13 UTC, daibhin commented on frontend/src/scenes/notebooks/Notebook/NotebookPopover.tsx
> +    const contentWidthHasEffect = useMemo(() => fullScreen && width && width > 866, [fullScreen, width])
Ah brilliant, I was looking for something similar but didn't come across that

2023-10-09 11:36 UTC, benjackwhite approved these changes
Apart from the dangling import 👍

2023-10-09 12:22 UTC, merged