feat(storybook): add theme toggle to storybook
PostHog/posthog pull request #18123
Opened 2023-10-20 20:24 UTC by thmsobrmlr

## Problem

We want to test components in all theme variants with storybook.

## Changes

This PR adds a theme toggle via Storybook globals to Storybook. The toggle code is not super clean (also doesn't use `themeLogic` and set the theme by updating the theme property on `body` accordingly), but seams to work in most cases.

![2023-10-20 22 23 13](https://github.com/PostHog/posthog/assets/1851359/bc6fc9bf-b457-43d2-952b-924a6ad9a75c)

## How did you test this code?

Ran Storybook locally

2023-10-23 07:41 UTC, benjackwhite approved these changes
This is super cool. Clicked around locally and everything seemed to work as expected

2023-10-23 07:41 UTC, benjackwhite commented on frontend/__snapshots__/posthog-3000-navigation--navigation.png
I guess this needs to be changed (or removed) as we now do this via the theme picker?

2023-10-23 10:38 UTC, Twixes commented on frontend/__snapshots__/posthog-3000-navigation--navigation.png
Yeah, I think for the purpose of snapshots we still need the decorator.

BTW looks like the now-unused dark mode and light mode snapshots weren't deleted, we might want to do some pruning of unused snapshots at some point. 🤔

2023-10-23 11:01 UTC, thmsobrmlr commented on frontend/__snapshots__/posthog-3000-navigation--navigation.png
Yep, I'd like to address this by adding an option to `testOptions` where you can specify wether "legacy", "3000" or "all" themes should be captured.

I was hoping Storybook would provide a way to set globals for a specific story, so that we could override the theme there, but that doesn't seem to be the case.

2023-10-24 14:43 UTC, Twixes requested changes, later dismissed
This is great, but we do need to keep the 3000 navigation stories, since the story we have now just shows the classic navigation

2023-10-25 15:08 UTC, thmsobrmlr commented
> This is great, but we do need to keep the 3000 navigation stories, since the story we have now just shows the classic navigation

I'm forcing these stories to use the feature flag now (see [visual regression tests](https://github.com/PostHog/posthog/pull/18123/commits/35d64647c9c7f8597ef52aa7db7e4491747912fa)). Also I've added one for the "base 3000 nav".

2023-10-26 11:27 UTC, merged