fix: restructure button styles to allow secondary to be transparent
PostHog/posthog pull request #18949
Opened 2023-11-29 11:21 UTC by daibhin

## Problem

Follow on from work in https://github.com/PostHog/posthog/pull/18930

## Changes
- 

TODO
- Destructive colors (light / dark mode)

## How did you test this code?

Snapshots

2023-11-29 11:58 UTC, daibhin commented on frontend/__snapshots__/lemon-ui-lemon-button--types-3000.png
This snapshot can be ignored - it is really only relevant in the 3000 variations

2023-11-29 15:33 UTC, corywatilo requested changes
Some regressions below.

(left: prod, right: this branch)

- [x] Lost hover effect (`top: -1px`)

    ![2023-11-29 10 27 18](https://github.com/PostHog/posthog/assets/154479/89866f5f-852b-4975-923a-98a3f42198c2)

    ![2023-11-29 10 28 01](https://github.com/PostHog/posthog/assets/154479/725278a8-15e2-409d-94f2-06d7af5ede5c)

- [ ] Button paddings are off

    <img width="518" alt="image" src="https://github.com/PostHog/posthog/assets/154479/0e9120dd-5504-4512-afda-dd6ec7a736b3">

    <img width="486" alt="image" src="https://github.com/PostHog/posthog/assets/154479/a6e89e2b-43ee-44e1-84af-9affc95db323">

    <img width="596" alt="image" src="https://github.com/PostHog/posthog/assets/154479/08ca75ae-8da1-4c58-9105-70616bef9050">


- [ ] Tab buttons broken

    <img width="511" alt="image" src="https://github.com/PostHog/posthog/assets/154479/94fbda3e-988a-4003-aeeb-ae4b35f52cc9">

- [ ] Button colors are different

    <img width="472" alt="image" src="https://github.com/PostHog/posthog/assets/154479/529e8681-6885-49d5-9857-eb20771a70b7">

    <img width="859" alt="image" src="https://github.com/PostHog/posthog/assets/154479/771bcf8c-3a6a-4820-84f3-f3f9bdbcbc03">

- [ ] Button background is off a bit - maybe somewhere in the middle would be best

    <img width="909" alt="image" src="https://github.com/PostHog/posthog/assets/154479/6a52d850-b101-484e-8dd0-8a04960b6754">

2023-11-29 20:15 UTC, corywatilo commented
- [ ] Distance between top layer and bottom layer feels about 1px too separated, and definitely too far apart on hover. Maybe 1px less for both? (Currently the distance between `:hover` and `:active` feels too far, so nudging the `default` and `hover` states down 1px should fix this.)

    ![2023-11-29 15 05 44](https://github.com/PostHog/posthog/assets/154479/bed4d5ca-ca5f-4eb5-8294-7759c94a61ba)

- [ ] Need 1px of vertical space between each nav button (so they don't touch)

    ![2023-11-29 15 05 57](https://github.com/PostHog/posthog/assets/154479/b3520a9a-c53f-43a1-a975-871b2842d78a)

- [ ] Spacing weirdness when "On dashboard" is used

    <img width="506" alt="image" src="https://github.com/PostHog/posthog/assets/154479/0945597f-82b1-43d3-ac61-8edce107fce4">

- [ ] Can we darken icons on hover?

    ![2023-11-29 15 11 19](https://github.com/PostHog/posthog/assets/154479/b22b8027-d347-40c7-87b9-7299f4562a8b)

- [ ] Sizing/state

    ![2023-11-29 15 12 13](https://github.com/PostHog/posthog/assets/154479/ee5c7ba4-56a6-4b77-9e82-c78de0fca2fc)

- [ ] Any reason we're not using stealth (or whatever we're calling the buttons where chrome only shows on hover) here? (And in lots of other places)

    ![2023-11-29 15 12 51](https://github.com/PostHog/posthog/assets/154479/45a2fae4-5ffa-4a3d-8add-d75a5bd67b00)

- [ ] Top of one button gets clipped in WA

    ![2023-11-29 15 13 48](https://github.com/PostHog/posthog/assets/154479/1bbafe28-4fdc-4cd9-b107-806f7d0bb77d)

- [ ] Should we just use the tab bar buttons here while we're at it?

    <img width="368" alt="image" src="https://github.com/PostHog/posthog/assets/154479/bf495723-cd33-4b99-a469-00694895693e">

2023-11-30 17:04 UTC, daibhin commented on frontend/__snapshots__/lemon-ui-lemon-button--default--dark.png
Expected that tertiary buttons get slightly taller in 3000 (from 33px to 37px). This is because of the new button structure and fixes the issue where a tertiary button next to a 3D button would also be smaller (because it doesn't have the frame border basically)

2023-11-30 17:23 UTC, daibhin commented
@corywatilo got through your latest round of feedback. I left the last three items because they are existing issues and this PR is solely focused on replacing the button styles with a new structure to make them easier to customize. Will for up with fixes for each of them individually once this is in

2023-11-30 23:46 UTC, corywatilo commented
## Final round

- [ ] Non-active tab bar buttons feel disabled. Maybe slightly higher opacity on text?

    <img width="431" alt="image" src="https://github.com/PostHog/posthog/assets/154479/777487df-a705-4459-8525-3af7e7e02dcc">

- [ ] When buttons are on top of the accent color, the button border feels low on contrast. Not sure what the easy fix is here though...

    <img width="312" alt="image" src="https://github.com/PostHog/posthog/assets/154479/beb8c4de-a4e8-4da8-a3aa-234d41f7f303">

- [ ] Right padding on these normal sized buttons feels a little large

    <img width="414" alt="image" src="https://github.com/PostHog/posthog/assets/154479/0d88fd8e-3b82-4158-92fd-ce2a87ae4304">

    <img width="616" alt="image" src="https://github.com/PostHog/posthog/assets/154479/740910ef-3d0d-406e-8cfe-f14cec8fe8db">

- [ ] Is the _Add criteria_ button supposed to be full width? (I'd vote no if I had the option. [As seen in](http://localhost:8000/cohorts/2))

    <img width="1067" alt="image" src="https://github.com/PostHog/posthog/assets/154479/7c56ca52-2c64-4bfc-8fd8-da471ab503d0">

- [ ] Overflow/button type issue (This is a dropdown, should have a chevron)

    <img width="544" alt="image" src="https://github.com/PostHog/posthog/assets/154479/6ee7acdf-b70f-4876-b124-750f739b4868">

- [ ] Feels like this should be indicated as a dropdown too?

    ![2023-11-30 18 46 15](https://github.com/PostHog/posthog/assets/154479/b0c1aa5a-1106-46a5-b899-8f9293b2d8b4)

2023-12-01 13:07 UTC, Twixes reviewed
Found a couple of small things to fix, and one Q for Cory

2023-12-01 14:26 UTC, daibhin commented on frontend/__snapshots__/posthog-3000-navigation--navigation-3000.png
Fixed in https://github.com/PostHog/posthog/pull/18949/commits/47330c55cd9bef3f785ae41bc7d08b2483add6ab

2023-12-01 17:49 UTC, daibhin commented on frontend/__snapshots__/scenes-app-sidepanels--side-panel-settings.png
Implemented the shadow rotation on the secondary buttons

2023-12-01 18:09 UTC, Twixes approved these changes

2023-12-01 18:25 UTC, corywatilo approved these changes

2023-12-04 10:24 UTC, merged

2023-12-04 12:02 UTC, daibhin commented
> - [x] Any reason we're not using stealth (or whatever we're calling the buttons where chrome only shows on hover) here? (And in lots of other places)
![2023-11-29 15 12 51](https://github.com/PostHog/posthog/assets/154479/45a2fae4-5ffa-4a3d-8add-d75a5bd67b00)

Because those were implemented as tertiary buttons and would need to manually be updated to a different button style. Will leave that down to the individual teams to do depending on their own preferences / use cases once 3000 launches


> - [ ] Top of one button gets clipped in WA
![2023-11-29 15 13 48](https://github.com/PostHog/posthog/assets/154479/1bbafe28-4fdc-4cd9-b107-806f7d0bb77d)

Chatted through this on a standup call. This was the regression we are willing to accept to get the 3D button moving up on hover. Will look into this specific use case to see if it can be fixed. Would require removing the `overflow: hidden` on the surrounding parent

> - [ ] Should we just use the tab bar buttons here while we're at it?
<img width="368" alt="image" src="https://github.com/PostHog/posthog/assets/154479/bf495723-cd33-4b99-a469-00694895693e">

Migrated in https://github.com/PostHog/posthog/pull/19041

2023-12-06 09:18 UTC, daibhin commented
Final button spacing issues fixed in https://github.com/PostHog/posthog/pull/19046