chore: drop kafka_skip_broken_messages from kafka_events_json
PostHog/posthog pull request #18970
Opened 2023-11-29 19:21 UTC by bretthoerner

## Problem

We _shouldn't_ be sending any messages that don't deserialize properly, and so we'd like to go back to `kafka_skip_broken_messages = 0` in prod.

## Changes

Remake virtual Kafka table (and MV that's based on it) without the `kafka_skip_broken_messages` setting.

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2023-11-29 19:22 UTC, bretthoerner commented
@fuziontech I'm not sure if I missed a tool to create these, I created the migration manually. I assume our migration script checks for the migration by name.

Speaking of which, there are two `0049` migrations here: https://github.com/PostHog/posthog/tree/master/posthog/clickhouse/migrations

2023-11-30 15:57 UTC, tiina303 approved these changes
lgtm

2023-12-04 15:48 UTC, bretthoerner commented
Ping @fuziontech - looks like I need your approval.

2023-12-05 22:49 UTC, fuziontech approved these changes
lgtm! sorry for lag
🚢 it!

2023-12-05 22:53 UTC, fuziontech commented
> @fuziontech I'm not sure if I missed a tool to create these, I created the migration manually. I assume our migration script checks for the migration by name.

No tool to make these, just manually. Checks for i+1 where i is the current migration id.

> Speaking of which, there are two 0049 migrations here. I hope that's OK/known?: https://github.com/PostHog/posthog/tree/master/posthog/clickhouse/migrations

oh, interesting. I would probably increment this to `0051` and bump the last migration to `0050`

2023-12-05 22:54 UTC, fuziontech requested changes
Could you bump the last `0049` migration to be `0050` and then make this `0051` for consistency?

2023-12-05 22:55 UTC, fuziontech commented
Actually. Give me a second to put a PR to correct this. One of those migrations needs to be removed. One sec.

2023-12-05 23:02 UTC, fuziontech commented
Once this lands, let's rebase this one and 🚢 it
https://github.com/PostHog/posthog/pull/19110

2023-12-06 00:27 UTC, bretthoerner commented
Rebased 🤞

2023-12-06 01:07 UTC, bretthoerner commented
Looks good, just needs your stamp @fuziontech

2023-12-06 01:11 UTC, fuziontech approved these changes
just kept rolling for all green tests.
Ship it!

2023-12-06 17:03 UTC, bretthoerner commented
Actually going to close this in favor of the upcoming `_error` virtual columns.

This migration will allow bad messages to kill ingestion, where as the `_error` columns can be forwarded and stored in a table for us to analyze (without killing ingestion).

2023-12-06 17:03 UTC, closed without merging