fix(3000): use page background for replay canvas
PostHog/posthog pull request #19394
Opened 2023-12-18 14:23 UTC by thmsobrmlr

## Problem

See https://posthog.slack.com/archives/C04L2CV12V9/p1702667892126749.

## Changes

This PR changes the replay background to the page background in both dark **and** light mode.

<img width="902" alt="Screenshot 2023-12-18 at 15 22 44" src="https://github.com/PostHog/posthog/assets/1851359/e40e3854-4de5-4829-85bb-85b3506f813f">
<img width="908" alt="Screenshot 2023-12-18 at 15 22 31" src="https://github.com/PostHog/posthog/assets/1851359/459080b0-9f04-4ef4-aca3-00eb6fd94e70">

## How did you test this code?

👀

2023-12-18 15:44 UTC, daibhin approved these changes

2023-12-18 16:22 UTC, benjackwhite requested changes
Nope! This is super unusable for many people. We had feedback about it which is why I changed to always be black

2023-12-18 17:11 UTC, thmsobrmlr commented
Got it, didn't know people were having issues with it. I've re-done the changes so that there is just the usual 3000 background, always in dark. How does that look @benjackwhite? Or would you prefer it staying as it is?

<img width="969" alt="Screenshot 2023-12-18 at 18 11 09" src="https://github.com/PostHog/posthog/assets/1851359/6232bce4-e8ae-40cc-b925-deff82e0dbeb">

2023-12-19 09:31 UTC, benjackwhite approved these changes
Yep - no strong feelings about which black - as long as it is black 😊

2023-12-19 09:33 UTC, merged