feat: Add cta on billing for >20k annual spend customers
PostHog/posthog pull request #19508
Opened 2023-12-22 18:44 UTC by xrdt

## Problem

Updates the existing >$1k monthly spend alert to include more perks we can offer to large customers. 

## Changes

No CTA: 
<img width="1273" alt="Screenshot 2023-12-22 at 10 41 54 AM" src="https://github.com/PostHog/posthog/assets/21014901/5bf2438a-dff1-4d9a-9981-50089f5b2f6a">

With CTA: 
<img width="1332" alt="Screenshot 2023-12-22 at 10 42 46 AM" src="https://github.com/PostHog/posthog/assets/21014901/108f156c-4d17-4b6c-974f-1cfa8f4eff2c">

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2023-12-22 18:45 UTC, xrdt commented on frontend/src/scenes/billing/Billing.tsx
> +                            <div style={{ alignSelf: 'start', paddingTop: '8px' }}>
Need to fix this lint issue with styling the lemonbutton.
Also see line 284

2023-12-22 18:45 UTC, xrdt commented on frontend/src/scenes/billing/Billing.tsx
> +                                    Get in touch!
We can collapse this once they click the button. Need to think about collapsed state.

2023-12-22 18:47 UTC, xrdt commented on frontend/src/scenes/billing/Billing.tsx
> +                                    Get in touch!
Is it better to have an explicit dismiss button? Either something that appears on hover of the hog, say, or a x in the upper right that appears on hover?

2023-12-22 18:47 UTC, xrdt commented on frontend/src/scenes/billing/Billing.tsx
> +                                    Get in touch!
Or a dismiss button next to the Get in touch <<< this is probably the simplest.

2024-01-02 17:15 UTC, raquelmsmith commented
IMO this doesn't need to be dismissable, it can just be a persistent "ad"

2024-01-02 21:07 UTC, xrdt commented
Newer screenshot 
<img width="1279" alt="Screenshot 2024-01-02 at 1 07 27 PM" src="https://github.com/PostHog/posthog/assets/21014901/e4b09b95-9087-4fb9-b507-348ed15673a6">

2024-01-02 22:45 UTC, xrdt commented
Re dismissability: Can hide the CTA once they've converted to an annual plan.

2024-01-03 00:46 UTC, raquelmsmith commented
Changed how it looks a bit:

![image](https://github.com/PostHog/posthog/assets/18598166/f6642eb6-723c-434a-83b7-8f73580fd0a0)

There's kind of an awkward gap above the "Products" header but cory wants to redo this page anyway so I think it's fine.

2024-01-03 00:55 UTC, raquelmsmith requested changes
Just removing the dismiss code and the extra hog!

2024-01-03 00:55 UTC, raquelmsmith commented on frontend/public/hedgehog/builder-hog-waving-smiling.png
do we need this?

2024-01-03 00:55 UTC, raquelmsmith commented on frontend/src/scenes/billing/billingLogic.ts
> +        setPerksCTADismissed: (perksCTADismissed: boolean) => ({ perksCTADismissed }),
I don't think we need this action, can just keep it there until they sign up for annual.

2024-01-03 00:55 UTC, raquelmsmith commented on frontend/public/hedgehog/builder-hog-waving-smiling.png
Do we need this file?

2024-01-03 00:55 UTC, raquelmsmith commented on frontend/src/lib/components/hedgehogs.tsx
> +}
Do we not already have this one in there? Prob remove since not using it anyway.

2024-01-03 18:03 UTC, raquelmsmith requested changes
dark mode!

2024-01-03 18:03 UTC, raquelmsmith commented on frontend/__snapshots__/scenes-other-billing-v2--billing-v-2-with-discount--dark.png
👀 doesn't look very good in dark mode, worth a quick color pass

2024-01-03 21:55 UTC, xrdt commented on frontend/__snapshots__/scenes-other-billing-v2--billing-v-2-with-discount--dark.png
Good catch, thanks.

2024-01-03 22:06 UTC, xrdt commented on frontend/__snapshots__/scenes-other-billing-v2--billing-v-2-with-discount--dark.png
<img width="1324" alt="Screenshot 2024-01-03 at 2 06 03 PM" src="https://github.com/PostHog/posthog/assets/21014901/64f62934-d3ba-4a32-b433-8e231f0d465a">

2024-01-03 22:55 UTC, raquelmsmith approved these changes

2024-01-04 00:06 UTC, merged