Feature/product analytics hide dashboard dropdown if dashboard count is 0
PostHog/posthog pull request #19530
Opened 2023-12-27 23:49 UTC by baristaGeek

## Problem
If there are no dashboards, users can select from an empty list: https://github.com/PostHog/posthog/issues/19519

## Changes
I added a conditional render to fix this. This is how it looks: 

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?
Other than manually testing on my local env, I ran the tests for scenes/insights and everything seems to be fine: 

<img width="492" alt="ranTestsForInsights" src="https://github.com/PostHog/posthog/assets/8325094/313ea68e-1c3b-48bc-b209-f907654629e7">

2023-12-28 09:26 UTC, thmsobrmlr requested changes
Hi @baristaGeek, thank you very much for your contribution! 

Peeking into this PR it looks like all filters are hidden when there are no dashboards. It would be great to only hide the dashboards filter in this case.

It seems you also made some changes to the persons dropdown. Would you mind moving this to a separate PR or at least explaining the changes there?

2023-12-28 15:13 UTC, baristaGeek commented
@thmsobrmlr gotcha! I'll do the change and re-run the tests later today. Regarding the change in the selector, it's probably like that because I mixed up something.

2024-01-03 01:02 UTC, baristaGeek commented
> Hi @baristaGeek, thank you very much for your contribution!
> 
> Peeking into this PR it looks like all filters are hidden when there are no dashboards. It would be great to only hide the dashboards filter in this case.
> 
> It seems you also made some changes to the persons dropdown. Would you mind moving this to a separate PR or at least explaining the changes there?

I made the update to only hide the dashboards selector. Please lmk what you think 

<img width="961" alt="Screenshot 2024-01-02 at 8 01 56 PM" src="https://github.com/PostHog/posthog/assets/8325094/650ee14a-b80a-47de-9efe-7d382c1003a3">

2024-01-03 09:24 UTC, daibhin approved these changes

2024-01-09 10:44 UTC, thmsobrmlr approved these changes

2024-01-09 10:57 UTC, merged