fix(3000): last updated at overflowing on mobile dashboards
PostHog/posthog pull request #19571
Opened 2024-01-03 05:12 UTC by RhysSullivan

## Problem

The "last updated at..." for dashboards on mobile overflows causing the screen to be able to be dragged horizontally

## Changes

Old:
![image](https://github.com/PostHog/posthog/assets/39114868/a935372f-fff1-4fc5-b737-fe7c692cdcd2)

New:
![image](https://github.com/PostHog/posthog/assets/39114868/c03a0cde-6b1f-41c1-8333-2b81603911e5)

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

Manually checked in the local development environment

2024-01-03 05:16 UTC, RhysSullivan commented
FYI I had to change 

`image: ghcr.io/posthog/kafka-container:v2.8.2` to `image: bitnami/kafka:3.5.1` in order to get docker compose to run - otherwise I ran into an authentication issue with accessing the container. Didn't include that change in this PR though as I was unsure if it was an error on my end

2024-01-08 12:22 UTC, Twixes requested changes
Thanks for the contribution @RhysSullivan! Just one request from me is that we keep using utility classes here

2024-01-08 12:22 UTC, Twixes commented on frontend/src/scenes/dashboard/Dashboard.tsx
> +                    <div className="dashboard-controls">
We want to stick to utility classes these days as opposed to SCSS files. In fact, if you rebase on top of current `master`, you'll be able to use full Tailwind here. 😄 Including breakpoints, e.g. `md:flex-row` – though in this case perhaps flex wrapping would do the job?
```suggestion
                    <div className="flex gap-2 items-center justify-between flex-wrap">
```

2024-01-16 15:12 UTC, Twixes approved these changes
Oh, totally missed this last week, sorry about the delay.
Looks good, let's get this in!

2024-01-17 19:18 UTC, merged