Fix encoding problem when exporting CSV
PostHog/posthog pull request #19658
Opened 2024-01-09 02:41 UTC by nykolaslima

## Problem

Encoding problem for CSV exports when opening the generated file in Microsoft Excel

## Changes

Implemented BOM in CSV exports to resolve encoding issues with special characters on Microsoft Excel.

Introduces a Byte Order Mark (BOM) at the start of CSV files to improve the handling of special characters across various platforms. The UTF-8 BOM, a specific byte sequence (EF BB BF), is used as a signal to software that the file is encoded in UTF-8, ensuring consistent interpretation of Unicode characters, especially on systems where UTF-8 is not the default encoding.

This change aims to enhance cross-platform compatibility and prevent misinterpretation of special characters in CSV exports.

## How did you test this code?

1. Generate a Survey
2. Add a response with some special characters. e.g. "你好吗"
3. Export the Survey responses
4. Open in Microsoft Excel

Fixes #19580

@liyiy could you please help with a review here?

2024-01-19 02:18 UTC, nykolaslima commented
@liyiy could you give some help to review here?

2024-01-23 14:36 UTC, nykolaslima commented
@pauldambra @daibhin could you please help me with a review/feedback here?

2024-01-26 21:08 UTC, nykolaslima commented
@liyiy fixed lint error on commit/PR message

2024-01-29 15:43 UTC, nykolaslima commented
@liyiy rebased with main. could you take a look please? thanks!

2024-01-30 12:50 UTC, mariusandra commented
Hey @nykolaslima 

To make this pass the `mypy` check (`mypy -p posthog | mypy-baseline filter`), you'll need to change a few lines higher to: `render_context: dict = {}`

I'd be happy to merge it in with the change, though in my testing locally I didn't actually see the BOM symbol inside the exported CSV files, when looking at them with a hex editor... and I'm not sure why 🤔. Did you test locally that this works?

Also, the real answer is probably to implement XLS exports 😅

2024-01-30 22:52 UTC, nykolaslima commented
@mariusandra I had to test it with microsoft excel - when importing in google sheets for example it works, but in microsoft excel it didn't

will fix what you mentioned and will let you know when its done

2024-02-15 17:24 UTC, liyiy commented
I would agree with @mariusandra here that implementing an option for XLS exports is a much more proper solution than introducing a bom mark to the file especially since there's no pressing urgency for a quick fix 👍 Did you want to take a go at that?

2024-02-26 12:32 UTC, webjunkie requested changes
Thank you for your contribution. I reviewed your code change, and unfortunately setting the bom in this context has no effect. The bom value is only used by the `CSVStreamingRenderer` for some reason, but we use `CSVRenderer` where it's not taken into account.

If you find another way to add the bom, feel free to adjust this PR. Please not that we might add Excel support anyways in the near future.

2024-02-28 10:06 UTC, webjunkie commented
FYI see #20568 for xlsx support

2024-03-14 07:31 UTC, closed without merging