feat(pipeline-ui): batch export icons
PostHog/posthog pull request #19768
Opened 2024-01-15 18:26 UTC by tiina303

## Problem

Batch exports didn't have an icon, picked the icons from the old apps repos

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2024-01-18 11:19 UTC, Twixes requested changes

2024-01-18 17:52 UTC, tiina303 commented on frontend/src/scenes/pipeline/destinationsLogic.tsx
> +    destination_type: BatchExportDestination['type']
chatGPT suggested `data storage type` I feel like service would be confusing too

2024-01-18 19:12 UTC, tiina303 commented on frontend/src/scenes/pipeline/icons/Redshift.png
I got them both originally from our plugin repos, not sure where to best get these icons, so yes they look different now too 😅  but at least look good both black and white background now

2024-01-19 15:43 UTC, tiina303 commented
quick tips for icon location problem? do they need to be in the 'public' folder?

2024-01-23 20:04 UTC, Twixes approved these changes
Looks good, I think the location makes sense

2024-01-23 20:32 UTC, Twixes commented
Ah, right, only Storybook's Webpack config wasn't happy. `public` it is.

2024-01-24 18:15 UTC, merged