[WIP] feat: embeddings similarity
PostHog/posthog pull request #20268
Opened 2024-02-12 14:06 UTC by daibhin

## Problem

## Changes

👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

2024-02-19 19:11 UTC, pauldambra requested changes
great start

2024-02-19 19:11 UTC, pauldambra commented on frontend/src/scenes/session-recordings/player/SimilarRecordings.tsx
should we put a trigger button for it in here

<img width="496" alt="Screenshot 2024-02-19 at 19 01 48" src="https://github.com/PostHog/posthog/assets/984817/37c92d57-0c6b-41cc-bc2e-e8a399803d19">

i can imagine just wanting a manual trigger for now while we test it out?

2024-02-19 19:11 UTC, pauldambra commented on posthog/session_recordings/session_recording_api.py
> +            cache.set(cache_key, recordings, timeout=30)
changed it so we don't cache empty recordings

2024-02-19 19:12 UTC, pauldambra commented on frontend/src/scenes/session-recordings/player/SimilarRecordings.tsx
feels like we're on the verge of inventing unsaved playlists / saved filters for clusterings or something...

so, we'd open an "unsaved" playlist that shows similar recordings to X, and then autosuggest title and description

title would be "recordings like {UUID}" description comes from chat gpt????

2024-02-19 19:12 UTC, pauldambra commented on frontend/src/scenes/session-recordings/player/SimilarRecordings.tsx
but that can come later (or be totally different)

2024-02-20 10:58 UTC, daibhin commented on ee/session_recordings/ai/similar_recordings.py
> +                cosineDistance(embeddings, %(target)s) AS similarity_score
Found a good example on how to do that: https://clickhouse.com/blog/approximate-nearest-neighbour-ann-with-sql-powered-local-sensitive-hashing-lsh-random-projections#querying

2024-02-20 11:01 UTC, daibhin commented on frontend/src/scenes/session-recordings/player/SimilarRecordings.tsx
That certainly makes sense. Assuming the similarity measures work (which this PR will prove) that could well save us the problem of cluster naming. We don't have to be able to make the next leap and say _why_ they're similar, just that they're similar to some root recording

2024-02-21 13:14 UTC, pauldambra approved these changes
LGTM - really excited to see how this performs!

2024-02-21 13:34 UTC, merged