Use psycopg-binary for bundled version of libpq
PostHog/posthog pull request #21476
Opened 2024-04-10 18:10 UTC by sjmiller609

## Problem

https://github.com/PostHog/posthog/issues/21475

## Changes

Updates `psycopg` to use the other version that includes bundled system dependencies. This allows to ensure the versions have the latest features, instead of accidentally using old version of libpq.

psycopg: https://github.com/psycopg/psycopg?tab=readme-ov-file#installation

## Does this work well for both Cloud and self-hosted?

`psycopg-binary` is a drop-in version of `psycopg`, the imports and everything else works exactly the same, but it just doesn't depend on libpq on the system.

## How did you test this code?

Described in the issue

2024-04-10 19:28 UTC, webjunkie requested changes
Just a quick note that the package says

> You shouldn’t install this package directly: use instead

> pip install "psycopg[binary]"


And I also thought this binary thing was gone with psycopg 3.

Additionally, we have a Django 4.2 update basically ready which will depend more on this.

Will check more closely when I get a chance.

2024-04-10 20:07 UTC, sjmiller609 commented
> Just a quick note that the package says
> 
> > You shouldn’t install this package directly: use instead
> 
> > pip install "psycopg[binary]"
> 
> And I also thought this binary thing was gone with psycopg 3.
> 
> Additionally, we have a Django 4.2 update basically ready which will depend more on this.
> 
> Will check more closely when I get a chance.

Ok thank you. FWIW, I did `pip install "psycopg[binary]"` and that results in the "-binary" showing up in "pip freeze" output.

2024-04-10 20:10 UTC, sjmiller609 commented
Also, there is another option, to update libpq by installing into the image from the Postgres repo. I think libpq-dev is just old for some reason where it's installed in the PostHog image

2024-04-11 18:41 UTC, sjmiller609 commented
@webjunkie @tomasfarias Thank you both. I am very eager to help our mutual customer.

I am happy to take the libpq update approach if you want instead of the `-binary` approach, although in my opinion the `-binary` approach seems cleaner and handles for future issues like this (clarified the two approaches in the bottom of this [doc](https://tembo.io/docs/getting-started/quickstarts/python)).

I am curious if the tests passing would be sufficient to show it's working well, perhaps it is possible to trigger them to run somehow.

Thank you so much!

2024-04-11 20:32 UTC, tomasfarias commented
For what it's worth, I am planning to move away from `psycopg` entirely in `posthog/temporal/*`, in favor of `asyncpg`. Beyond better performance, I am not happy with how awkward it is to get a pg binary `COPY` going with `psycopg`, and it got worse in 3 with the removal of `copy_from`.

Here's how it looks like with `asyncpg` in a draft branch I was playing around with: https://github.com/PostHog/posthog/commit/2a8158b30d7fe329fc1c460207175912dc15f616#diff-1e5bf24f11f58359c9712bde7a12e6c97b5fb3aca731c9aa86a54c575897f4cdR217. Just a simple call to `copy_to_table`. We can go even further beyond and get rid of the whole temporary file thing with `asyncpg`: https://github.com/PostHog/posthog/commit/88fe890a1a98869345904d186ff6fa874dee4192. 

These drafts will eventually land on `master`, just need to find some days of uninterrupted time to cherry-pick, deploy, and monitor this.

Anyways, that may take a while. In the meantime, happy to merge this as it should help with #21475. No concerns from Temporal-land, but we must look at the impact this could have on the django side of PostHog.

2024-04-11 20:47 UTC, neilkakkar commented
> Ok thank you. FWIW, I did pip install "psycopg[binary]" and that results in the "-binary" showing up in "pip freeze" output.

That's correct, we want both the binary and the main psycopg package, and hence adding "psycopg[binary]" is correct, and just the binary is wrong.

---

Tomas that is good to know, because after the version 4.2 django update, I wanted to remove psycopg2, and temporal land would be the last place still using it :)

2024-04-13 23:07 UTC, sjmiller609 commented
Thanks all so much again for your help. Please let me know if there is anything I can do to help out. Regarding asyncpg, I think we will want to check for Server Name Indication support, which can be done by scraping packets sent from the client and inspecting the server name indication field of TLS

2024-04-15 07:53 UTC, webjunkie approved these changes

2024-04-15 08:03 UTC, merged