feat: heatmap storage and API
PostHog/posthog pull request #21623
Opened 2024-04-17 18:48 UTC by pauldambra

Splitting parts out of #21487 which was a good spike PR but needs breaking up now

This adds 

* the CH table 
* the HogQL wiring
* an API reading heatmaps from the table using HogQL

2024-04-17 19:39 UTC, pauldambra commented on posthog/heatmaps/sql.py
> +        # without needing to query too many shards
```suggestion
```

2024-04-17 19:40 UTC, pauldambra commented on posthog/heatmaps/sql.py
> +        # without needing to query too many shards
```suggestion
```

2024-04-18 07:45 UTC, benjackwhite requested changes
A few things - @pauldambra let me know if you want me to implement the changes suggested

2024-04-18 07:45 UTC, benjackwhite commented on posthog/heatmaps/heatmaps_api.py
> +
```suggestion
```

2024-04-18 07:45 UTC, benjackwhite commented on posthog/heatmaps/heatmaps_api.py
> +        if value not in ["total_count", "unique_visitors"]:
This could be a ChoiceField

2024-04-18 07:45 UTC, benjackwhite commented on posthog/heatmaps/heatmaps_api.py
> +    results = serializers.ListField(child=serializers.DictField())
Why no serializer?

2024-04-18 07:45 UTC, benjackwhite commented on posthog/heatmaps/heatmaps_api.py
> +        doohickies = execute_hogql_query(
Fun police - we need a less silly var name here

2024-04-18 07:45 UTC, benjackwhite commented on posthog/hogql/database/schema/heatmaps.py
> +        # join to get analytics for heatmap areas?
Feels like this should be removed or implemented properly

2024-04-18 08:35 UTC, pauldambra commented
🤣 we both did it...

good test of how consistent a change would be if we both did it 🤣

2024-04-18 13:33 UTC, benjackwhite approved these changes

2024-04-22 20:15 UTC, pauldambra commented
paging @fuziontech 😊 

plz can we do these things to the clickhouse

2024-04-22 20:56 UTC, fuziontech approved these changes
![image](https://github.com/PostHog/posthog/assets/391319/7cb20139-2339-4775-989d-c209815a44f0)

2024-04-22 20:56 UTC, fuziontech commented on posthog/heatmaps/sql.py
> +    _timestamp DateTime
something else that would be _lovely_ to add here are the following [virtual columns](https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka#virtual-columns):
`_offset`
`_partition`

We've really wished to have these on tables in the past - would be super cool to start adding them here.

2024-04-22 20:56 UTC, fuziontech commented on posthog/heatmaps/sql.py
> +    ORDER BY (type, team_id,  toDate(timestamp), current_url, viewport_width)
love it, this is perfect. Well done 🙏

2024-04-22 20:56 UTC, fuziontech commented on posthog/heatmaps/sql.py
> +    _timestamp
same thing here:
something else that would be lovely to add here are the following [virtual columns](https://clickhouse.com/docs/en/engines/table-engines/integrations/kafka#virtual-columns):
_offset
_partition

We've really wished to have these on tables in the past - would be super cool to start adding them here.

2024-04-22 20:56 UTC, fuziontech commented on posthog/heatmaps/sql.py
> +INSERT_SINGLE_HEATMAP_EVENT = """
This is a scary bit of text - as long as it's only ever used for testing we are good!

2024-04-23 07:29 UTC, pauldambra commented
@benjackwhite I have confirmed the migration and ingestion with these latest changes locally (well, I was on partition 0 but the offset was populating)

am in and out all morning but feel free to merge without waiting for me - or I'll do it this afternoon

2024-04-23 10:14 UTC, pauldambra commented
* primed kafka setup on master
* then switched to this branch and migrated
* and could see the heatmap

<img width="947" alt="Screenshot 2024-04-23 at 11 14 12" src="https://github.com/PostHog/posthog/assets/984817/9212fcf9-5538-4e2d-aa67-f0f439128020">

2024-04-23 10:41 UTC, merged