feat: Pipeline UI visual improvements
PostHog/posthog pull request #22204
Opened 2024-05-08 20:54 UTC by tiina303

## Problem

1. smaller icons, order column
2. icons to the left
3. create buttons have a + icon too (matching insight top button style)
4. sparkgraph takes us to the metrics as would be expected
5. description to be textbox
6. text in new options page takes to creation

## Changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

## How did you test this code?

2024-05-09 07:21 UTC, benjackwhite requested changes
This looks so much nicer! Small tweak needed otherwise :chefs_kiss:

2024-05-09 07:21 UTC, benjackwhite commented on frontend/src/scenes/pipeline/PipelineNodeNew.tsx
>                                      target={target.backend == PipelineBackend.Plugin ? '_blank' : undefined}
I think this should be removed now - it should never open in a new tab

2024-05-09 12:37 UTC, tiina303 commented on frontend/src/scenes/pipeline/PipelineNodeNew.tsx
>                                      target={target.backend == PipelineBackend.Plugin ? '_blank' : undefined}
```suggestion
```

2024-05-10 07:42 UTC, benjackwhite approved these changes

2024-05-10 12:55 UTC, merged