refactor(insightTooltipUtils): Splits getFormattedDate to new getFormattedTimeInterval method
PostHog/posthog pull request #22440
Opened 2024-05-22 19:47 UTC by matzexcom

## "Problem"
In `insightTooltipUtils.tsx`, the method `getFormattedDate` may be overloaded. The method generates a formatted date, as the name implies, but it also generates an interval amount like "2 days, 4 weeks, ..." depending on the type of the first argument, which may not be intuitive for future maintainers.

## Propose
Extract the part for the interval amount from the method `getFormattedDate` into a new method `getFormattedTimeInterval`

## Changes
- Created a new method `getFormattedTimeInterval(intervalAmount: number, interval: IntervalType = 'day')``
- Changed Input type from `getFormattedDate` to string and make it required
- Changed the `InsightTooltipProps.date` to `string | number` to reflect the possibility that the date can either be a string (hopefully a date string) or a number
- Changed the `getTooltipTitle` method a bit to reflect the change that the date can be undefined or a number, which would result in a "bad" title
- Adds unit tests for `getFormattedTimeInterval` and `getTooltipTitle`

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

Add a new insight on a dashboard, test the different tabs, and check if the tooltip is the same as before.

2024-05-22 20:00 UTC, matzexcom commented
@thmsobrmlr I proposed a refactor, which we discussed in #22304, and I created this separate PR. My refactor clarifies the purpose of the insightTooltipUtil methods.
I had to adjust some types because there are cases where the date variable is a number, that was missed in the typing. I changed the nearest type definition because changing the definition of `days` in the `TrendResult` interface would result in a big refactor.

I hope my changes don't add more complexity and reduce tech dept for the future.

2024-05-23 10:28 UTC, thmsobrmlr requested changes
Something funky is going on, see here:
<img width="252" alt="Screenshot 2024-05-23 at 12 26 11" src="https://github.com/PostHog/posthog/assets/1851359/8d0a4d0a-4574-4ed6-8976-34bdfc700659">

That's how it should look:
<img width="243" alt="Screenshot 2024-05-23 at 12 26 54" src="https://github.com/PostHog/posthog/assets/1851359/8f84680d-7f0f-4f05-880b-490b0ca7b28f">

2024-05-23 20:39 UTC, matzexcom commented
Thanks for the catch; I thought I had checked that; my mistake.
I wrote an e2e test to reflect my introduced bug 🙈 and fixed it.
I am not very happy with the nested ternary. I don't know if it is allowed in the coding convention or if I should write a "helper" method for the InsightTooltip Component to get the title.

2024-05-27 11:35 UTC, thmsobrmlr reviewed
Don't know if it's actually related to this PR, but the original fix from https://github.com/PostHog/posthog/pull/22304 doesn't seem to work any more 
<img width="528" alt="Screenshot 2024-05-27 at 13 34 25" src="https://github.com/PostHog/posthog/assets/1851359/7d3b85c3-2eae-4073-a82a-f02a72c9a201">

2024-05-27 11:35 UTC, thmsobrmlr commented
> I am not very happy with the nested ternary. I don't know if it is allowed in the coding convention or if I should write a "helper" method for the InsightTooltip Component to get the title.

The nested ternary is ok, we have many of those in the codebase.

2024-05-27 15:41 UTC, matzexcom commented
@thmsobrmlr Yes not related to my changes here.

Since commit 31f97c11 the tooltip in stickiness is broken again

the interval type in `seriesData?.[0]?.filter?.interval` is undefined, the filter property is an empty object `{}`

I have to comment out/delete this two lines
```
#     "hogql-in-insight-serialization",
#     "hogql-insights-preview",
```
in `posthog/settings/feature_flags.py` after that the filter property is filled again and the tooltip is shown correctly

2024-06-05 18:20 UTC, matzexcom commented
@thmsobrmlr Any idea where I can investigate the issue? I tried to find my way in the backend and found out that the `filter` parameter is built within this method `_query_to_filter` in `posthog/hogql_queries/insights/trends/trends_query_runner.py` (maybe)

I tried to start the django server in debug mode but I can not start it and get weird `ModuleNotFoundError: No module named 'errors'`

2024-06-25 07:31 UTC, closed without merging