feat(hogql): Improve HogQL editor example design
PostHog/posthog pull request #22565
Opened 2024-05-29 09:01 UTC by webjunkie

## Problem

It's not clear that these are bullet points and code cannot be easily copied

## Changes

Use code snippet component

<img width="585" alt="image" src="https://github.com/PostHog/posthog/assets/59713/cb71d2d5-e55e-491e-aa91-47fb5f5c05b2">

## Does this work well for both Cloud and self-hosted?

n/a

## How did you test this code?

👀

2024-05-29 09:06 UTC, webjunkie commented
Somehow the look of the bullet points is irking me... but without them it looks like a potential columns of buttons or something not everyone will get. Is it alright or any other ideas?

2024-05-30 18:29 UTC, Twixes commented
Hmm, this takes up more much space. I think something really simple that can't go wrong is keeping the current examples, just with "-" swapped to "•"

2024-05-31 09:31 UTC, webjunkie commented
The snippets have the nice advantage of having the copy button on them... maybe I'll make a more tiny variant of them?

2024-06-03 11:55 UTC, webjunkie commented
Added new minimal variant

2024-06-03 13:05 UTC, Twixes requested changes

2024-06-03 13:05 UTC, Twixes commented on frontend/__snapshots__/components-hogqleditor--hog-ql-editor--dark.png
Honestly I'm not sure that this is an improvement, just because of massively more space being necessary, even in the minimal `CodeSnippet` variant :(

2024-06-04 08:13 UTC, mariusandra commented
The examples themselves could also change:

Now:

```sql
properties.$current_url
person.properties.$geoip_country_name
toInt(properties.`Long Field Name`) * 10
concat(event, ' ', distinct_id)
if(1 < 2, 'small', 'large')
```

Modern-er syntax:

```sql
properties.$current_url ??
person.properties.$geoip_country_name
toInt(properties.`Long Field Name`) * 10
f'{event} {distinct_id}'
1 < 2 ? 'small' : 'large'
```

2024-06-04 09:04 UTC, closed without merging