feat(alers): show a warning about implicit alerts deletion
PostHog/posthog pull request #22826
Opened 2024-06-09 17:27 UTC by nikitaevg

## Problem

https://github.com/PostHog/posthog/issues/14331

## Changes

## Does this work well for both Cloud and self-hosted?

## How did you test this code?

2024-06-11 17:56 UTC, nikitaevg commented
@mariusandra PTAL!

2024-06-13 08:43 UTC, mariusandra commented on posthog/models/alert.py
> +        query = filter_to_query(insight.filters)
Some insights already only have `query` set, and no `filters`.

2024-07-01 18:52 UTC, webjunkie requested changes

2024-07-14 11:02 UTC, nikitaevg commented on frontend/src/lib/components/Alerts/alertDeletionWarningLogic.ts
> +export const alertDeletionWarningLogic = kea<alertDeletionWarningLogicType>([
Yeah, makes sense, done

2024-07-17 09:50 UTC, webjunkie approved these changes

2024-07-23 08:18 UTC, nikitaevg commented
@webjunkie Could you please merge this?

2024-08-06 07:26 UTC, nikitaevg commented
@webjunkie, gentle reminder, could you please merge this?

2024-08-06 08:09 UTC, merged