feat: Support API access for basic batch export actions
PostHog/posthog pull request #23434
Opened 2024-07-03 10:14 UTC by tomasfarias

## Problem

Enable access to batch exports API with the right scoped API key. This is currently possible if one were to simulate what the frontend is doing, so we might as well also make it possible via the API with an API key.

## Changes

Set scope object actions on batch export view.

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

## How did you test this code?

2024-07-03 10:26 UTC, tomasfarias commented
@benjackwhite tagged you for review as `git blame` points that you developed the scope permission checks, and also because you are awesome. Hoping I enabled things the right way.

2024-07-08 07:18 UTC, benjackwhite requested changes

2024-07-08 07:18 UTC, benjackwhite commented on posthog/batch_exports/http.py
> +    scope_object_write_actions: list[str] = ["destroy", "create", "backfill", "pause", "unpause"]
A nicer way of doing this tbh is with the `@action` decorator adding `required_scopes=["batch_export:read"]` as that way its inline with the action

2024-07-08 07:18 UTC, benjackwhite approved these changes

2024-07-08 07:18 UTC, benjackwhite commented on posthog/batch_exports/http.py
> +    scope_object_write_actions: list[str] = ["destroy", "create", "backfill", "pause", "unpause"]
Although this also works so will approve

2024-07-09 07:08 UTC, merged