feat(ui): Improve timezone popover
PostHog/posthog pull request #23523
Opened 2024-07-08 12:44 UTC by webjunkie

## Problem

I always have a hard time reading what is actually important in the timezone popover. The timezone labels are more jarring than useful.

Old:

<img width="466" alt="image" src="https://github.com/PostHog/posthog/assets/59713/c0f05034-ee27-40b4-9c39-e564f290a95f">

New:

<img width="593" alt="image" src="https://github.com/PostHog/posthog/assets/59713/2ff00444-b2ff-48fd-a800-3dad44a946e0">

## Changes

Adjust so that there is a clear hierarchy of information importance.

2024-07-08 14:26 UTC, skoob13 approved these changes

2024-07-08 15:04 UTC, Twixes requested changes

2024-07-08 15:04 UTC, Twixes commented on frontend/src/lib/components/TZLabel/index.tsx
Visual hierarchy is great! But in this case it's somewhat chaotic: three different icons having three different sizes is too much variance, and alignment is out of whack.
<img width="593" alt="346566419-2ff00444-b2ff-48fd-a800-3dad44a946e0" src="https://github.com/PostHog/posthog/assets/4550621/44aadbe6-80a2-4c67-804a-078e3d967f49">
While we're at it, it'd also be great to center the popover title vertically in its area.

2024-07-08 15:56 UTC, webjunkie commented on frontend/src/lib/components/TZLabel/index.tsx
Agreed... I'll try to enhance this more.

2024-07-09 16:14 UTC, Twixes commented on frontend/src/lib/components/TZLabel/index.tsx
Hm, the wonkiness with margins is still there:
<img width="517" alt="Screenshot 2024-07-09 at 18 13 41" src="https://github.com/PostHog/posthog/assets/4550621/ec87f0a2-f0c9-4372-b736-ed8316049680">

2024-07-10 06:56 UTC, webjunkie commented on frontend/src/lib/components/TZLabel/index.tsx
Ah, I see. Fixed.

2024-07-10 12:41 UTC, Twixes approved these changes

2024-07-10 12:41 UTC, merged