WIP: HogQL shortcuts in taxonomic filters
PostHog/posthog pull request #23824
Opened 2024-07-18 15:31 UTC by anirudhpillai

## Problem
Fixes #13172 

Letting people breakdown by 'day of week', 'hour' without having to know about/type in HogQL.

## Changes
Initial version of UI, wanted quick feedback/open to changes.
<img width="625" alt="image" src="https://github.com/user-attachments/assets/e3f9b7bd-b2f0-459e-a59a-c07a5fe5bfe1">

<img width="755" alt="image" src="https://github.com/user-attachments/assets/c51acec6-8ef8-4062-8ec2-8284d4bb2906">

The `InfiniteList` is very tightly integrated within in the `TaxonomicFilter` like [here](https://github.com/PostHog/posthog/blob/feature/hogql-shortcuts/frontend/src/lib/components/TaxonomicFilter/InfiniteSelectResults.tsx#L44) for eg. Can still try to integrate the `render` [component](https://github.com/PostHog/posthog/blob/feature/hogql-shortcuts/frontend/src/lib/components/TaxonomicFilter/taxonomicFilterLogic.tsx#L491) better but wanted to check if it's worth the effort. Integrating will show the user the filtered counts in the category pill and make items searchable. But the search is already good enough in that it falls back to the hogql tab if it doesn't find anything else.
Also I think integrating them closely might be a bit messy with lot of overrides for this specific scenario, though might have missed a cleaner way to do it.

I went with the approach the Replay properties are using
<img width="581" alt="image" src="https://github.com/user-attachments/assets/f966f892-7dc1-419e-be13-46780e7c21a1">

## Does this work well for both Cloud and self-hosted?
N/A

## How did you test this code?
Tested on UI

2024-07-18 16:03 UTC, anirudhpillai commented on frontend/src/lib/components/TaxonomicFilter/InlineHogQLEditor.tsx
> +const SHORTCUTS = [
Guessing can expose things to use latest event/person property
```
select 
   event, 
   pdi.person.properties.email, -- current property value, fetched via a join
   poe.properties.email, -- ingestion time property stored on the event
   person.properties.email -- whatever is the default setting for your team, one of the two above
from events limit 10
```

2024-07-19 11:15 UTC, Twixes reviewed
Sounds good to me at a high level. 

Two things that stand out to me at a glance: 1. there's a lot of unused whitespace due to the column-based layout, 2. the "Enter HogQL Expression, such as" list is conceptually _pretty_ similar to shortcuts – both are lists of examples, except the first one is kind of raw, while the second is ready-made.

The question is: how can we make this user experience the best it can be?

<img width="599" alt="Screenshot 2024-07-19 at 13 10 49" src="https://github.com/user-attachments/assets/896b3a6f-dcff-460f-8287-0c383c4645b1">

2024-07-19 11:29 UTC, anirudhpillai commented
Sorry should have specified earlier.
1. I pictured the column on the right to be scrollable (once we add more shortcuts especially [latest/events](https://github.com/PostHog/posthog/pull/23824#discussion_r1683114653)). 2 column layout made more sense as then you can access shortcuts and both the HogQL editor quickly (over putting the shortcuts under the editor).
2. I decided against hiding the placeholder as the column on the right would need more space once we have more shortcuts. Though was also thinking maybe it made more sense to change the placeholder to be something like the snippet [here](https://github.com/PostHog/posthog/pull/23824#discussion_r1683114653) so users know how to access different property values.

2024-07-20 09:37 UTC, anirudhpillai commented on frontend/src/lib/components/TaxonomicFilter/InlineHogQLEditor.tsx
> +const SHORTCUTS = [
Skipping these for now as we'll implement this in the event/person properties picker

2024-07-20 09:41 UTC, anirudhpillai commented
Moved to a single column UI
Can use ideas to restyle the 'shortcuts' label. Think we might be able to get away without the label as (which looks better) as we already have tooltips for the shortcuts and when the user clicks them the behaviour is easy to understand - it fills the editor with the tooltip and sets the breakdown.

<img width="596" alt="image" src="https://github.com/user-attachments/assets/01e8429d-9ad2-4851-9f3b-2b29fba12884">

2024-08-01 11:19 UTC, Twixes requested changes
I've been thinking about this UI. The current iteration feels alright… but not _great_. I think there's a couple of aspects to it:
1. Having the list of shortcuts on the side creates a bunch of useless whitespace. We must strive for compactness.
2. The shortcuts alongside the examples feel kind of clunky. Specifically, the examples feel very stop-gappy.

I have two ideas on this:
1. The whitespace problem can be resolved by moving shortcuts directly below the expression editor
2. I think we should outsource the current examples to the Docs. Specifically, we can create a "Cheatsheet" page in the existing HogQL section of the docs in posthog.com, and link to it in `HogQLEditor`. That cheatsheet would then neatly open in the docs side panel, so it'd actually be handy. Maybe a little bit inspired by regexr.com's regex cheatsheet – except ours will be SQL:
    <img width="300" alt="Screenshot 2024-08-01 at 13 17 16" src="https://github.com/user-attachments/assets/20772e98-c928-4d78-a59c-25fa946871cf">

2024-08-19 07:31 UTC, closed without merging