fix: Make error contact point to support modal
PostHog/posthog pull request #24048
Opened 2024-07-29 12:32 UTC by joethreepwood

## Problem

I have no idea if this will work, but always good to try and give things a go. 

## Changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

## How did you test this code?

2024-07-29 12:45 UTC, MarconLP requested changes
that file is missing the `openEmailForm` function
https://github.com/PostHog/posthog/blob/44da61a8b99b3cd46e0486b3627374e8331b67e3/frontend/src/layout/navigation-3000/sidepanel/panels/SidePanelSupport.tsx#L168

2024-07-30 13:45 UTC, MarconLP commented
![2024-07-30 at 15 44 23](https://github.com/user-attachments/assets/33f78605-ca89-44b7-b9ac-b0760b6d3051)

2024-07-30 13:46 UTC, MarconLP approved these changes

2024-07-30 15:21 UTC, thmsobrmlr approved these changes

2024-07-31 09:31 UTC, merged