refactor: adjust navbar scenes
PostHog/posthog pull request #24059
Opened 2024-07-29 23:15 UTC by EDsCODE

## Problem

- there are too many unclear scenes based on data management

## Changes

- reorganize data related scenes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

## How did you test this code?

2024-07-30 09:12 UTC, benjackwhite requested changes

2024-07-30 09:12 UTC, benjackwhite commented on frontend/src/layout/navigation-3000/navigationLogic.tsx
> +                                  label: 'Data export',
I don't think this works...

"Data export" now includes "Transformations" which are all about how the incoming events are transformed - nothing to do with exporting 🤔 

I don't mind the "Events Management" change but I'm really thinking we should stick with `Data pipelines` for now as the overall term for "data in and out". Then we just need to make some UX improvements to that section to have

`|Overview|Sources|Transformations|Destinations|` 

Happy to help put that together if we agree its the way forward

2024-07-30 12:28 UTC, Twixes requested changes
I think it makes sense to split SQL out of Product Analytics!
In terms of the querying and taxonomy experience, there are just 3 tricky things right now:
1. Just "SQL" by itself is pretty vague and dry compared to the rest of the navbar.
  I propose "SQL studio" or something like that.
2. "SQL" being sandwiched between "Product analytics" and "Web analytics" seems unintuitive. This brings me to [David's doubt if SQL querying is a product by itself](https://posthog.slack.com/archives/C0113360FFV/p1722328852091199?thread_ts=1722302997.123169&cid=C0113360FFV) – I _am_ inclined to say that SQL access is more of a platform-level feature.
  Hence I argue it should be right below "Activity", in that top section that _is_ about the platform.
3. "Events management" is a _little_ bit misleading, since property management in there also covers person properties. (We've also got "Annotations" there, but they don't fit perfectly currently either.)
  I don't have an alternative solution in mind right now, other than status quo.

2024-08-01 17:49 UTC, EDsCODE commented
closing in favor of this https://github.com/PostHog/posthog/pull/24072

2024-08-01 17:49 UTC, closed without merging