feat: Move data warehouse sources into pipeline
PostHog/posthog pull request #24072
Opened 2024-07-30 10:48 UTC by benjackwhite

## Problem

Wanted to play with what an alternative could look like for data sources https://github.com/PostHog/posthog/pull/24059

## Changes

<img width="2512" alt="Screenshot 2024-07-30 at 12 46 49" src="https://github.com/user-attachments/assets/fb3b1204-3d6b-48d2-b33c-f64dcfe62835">

* Builds on the previous PR
* Moves everything into data pipelines
* Simplifies the warehouse stuff into one "sources" area

## TODO
- [ ] Fix up remaining paths so we only have one flow for the data warehouse source management
- [ ] Agree if this is the right direction

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

## How did you test this code?

2024-07-30 13:39 UTC, EDsCODE commented
I'm good with this format too as long as we address the add-on perception @raquelmsmith.

1. I think we can remove the "all tables" section as this will be in the editor schema
2. We'll need to bound the number of sources for each section (managed,self-managed) if there are 100 managed sources, you won't be able to see self-managed is on this page too

2024-07-30 13:41 UTC, benjackwhite commented
> I'm good with this format too as long as we address the add-on perception @raquelmsmith.
> 
> 1. I think we can remove the "all tables" section as this will be in the editor schema
> 2. We'll need to bound the number of sources for each section (managed,self-managed) if there are 100 managed sources, you won't be able to see self-managed is on this page too

1. Sure.
2. tbh if we are hitting that many sources, we likely need better tooling like search etc.

2024-07-30 13:44 UTC, EDsCODE commented
Maybe 100 is an exaggeration. I was just looking at the number of sources we have now and it would make stacked tables a bit confusing. Could limit the tables to show 10? and then paginate beyond that

2024-07-30 18:15 UTC, raquelmsmith commented
We can rename the addon. I just don't know what we'd rename it _to_ 🤔

2024-07-31 09:41 UTC, Gilbert09 approved these changes

2024-08-01 07:22 UTC, corywatilo commented
May feel pedantic but two things I'd like us to consider here:

1. The 3000 nav re-org moved _Data_ and _People_ to the top section along with Dashboards and Notebooks. It was intended to be the section for all your _project-related data_. I could be convinced to separate dashboards and notebooks from the data layer (since they're an abstraction from it), but think it makes sense to keep _Data_ and _People_ together.
2. The term "Events management" is clunky. Think just going with _Events_ does the job, and matches _People_ in brevity.

2024-08-01 07:53 UTC, benjackwhite commented
> May feel pedantic but two things I'd like us to consider here:
> 
> 1. The 3000 nav re-org moved _Data_ and _People_ to the top section along with Dashboards and Notebooks. It was intended to be the section for all your _project-related data_. I could be convinced to separate dashboards and notebooks from the data layer (since they're an abstraction from it), but think it makes sense to keep _Data_ and _People_ together.
> 2. The term "Events management" is clunky. Think just going with _Events_ does the job, and matches _People_ in brevity.

This is actually no longer part of this PR so we can agree what to do in follow up

2024-08-01 11:16 UTC, corywatilo commented
Not sure if we're still merging this or not but if so...

SQL Studio → SQL studio (casing)

2024-08-01 12:52 UTC, Twixes commented on frontend/src/scenes/sceneTypes.ts
> +    DataWarehouse = 'SQL',
These should stay the same

2024-08-01 13:02 UTC, Twixes requested changes, later dismissed

2024-08-01 13:02 UTC, Twixes commented on frontend/src/scenes/urls.ts
> +        }
This isn't right, as insights use `query` too. You can see this in Web analytics, where in this PR "Open as new insight" opens trend insights in… SQL studio. Only queries with `kind: "HogQLQuery"` should be opened (or generally _openable_) in the SQL scene.

2024-08-01 13:07 UTC, Twixes reviewed
Only looked at the querying/SQL side of things – just a couple of issues before merging

2024-08-01 14:13 UTC, EDsCODE commented on frontend/src/scenes/insights/insightSceneLogic.tsx
> -        '/data-warehouse/*': (_, __, { q }) => {
Good point, i set a redirect for all /data-warehouse links to go to /sql

2024-08-01 15:21 UTC, EDsCODE commented
completely removed the sql studio change for now. Scoping this PR down to just the pipeline import settings changes

2024-08-01 18:44 UTC, Twixes commented on frontend/src/scenes/pipeline/sources/Sources.tsx
> +                    <h2>Self managed sources</h2>
```suggestion
                    <h2>Self-managed sources</h2>
```

2024-08-01 19:53 UTC, merged