refactor: set default toolbar position to bottom center of the viewport
PostHog/posthog pull request #24175
Opened 2024-08-03 21:53 UTC by namit-chandwani

## Linked Issues
- Closes https://github.com/PostHog/posthog/issues/22783

## Problem

- The toolbar appears at random locations and times, causing unpredictability and potential inconvenience for users.
- Inconsistent appearance may negatively affect user experience and psychological comfort.
- Users may find it difficult to locate or use the toolbar effectively due to its random positioning.
- The current behavior lacks a default, predictable position, which could be improved by affixing the toolbar to the bottom center of the viewport.

## Changes

- **Backend:**
    - No changes required

- **Frontend (Toolbar.tsx):**
	- **Initial Drag Position:**
		- Introduced `setInitialDragPosition` to calculate and set the toolbar's initial position at the bottom center of the viewport.
		- Implemented `useLayoutEffect` to ensure `setInitialDragPosition` runs when the component mounts and whenever the `element` reference changes.

	- **Error Handling:**
	  - Added console error messages for invalid toolbar dimensions and missing toolbar elements to improve debugging and robustness.

## Does this work well for both Cloud and self-hosted?

- Yes, will work well for both Cloud and self-hosted Posthog instances.

## How did you test this code?

-   **Backend Testing:**
    
    -   No changes involved

-   **Frontend Testing:**
    
    -   **Manual Testing:**    
	    -   Verified the toolbar consistently appears at the bottom center of the viewport upon initial load.
	    -   Resized the browser window to ensure the toolbar maintains its position correctly.
	    -   Dragged the toolbar to different positions and refreshed the page to confirm it initializes at the correct default position.
	    -   Checked the browser console for any error messages related to invalid toolbar dimensions or missing elements.

	-   **Cross-Browser Testing:**
	    -   Tested the changes in multiple browsers (e.g., Chrome, Firefox, Safari) to ensure consistent behavior across different environments.

-   **Screen Recording of Testing:**

      

https://github.com/user-attachments/assets/9ad6604d-452b-4cba-b0bd-77615d3cc1d0

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactoring (altering code without changing its external behaviour)
- [ ] Documentation change
- [ ] Other

## Checklist:

- [x] Development completed
- [x] Comments added to code (wherever necessary)
- [ ] Documentation updated (if applicable)
- [ ] Added tests [Unit tests/Integration tests] (if required)
- [x] Tested changes locally

## Follow-up tasks (if any):

- None

## Additional Comments
-   Please let me know if any further changes are required elsewhere

2024-08-06 08:04 UTC, benjackwhite requested changes

2024-08-15 04:19 UTC, namit-chandwani commented on frontend/src/toolbar/bar/Toolbar.tsx
> +    }
@benjackwhite This is been resolved via commit: https://github.com/PostHog/posthog/pull/24175/commits/055feb037fcba8c6eb8e5595f1dd9742c5fcec7c now

Request you to have a look. Thanks!

2024-08-19 10:51 UTC, benjackwhite approved these changes

2024-08-21 08:31 UTC, namit-chandwani commented
Hey @benjackwhite, I've just pushed the latest commit [5519a07](https://github.com/PostHog/posthog/pull/24175/commits/5519a07e116a5a76f94a84575f60a36ede13f517), which updates the snapshots for the Toolbar story. 

This should resolve the failing Storybook visual regression test. I’ve also verified it locally by running the test using the command:

```bash
pnpm test:visual:ci:verify frontend/src/toolbar/Toolbar.stories.tsx
```

Looks like we’re good to go now!

2024-08-28 08:27 UTC, namit-chandwani commented
Hey @benjackwhite, thank you for your support with the review and approval. 

Could you please trigger the CI to re-run the visual regression test? I’ve updated the snapshots for the Toolbar story and confirmed that the test passes locally.

As this is one of my initial PRs to PostHog, I’m excited to see it through to completion :)
I’m here to help with any remaining steps if needed.

TIA

2024-08-28 13:34 UTC, namit-chandwani commented
@benjackwhite Looks like the storybook visual regression test is still failing.

However, after updating the snapshots ([here's the commit](https://github.com/PostHog/posthog/pull/24175/commits/5519a07e116a5a76f94a84575f60a36ede13f517)), I had ran the tests locally using:

```bash
pnpm test:visual:ci:verify frontend/src/toolbar/Toolbar.stories.tsx
```

Locally, all tests were passing without any problems, as shown in the screenshot:

<img width="1701" alt="Screenshot 2024-08-28 at 6 28 46 PM" src="https://github.com/user-attachments/assets/e7ff899e-fca6-49fb-a6d7-2efdd3d3a001">




Do you have any suggestions on what I might be missing or what else I can try?

Appreciate your help!

2024-08-28 17:16 UTC, benjackwhite commented
I really can't figure out why the tests keep failing...

2024-08-28 17:21 UTC, benjackwhite commented
This PR was stuck on my brain today and I thought there might actually be a better option... The issue with this one is that as soon as the element moves, the fixed position is lost forever. I put something together that allows "snapping" the position to different areas which I think [works a little nicer](https://github.com/PostHog/posthog/pull/24648).

Sorry for jumping in 🙈 without this PR I wouldn't have thought of the other solution for sure!

2024-09-05 08:16 UTC, closed without merging