fix(insights): Improve load more for breakdowns
PostHog/posthog pull request #24231
Opened 2024-08-07 08:57 UTC by webjunkie

## Problem

It was only working if you selected "display other" presumably this was because of the filter conversion?

Fixes #23554

## Changes

- make it show up in all cases
- adjust the wording to have the actual values - since you also modify the query with this and it's persisted when you save

## How did you test this code?

Tested locally

2024-08-07 10:24 UTC, thmsobrmlr commented on frontend/__snapshots__/scenes-app-experiments--running-trend-experiment--dark.png
Seems this affects experiment results as well, where we don't need it.

2024-08-07 10:32 UTC, thmsobrmlr commented on frontend/__snapshots__/scenes-app-insights--trends-area-breakdown--dark--webkit.png
In general we should probably only show this if there are more breakdown values.

2024-08-07 10:43 UTC, skoob13 approved these changes

2024-08-12 09:50 UTC, webjunkie commented
@thmsobrmlr I've added a relatively quick approach/workaround to tell if there are actually more values. Can you check again? Also for experiments, I checked one and now the load more isn't there. But maybe that depends on certain conditions, so would be great if you can also check that.

2024-08-13 10:02 UTC, thmsobrmlr requested changes
Thanks for the follow-up @webjunkie! Works great now.

Did a couple of stylistic changes, hope you don't mind.

There's only one thing blocking this from merging now: The button only appears on a new insight, but not after saving. I'm assuming this has something to do with the insight serializer not returning the `hasMore` or similar.

2024-08-13 10:03 UTC, thmsobrmlr commented
> Also for experiments, I checked one and now the load more isn't there. But maybe that depends on certain conditions, so would be great if you can also check that.

This was just an artifact of the previous implementation where we would always display the button regardless if there are more values. Experiments only have two values and as such it's working there now.

2024-08-13 13:28 UTC, webjunkie commented
> with the insight serializer not returning the hasMore or similar.

Okay fixed this now. The `hasMore` is next to the results... which means it needs to go into the serializer as well. This whole area is a bit cumbersome. I wonder why no other insights had specific fields that needed to be included. We have `hasMore` also for other query responses, but it seems it's mostly actors responses that are not going to be the result of a saved insight 🤔

2024-08-13 13:32 UTC, thmsobrmlr commented
> > with the insight serializer not returning the hasMore or similar.
> 
> Okay fixed this now. The `hasMore` is next to the results... which means it needs to go into the serializer as well. This whole area is a bit cumbersome. I wonder why no other insights had specific fields that needed to be included. We have `hasMore` also for other query responses, but it seems it's mostly actors responses that are not going to be the result of a saved insight 🤔

Yeah it's quite annoying. We did have other insights with problems here and probably still have some edge cases that are unhandled..

2024-08-13 13:32 UTC, thmsobrmlr approved these changes

2024-08-14 09:30 UTC, merged