fix(api): fix `KeyError` in _filter_queryset_by_parents_lookups
PostHog/posthog pull request #24693
Opened 2024-08-30 07:39 UTC by jurajmajerik

## Problem
https://posthog.sentry.io/issues/5732669244/?alert_rule_id=4194161&alert_type=issue&notification_uuid=77b8f425-2556-4c84-aec3-bf3b8338ea28&project=1899813&referrer=slack

## Changes
Fixes a `KeyError` that occurs in the `_filter_queryset_by_parents_lookups` method when the method tries to access a key that doesn't exist in `parents_query_dict`.

## How did you test this code?
👀

2024-08-30 08:38 UTC, neilkakkar commented
didn't look too deeply, but the problem here might be in the filter rewrite rules here: https://github.com/PostHog/posthog/blob/master/ee/api/feature_flag_role_access.py#L80

2024-09-02 07:24 UTC, benjackwhite requested changes

2024-09-02 07:24 UTC, benjackwhite commented on posthog/api/routing.py
> +            if source in parents_query_dict:
I think this _should_ throw. If it isn't found then that indicates the implementation is wrong

2024-09-02 15:13 UTC, jurajmajerik commented
@Twixes this is likely related to https://github.com/PostHog/posthog/pull/23246

I don't have much context here, but seems the rewrite rules of `FeatureFlagRoleAccessViewSet` weren't updated in that PR - the change I've made here fixed the issue for me locally. Pls check :)

2024-09-03 07:21 UTC, benjackwhite approved these changes

2024-09-03 07:47 UTC, merged