feat(cdp): Use cyclotron part 2
PostHog/posthog pull request #24746
Opened 2024-09-02 13:52 UTC by benjackwhite

## Problem

The first PR refactored the code to make it easier to enqueue and read from Cyclotron instead of Kafka. This implements it

## Changes

* Adds the extra work needed to allow writing and reading from Cyclotron postgres instead of kafka
* Lots of pseudocode of things that need changing

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

## How did you test this code?

2024-09-04 17:48 UTC, bretthoerner commented
I got this at runtime:

```
Error: Cannot find module './manager'
Require stack:
- /Users/brett/Development/posthog/posthog/plugin-server/node_modules/.pnpm/file+..+rust+cyclotron-node/node_modules/@posthog/cyclotron/dist/index.js
- /Users/brett/Development/posthog/posthog/plugin-server/src/cdp/cdp-consumers.ts
- /Users/brett/Development/posthog/posthog/plugin-server/src/main/pluginsServer.ts
- /Users/brett/Development/posthog/posthog/plugin-server/src/index.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/Users/brett/Development/posthog/posthog/plugin-server/node_modules/.pnpm/file+..+rust+cyclotron-node/node_modules/@posthog/cyclotron/src/index.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.newLoader [as .js] (/Users/brett/Development/posthog/posthog/plugin-server/node_modules/.pnpm/pirates@4.0.5/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/brett/Development/posthog/posthog/plugin-server/node_modules/.pnpm/file+..+rust+cyclotron-node/node_modules/@posthog/cyclotron/dist/index.js',
    '/Users/brett/Development/posthog/posthog/plugin-server/src/cdp/cdp-consumers.ts',
    '/Users/brett/Development/posthog/posthog/plugin-server/src/main/pluginsServer.ts',
    '/Users/brett/Development/posthog/posthog/plugin-server/src/index.ts'
  ]
}
```

Even after whatever `bin/start` runs and `pnpm i`, my cyclotron install was still this:

```
# plugin-server/node_modules/@posthog/cyclotron
$ find .
.
./dist
./dist/index.js
./dist/index.js.map
./dist/index.d.ts
./index.node
./package.json
```

Did you have to bust the cache locally? I did `pnpm store prune` which was probably heavy handed, and I don't recommend it. Maybe `pnpm update @posthog/cyclotron --force` alone would have worked. Either way it seems like our install process doesn't detect/install changes in `cyclotron-node`?

2024-09-04 17:54 UTC, bretthoerner commented
Seemed to work for me otherwise, though. I have a Webhook defined, they all fired, went back to hog, and then were cleaned up by the janitor.

Metrics are happy:
```
cyclotron_janitor_completed_jobs{janitor_id="default_janitor_id",shard_id="default"} 145

#...

cyclotron_fetch_jobs_completed{shard_id="default",worker_id="default_worker_id",queue_served="fetch"} 145
```

2024-09-09 14:39 UTC, mariusandra requested changes
Tested locally, everything seems to work. Two issues worth addressing though:
- I think I found a bug with the cyclotron/kafka split (comment inline)
- `bin/start-cyclotron` should also use the new env.

2024-09-09 14:42 UTC, benjackwhite commented on plugin-server/src/cdp/cdp-consumers.ts
> +        delete (serializedInvocation as any).hogFunction
Same same. Given this is temporary I'm not going to optimise around it if thats okay

2024-09-09 14:44 UTC, mariusandra approved these changes
Go forth and multiply!

2024-09-10 07:05 UTC, merged