chore: change funnel errors to ExposedHogQLError
PostHog/posthog pull request #24822
Opened 2024-09-05 18:32 UTC by aspicer

## Problem

Realized through development environment that non posthog users couldn't see useful funnel errors (this was likely an async query change)

![image](https://github.com/user-attachments/assets/4567c86f-10ca-4b82-8742-79ae9ce7f2b6)

## Changes

Change all validation errors in funnels to ExposedHogQLError

## Does this work well for both Cloud and self-hosted?

Yes

## How did you test this code?

Made sure errors surfaced when you weren't a staff user.

2024-09-09 09:30 UTC, skoob13 approved these changes

2024-09-09 10:25 UTC, Twixes reviewed
Why not the more general solution: replacing `isinstance(err, ExposedHogQLError | ExposedCHQueryError)` with `isinstance(err, ExposedHogQLError | ExposedCHQueryError | APIException)`? This would allow all `ValidationError`s but also e.g. `PermissionDenied` to pass through, which should be the case, since these DRF exceptions are explicitly expose-able

2024-09-09 10:39 UTC, Twixes requested changes
Seems passing `ValidationError` through is the way – e.g. would automatically solve this issue: https://github.com/PostHog/posthog/pull/24809#issuecomment-2336471553

2024-09-11 10:39 UTC, Twixes approved these changes
🙌

2024-09-11 10:39 UTC, merged