feat(data-warehouse): Added Chargebee data source
PostHog/posthog pull request #25818
Opened 2024-10-25 11:08 UTC by rossgray

## Problem

Still a WIP:
- [ ] need to add more resources
- [ ] will likely need to regenerate the Django migration

## Changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

## How did you test this code?

2024-10-25 11:48 UTC, Gilbert09 requested changes
One change, just to check the subdomain, otherwise this looks good!

2024-10-25 11:48 UTC, Gilbert09 commented on posthog/warehouse/api/external_data_source.py
> +                )
Nice, we also wanna check the subdomain to ensure users can't do any RCE attacks here, see https://github.com/PostHog/posthog/blob/master/posthog/warehouse/api/external_data_source.py#L781-L786

2024-10-25 11:48 UTC, Gilbert09 commented on posthog/temporal/data_imports/pipelines/chargebee/__init__.py
> +        "Customers": {
I reckon starting with customers, subscriptions, orders, invoices, transactions would be good

2024-10-25 13:26 UTC, rossgray commented on posthog/warehouse/api/external_data_source.py
> +                )
ah yes, I missed that, thanks!

2024-11-01 17:08 UTC, Gilbert09 approved these changes

2024-11-01 17:19 UTC, merged