fix: position of white noise middleware
PostHog/posthog pull request #25857
Opened 2024-10-28 18:17 UTC by pauldambra

The whitenoise middleware docs (https://whitenoise.readthedocs.io/en/stable/django.html#enable-whitenoise) say its middleware should be high up in the list of middleware

we had _a lot_ of middleware ahead of it, so we're running those middleware on requests for static assets

locally this change makes the request 60-100ms TTFB instead of 120-169ms TTFB

see https://posthoghelp.zendesk.com/agent/tickets/19227

2024-10-28 18:28 UTC, timgl requested changes

2024-10-28 18:28 UTC, timgl commented on posthog/settings/web.py
> +    "whitenoise.middleware.WhiteNoiseMiddleware",
I would definitely put this behind ShortCircuitMiddleware, as otherwise you're loading this for every capture/decide endpoint hit.

2024-10-30 15:01 UTC, benjackwhite approved these changes
No more context than anyone else to know if this is a good call or not but in principle - sure?

2024-10-30 18:07 UTC, timgl approved these changes

2024-10-30 18:16 UTC, merged