feat(max): Summarize insight results
PostHog/posthog pull request #26172
Opened 2024-11-13 17:07 UTC by Twixes

## Problem

You have been able to ask Max questions, but all it gave you was a graph.

## Changes

Now Max actually gives you an answer based on the data:

https://github.com/user-attachments/assets/a27dd2f0-8b46-48b8-82f4-a96bb8fd045b

## How did you test this code?

A few different tests.

2024-11-15 10:35 UTC, skoob13 requested changes
The code LGTM. Two things:
1. It looks like using prompt templates in BaseMessages doesn't apply formatting in ChatPromptTemplate. If I send a message, the node outputs that results weren't provided. Replacing to tuples make it work.
2. "how many users upgraded their plan to personal pro? show trends" fails to query. I've attached the Pydantic exception below. There must be some schema difference, so we can use the same converter functions.

Exception:
```
70 validation errors for QuerySchemaRoot
TrendsQuery.series.0.EventsNode.properties.0.EventPropertyFilter.type
  Input should be 'event' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.EventsNode.properties.0.PersonPropertyFilter.type
  Input should be 'person' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.EventsNode.properties.0.ElementPropertyFilter.key
  Input should be 'tag_name', 'text', 'href' or 'selector' [type=enum, input_value='new_plan', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/enum
TrendsQuery.series.0.EventsNode.properties.0.ElementPropertyFilter.type
  Input should be 'element' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.EventsNode.properties.0.SessionPropertyFilter.type
  Input should be 'session' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.EventsNode.properties.0.CohortPropertyFilter.key
  Input should be 'id' [type=literal_error, input_value='new_plan', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.EventsNode.properties.0.CohortPropertyFilter.type
  Input should be 'cohort' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.EventsNode.properties.0.CohortPropertyFilter.value
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='personal/pro', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/int_parsing
TrendsQuery.series.0.EventsNode.properties.0.RecordingPropertyFilter.type
  Input should be 'recording' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.EventsNode.properties.0.LogEntryPropertyFilter.type
  Input should be 'log_entry' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.EventsNode.properties.0.GroupPropertyFilter.type
  Input should be 'group' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.EventsNode.properties.0.FeaturePropertyFilter.type
  Input should be 'feature' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.EventsNode.properties.0.HogQLPropertyFilter.type
  Input should be 'hogql' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.EventsNode.properties.0.HogQLPropertyFilter.operator
  Extra inputs are not permitted [type=extra_forbidden, input_value=<AssistantSingleValueProp...Operator.EXACT: 'exact'>, input_type=AssistantSingleValuePropertyFilterOperator]
    For further information visit https://errors.pydantic.dev/2.9/v/extra_forbidden
TrendsQuery.series.0.EventsNode.properties.0.EmptyPropertyFilter.key
  Extra inputs are not permitted [type=extra_forbidden, input_value='new_plan', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/extra_forbidden
TrendsQuery.series.0.EventsNode.properties.0.EmptyPropertyFilter.operator
  Extra inputs are not permitted [type=extra_forbidden, input_value=<AssistantSingleValueProp...Operator.EXACT: 'exact'>, input_type=AssistantSingleValuePropertyFilterOperator]
    For further information visit https://errors.pydantic.dev/2.9/v/extra_forbidden
TrendsQuery.series.0.EventsNode.properties.0.EmptyPropertyFilter.type
  Extra inputs are not permitted [type=extra_forbidden, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/extra_forbidden
TrendsQuery.series.0.EventsNode.properties.0.EmptyPropertyFilter.value
  Extra inputs are not permitted [type=extra_forbidden, input_value='personal/pro', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/extra_forbidden
TrendsQuery.series.0.EventsNode.properties.0.DataWarehousePropertyFilter.type
  Input should be 'data_warehouse' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.EventsNode.properties.0.DataWarehousePersonPropertyFilter.type
  Input should be 'data_warehouse_person_property' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.ActionsNode.id
  Field required [type=missing, input_value={'event': 'upgraded_plan'...alue': 'personal/pro'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
TrendsQuery.series.0.ActionsNode.kind
  Input should be 'ActionsNode' [type=literal_error, input_value='EventsNode', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.ActionsNode.properties.0.EventPropertyFilter.type
  Input should be 'event' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.ActionsNode.properties.0.PersonPropertyFilter.type
  Input should be 'person' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.ActionsNode.properties.0.ElementPropertyFilter.key
  Input should be 'tag_name', 'text', 'href' or 'selector' [type=enum, input_value='new_plan', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/enum
TrendsQuery.series.0.ActionsNode.properties.0.ElementPropertyFilter.type
  Input should be 'element' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.ActionsNode.properties.0.SessionPropertyFilter.type
  Input should be 'session' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.ActionsNode.properties.0.CohortPropertyFilter.key
  Input should be 'id' [type=literal_error, input_value='new_plan', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
TrendsQuery.series.0.ActionsNode.properties.0.CohortPropertyFilter.type
  Input should be 'cohort' [type=literal_error, input_value=<Type.EVENT: 'event'>, input_type=Type]
    For further information visit https://errors.pydantic.de [...]

2024-11-15 17:20 UTC, Twixes commented on ee/hogai/summarizer/nodes.py
> +            elif isinstance(message, AssistantMessage | FailureMessage):
Yup, we don't really

2024-11-15 17:24 UTC, Twixes commented
Thanks @skoob13!

Re 1: Indeed, just before posting this I reworked `run()` so that _all_ the messages are generated in `_construct_messages()`, since it seemed a bit pointless to do it in multiple stages. Missed that BaseMessage instances aren't templated, we need message tuples instead.

Re 2: Looks like Pydantic's `.model_dump()` doesn't serialize Python enums to underlying values by default. Adding `mode="json"` fixed this.

2024-11-18 10:05 UTC, skoob13 approved these changes

2024-11-18 10:05 UTC, merged