feat: making role in organization as a required field
PostHog/posthog pull request #26205
Opened 2024-11-14 20:35 UTC by surbhi-posthog

## Problem

since we want to understand the type of users using our product, having the role information is crucial and we want to try to make it as a required field. 

## Changes
New changes doesn't allow the user to proceed without adding in a role. 
![image](https://github.com/user-attachments/assets/c90b1ece-619a-4b75-9ccc-38634b1742b2)

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

## How did you test this code?

I'm still testing this end to end. At the moment, i can verify changes in the UI that the error message shows up and the user is forced to add their role. However, I'm running into some validating user credential issues that is blocking me from testing the full sign up flow. I'm still placing the PR up for an initial review

2024-11-14 20:59 UTC, patricio-posthog approved these changes
Not a React expert, but it looks good to me :)

2024-11-14 21:13 UTC, zlwaterfield requested changes

2024-11-14 21:13 UTC, zlwaterfield commented on frontend/src/scenes/authentication/signup/signupForm/signupLogic.ts
> +                    if (!payload.role_at_organization) {
Shouldn't need this since it's required.

2024-11-14 21:13 UTC, zlwaterfield commented on frontend/src/scenes/authentication/signup/signupForm/signupLogic.ts
> +                        role_at_organization: payload.role_at_organization || undefined,
Shouldn't need this since it's required. The other fields are there to manipulate the value to undefined if it's not set.

2024-11-14 21:13 UTC, zlwaterfield commented on frontend/src/scenes/authentication/signup/signupForm/signupLogic.ts
> +                role_at_organization: !role_at_organization ? 'Please select your role in the organization' : undefined,
Yeah, you're learning kea!

2024-11-14 22:22 UTC, zlwaterfield commented
@surbhi-posthog after you fix something feel free to re-request a review.

For the failed E2E test, click into it and see if it's related to your change, if not you can try to re-run as it may be a flakey test.

2024-11-15 16:26 UTC, surbhi-posthog commented
@zlwaterfield, i've added the changes to the cypress tests and they now pass. Could you take another look at this?

In the meantime, I'm fixing the `xmlsec` issue on my local and verifying if cleaning the volumes and contains in orbstack fixes the authentication credential issue.

2024-11-15 18:28 UTC, zlwaterfield approved these changes
Nice work! LGTM.

2024-11-15 18:44 UTC, surbhi-posthog commented
I ran `DEBUG=1 CLOUD_DEPLOYMENT=1 bin/start` and cleared authentication credential issue

2024-11-15 18:44 UTC, merged