feat(cdp): site destinations
PostHog/posthog pull request #26572
Opened 2024-12-02 15:44 UTC by mariusandra

## Problem

Splitting https://github.com/PostHog/posthog/pull/26169 in two: site destinations & new site apps

## Changes

This is the site destinations part:

![2024-11-28 16 41 29](https://github.com/user-attachments/assets/4c1d4efa-b75f-4b75-8085-5b8a21de084b)

Plus some more changes:

- Hog Function and Hog Function Template API endpoints now support filtering by multiple types
- Make one extra query in `/decide` for teams with site apps enabled to load new hog-function-site-apps/destinations. We're moving to something more static soon anyway.
- Add group type aliases to CDP, like "organization.properties.name", in addition to "group_0.properties.name"

## How did you test this code?

Added a bunch of tests

2024-12-02 16:52 UTC, benjackwhite requested changes
Quick one - feature flag it please

2024-12-02 17:23 UTC, mariusandra commented
Done, [flag added](https://github.com/PostHog/posthog/pull/26572/commits/498569161199e00ecbe2930bf4101886d3e2f151)

2024-12-03 09:01 UTC, benjackwhite approved these changes

2024-12-03 09:02 UTC, mariusandra commented on posthog/cdp/templates/_internal/template_blank.py
> +                "email": "{person.properties.email}",
The ones you have provided to posthog-js will be

2024-12-03 12:15 UTC, merged