fix(experiments): Hackily apply timestamp to ASOF LEFT JOIN
PostHog/posthog pull request #26852
Opened 2024-12-11 21:45 UTC by danielbachhuber

See https://posthog.slack.com/archives/C07PXH2GTGV/p1733941329943129?thread_ts=1733936406.339719&cid=C07PXH2GTGV
See https://github.com/PostHog/posthog/issues/26332

## Changes

Hackily pulls timestamp statements from `node.where` and applies them to the ASOF LEFT JOIN.

Ideally, we'd directly reference the timestamp column from the data warehouse table. However, HogQL doesn't support referencing the parent clause, so this will have to suffice for now.

I'd also like to add an assertion that this timestamp information is added to the ASOF LEFT JOIN. However, the join isn't present in the HogQL so I need to somehow access the generated ClickHouse SQL.

## How did you test this code?

Tests should pass. I also inspected the query output.

2024-12-11 22:03 UTC, timgl requested changes
Would also be good to add a test here to make sure this does what we think it does

2024-12-11 22:03 UTC, timgl commented on posthog/warehouse/models/join.py
> +                node.where.exprs[0].op == ast.CompareOperationOp.GtEq
`WhereClauseExtractor` is probably a better way of doing this.

2024-12-12 14:32 UTC, danielbachhuber commented
@timgl I added a test to assert the contents of the `clickhouse_sql`.

> `WhereClauseExtractor` is probably a better way of doing this.

I'm not sure I follow. Can you provide a specific example?

2024-12-12 15:31 UTC, timgl approved these changes

2024-12-12 15:31 UTC, merged