feat: show modified recommended list as default for analytics
PostHog/posthog pull request #26993
Opened 2024-12-17 22:03 UTC by surbhi-posthog

## Problem

We noticed that many users entering our funnel are categorized as "Low ICP." To help these users convert through the onboarding flow, this PR introduces a few product recommendations:

Show HTML first – This is likely to be more useful for non-technical users.
Show the recommendations list by default – This makes it easier for users to find the "Invite Members" action on the same page, and reduces the overwhelming number of options.
These changes are applied to all users, as I wanted to avoid introducing role-based product changes unless absolutely necessary.

For more details on the hypothesis please refer to this notebook: https://us.posthog.com/project/2/notebooks/p9AvDIAK
	

## Changes

1. Reordered the SDK list.
2. Added a feature flag (Note: I wasn't able to test this properly, as the feature flag didn't appear in the values).
3. Defaulted to "Recommended" for users selecting Product Analytics.

| Before | After |
|--------|-------|
|![image](https://github.com/user-attachments/assets/b1321641-df34-4ec2-adfc-54befdbf1450) | ![image](https://github.com/user-attachments/assets/2cc04c83-cc00-4ba5-b91f-76187ca05075) |

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

Cloud: yes

## How did you test this code?

Since I was unable to toggle the feature flags through the console, I hardcoded them to true and then verified that the changes were visible only to product analytics, ensuring that they did not affect other products.

2024-12-18 17:41 UTC, rafaeelaudibert reviewed
I'm just reviewing a couple of random PRs to get myself familiarized with the rest of the codebase, so take my review with a grain of salt, I don't know anything about current goals in the team :)

Wont approve nor request changes because Im just passing by

2024-12-18 17:41 UTC, rafaeelaudibert commented on frontend/src/scenes/onboarding/sdks/sdksLogic.tsx
> +const getOrderedSDKs = (sdks: SDK[]): SDK[] => {
This is only "ordered" in terms of product analytics, so I'd be more semantic in this function name

```suggestion
const getOrderedProductAnalyticsSdks = (sdks: SDK[]): SDK[] => {
```

2024-12-18 17:41 UTC, rafaeelaudibert commented on frontend/src/scenes/onboarding/sdks/sdksLogic.tsx
> +        ...sdks.filter((sdk) => sdk.key === 'javascript-web'),
No need to use `filter`, we can just find the original ones
```suggestion
        sdks.find((sdk) => sdk.key === 'html'),
        sdks.find((sdk) => sdk.key === 'javascript-web'),
```

You might need to add `.filter(Boolean)` at the end of this to make TS happy

2024-12-18 17:41 UTC, rafaeelaudibert commented on frontend/src/scenes/onboarding/sdks/sdksLogic.tsx
> -            // TODO: This doesn't seem to run when the setProductKey action is called in onboardingLogic...
Have you checked if this is solved? If not, we should probably keep this here?

2024-12-18 19:04 UTC, zlwaterfield requested changes
Great work here :). Added a few requests.

2024-12-18 19:04 UTC, zlwaterfield commented on frontend/src/lib/constants.tsx
> +    PRODUCT_ANALYTICS_ONBOARDING: 'product-analytics-onboarding', // owner: @surbhi
Can we make this experiment key more specific to these changes incase we want to add more in onboarding.

2024-12-18 19:04 UTC, zlwaterfield commented on frontend/src/scenes/onboarding/sdks/sdksLogic.tsx
> +                values.featureFlags[FEATURE_FLAGS.PRODUCT_ANALYTICS_ONBOARDING]
For an experiment we can do `values.featureFlags[FEATURE_FLAGS.PRODUCT_ANALYTICS_ONBOARDING] === "test"` where "test" is the experiment variant.

2024-12-18 19:04 UTC, zlwaterfield commented on frontend/src/scenes/onboarding/sdks/sdksLogic.tsx
> +                values.featureFlags[FEATURE_FLAGS.PRODUCT_ANALYTICS_ONBOARDING]
Sam as comment below.

2024-12-18 19:04 UTC, zlwaterfield commented on frontend/src/scenes/onboarding/sdks/sdksLogic.tsx
> +                values.featureFlags[FEATURE_FLAGS.PRODUCT_ANALYTICS_ONBOARDING] &&
Same as comment below.

2024-12-18 23:02 UTC, surbhi-posthog commented
I've suggested changes. However, I'm still not able to see the feature flag values show up locally. This is currently undefined:
` values.featureFlags[FEATURE_FLAGS.PRODUCT_ANALYTICS_MODIFIED_SDK_LIST] `

2024-12-18 23:45 UTC, zlwaterfield commented on frontend/src/scenes/onboarding/sdks/sdksLogic.tsx
> -            actions.resetSDKs()
Any reason this was removed?

2024-12-19 00:51 UTC, raquelmsmith commented on frontend/src/lib/constants.tsx
Commenting on this file so we can thread the discussion...

I'm generally hesitant about this change because it effectively hides the rest of the SDKs we offer from the page. 

The null hypothesis is that people won't notice the "recommended" filter, won't click the "X" to clear it, and won't see all the other SDKs we offer.

Why don't we just put the recommended ones at the top in a separate section, with some way to show that they are recommended?

2024-12-19 00:56 UTC, raquelmsmith commented on frontend/src/lib/constants.tsx
Another thing - I think with this we are maybe prioritizing the wrong set of users?

High ICP users - engineers - will want to see all the SDK options we have so they can find the one they need. Maybe the experience there needs to change for those users if their conversion through this step isn't great, but I don't see why we'd change the onboarding for our most popular product to cater to _low_ ICP users.

If anything, we should only apply this change to people who we know are low-ICP (using role data is easy easy easy and required on signup for this exact reason). We can even skip this SDKs screen entirely for these people and do a custom invite thing where it says "you're all set up, now invite your technical team to implement" and in the email we send them we give them context about what needs to happen.

2024-12-19 00:56 UTC, raquelmsmith requested changes
I feel like my comments should be addressed before this is merged

2024-12-20 15:30 UTC, surbhi-posthog commented
After consolidating the feedback above, I've made a few significant changes to the experiment:

1. **Role-Based Targeting**: The new features will now only be shown to users with a low ICP (Ideal Customer Profile) score, which corresponds to our non-technical users.
2. **Invite Help Card Placement**: Instead of using a recommended list, I moved the invite help card to the top of the page for these users.

I’m hoping to get some signal from this test, and if anything learn how to collect signal correctly for this flow.

This got me thinking about other ideas, some of which I know we’re already discussing:

1. When the user selects products they want to use, we still show a list of all the product available in the side bar, I was wondering if adding an optimization there could help with user journey
2. Allowing users to skip the SDK step entirely, if needed.
3. Showing onboarding steps for all products selected at the beginning.
4. Allowing users to revisit the onboarding flow from different situations.

2025-01-09 17:51 UTC, surbhi-posthog commented
Closing this since I followed up on these changes on this stack: https://github.com/PostHog/posthog/pull/27401

2025-01-09 17:51 UTC, closed without merging