fix (action) Show the error info when deleting the action failed
PostHog/posthog pull request #27124
Opened 2024-12-23 06:19 UTC by xu20160924

## Problem

The delete API of the backend, but in the list missing shows the error information

![image](https://github.com/user-attachments/assets/3b82af08-e7db-449b-9760-02dc03fdc78a)
![image](https://github.com/user-attachments/assets/3e6362ab-12a6-4c24-9099-cfe6843ef385)

## Changes

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

Handle the exceptions in the action list and display it.

## Does this work well for both Cloud and self-hosted?

self-hosted worked

## How did you test this code?
Self-hosted test

2024-12-24 05:25 UTC, xu20160924 commented
@Twixes  Could you please review my pull request? Thank you.

2025-01-01 09:03 UTC, xu20160924 commented
waiting

2025-01-02 19:13 UTC, Twixes requested changes
Thank you for the PR @xu20160924!

Just one thing I noticed: It looks like there's actually a few more analogous `void deleteWithUndo(...)` call sites – they should all be `.catch()`ing potential errors, so that app behavior is consistent. Can you update those places too?

2025-01-03 11:19 UTC, Twixes commented on frontend/src/scenes/pipeline/destinations/destinationsLogic.tsx
>                      })
Oh, thank you for going through all these! However, I wasn't clear enough, which I apologize about: We don't in fact want `.catch()` inside logics, since we have automatic error handling there.
This PR only needs to affect `onClick` handlers.
Can you quickly revert the changes to logic files? Then we'll be able to get this in immediately. :)

2025-01-03 15:00 UTC, xu20160924 commented on frontend/src/scenes/pipeline/destinations/destinationsLogic.tsx
>                      })
Sorry for the incorrectly modified, I didn't notice the automatic error handling, I've reverted it.

2025-01-06 13:08 UTC, Twixes approved these changes
Awesome :shipit:

2025-01-06 13:08 UTC, merged