Fix unneeded horizontal scrolling on Onboarding pages
PostHog/posthog pull request #27134
Opened 2024-12-23 15:34 UTC by lucasheriques

## Problem

Fixes https://github.com/PostHog/posthog/issues/25527.

There's extra margin on the posthog onboarding pages that's causing an horizontal scroll.

## Changes

| Before | Header |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/38f57894-0aed-4f14-9890-ce39d84fcaa4) | ![CleanShot 2024-12-23 at 12 34 00@2x](https://github.com/user-attachments/assets/1e8ec70d-a86d-454b-8738-6c80220e05ea) | 

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

N/A

## How did you test this code?

Verified on localhost, since it's a UI only change

2024-12-23 15:45 UTC, daibhin approved these changes

2024-12-23 15:49 UTC, zlwaterfield requested changes
I don't think using a fixed value will resolve this.

We should probably be using the negative of `--scene-padding` which is the reason we need to have the negative margin in the first place and it's dependant on the screen size.

2024-12-23 16:04 UTC, lucasheriques commented
> --scene-padding

ohh I didn't know we have that. yeah I just checked what was the padding on the scene and changed to the appropriate value.

thanks for the pointer!

2024-12-23 16:09 UTC, lucasheriques commented
@zlwaterfield added a new spacing size to use `--scene-padding` in the tailwind config

2025-01-02 19:34 UTC, zlwaterfield approved these changes
Sorry for the delay here, looks good!

2025-01-02 19:34 UTC, merged