feat: add insight and remove insight from dashoard
PostHog/posthog pull request #27138
Opened 2024-12-23 18:17 UTC by k11kirky

## Problem

You cannot add existing insights to a dashboard from the dashboard screen. This creates a confusing UX and likely duplicate created insights.

## Changes

When you click add insight from the dashboard a new modal will pop up allowing you to select an exisitng insight or create a new one.

2025-01-02 10:56 UTC, thmsobrmlr requested changes
Hey @k11kirky, awesome job getting this started - seriously, this is such a great addition! It's kind of wild we didn’t have this feature already.

A few remarks from my end:
- Pagination in the modal does not work.
- It would be great to have an "in progress" state that disables the individual buttons, while an insight is added or removed.
- I know our UI is quite inconsistent across places, but it would be great if we'd get more consistent eventually (i.e. doesn't need to be addressed here, just wanted to share). In particular it would be nice to be closer to the "Add insight to dashboard" modal visually, e.g. 
    - A secondary "Add to dashboard" button instead of the primary "+".
    - "Close" and "Add new insight" buttons in footer.
    - Plain view vs table.

2025-01-02 10:56 UTC, thmsobrmlr commented on frontend/src/scenes/dashboard/AddInsightToDashboardModal.tsx
> +            {/* <p>Add insight to dashboard {dashboard?.name}</p> */}
leftover

2025-01-02 10:56 UTC, thmsobrmlr commented on frontend/src/scenes/saved-insights/AddSavedInsightsToDashboard.tsx
This file seems to contain a lot of duplication from the saved insights page. Can we dry up the code and at least import all the metadata from there?

2025-01-03 23:54 UTC, k11kirky commented on frontend/src/scenes/saved-insights/AddSavedInsightsToDashboard.tsx
Agree  and updated

2025-01-07 11:16 UTC, thmsobrmlr reviewed
Hi @k11kirky, thanks for addressing the feedback! I gave this another look, and pagination still seems a bit broken on my end. For example the page doesn't reset when a filter is changed, is stored in the url although we use kea state and the item count is off when navigating to a second page.

Now I don't want perfect to be the enemy of good and maybe these issues already exist on the original page (I didn't check), but it looks like there is a bunch of code that was just copied over and isn't necessary for the modal either.

I'm thinking we might want to properly generalize the table from the saved insights page or come up with a custom one for the modal. What do you think?

2025-01-08 15:02 UTC, thmsobrmlr approved these changes
Thank you, everything works now ✨

2025-01-08 18:17 UTC, merged