🦔 Fix Svelte Code During Onboarding
PostHog/posthog pull request #27155
Opened 2024-12-26 07:26 UTC by nermalcat69

## Problem

I was setting up posthog for my website saasplates.com which is written in svelte and i noticed this problem so thought i should fix it.

## Changes

Added OnMount as it's the best one and works best when a user visits the site.

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

## How did you test this code?

2024-12-26 15:11 UTC, rafaeelaudibert requested changes
Hey, @nermalcat69! This is great! I agree this is a much better fix - and ChatGPT agrees with the both of us, I'm not the best at Svelte :)

There are two changes we might want here:
- Can you make sure you're importing `onMount`? My understanding is that it's not available by default, correct me if I'm wrong
- Can you by any chance update our Svelte documentation on the website as well? It's fine if you can't get to it, I can always try and update it myself, but I believe you have more knowledge than I have :)

The docs are live here: https://posthog.com/docs/libraries/svelte
Our docs live in here, and it **should** be easy to find where to update it: https://github.com/PostHog/posthog.com

2024-12-26 15:20 UTC, nermalcat69 commented
Sureee, Thanks @rafaeelaudibert i'll get back to you ASAP!

2024-12-26 15:23 UTC, rafaeelaudibert commented
> Sureee, Thanks @rafaeelaudibert i'll get back to you ASAP!

Make sure you're enjoying the end-of-year break as well :). Thank you!

2024-12-26 18:03 UTC, nermalcat69 commented
Review it whenever you get time and thanks for your time 💯

Merry Belated Christmas 😄

2024-12-26 18:07 UTC, nermalcat69 commented
The docs pr: https://github.com/PostHog/posthog.com/pull/10223

2024-12-26 23:11 UTC, rafaeelaudibert approved these changes
🎉

2025-01-15 07:52 UTC, nermalcat69 commented
hey @rafaeelaudibert can you approve the workflows?

2025-01-15 12:47 UTC, merged