feat: [2/n] Adding role_at_organization to the user API
PostHog/posthog pull request #27189
Opened 2024-12-30 19:39 UTC by surbhi-posthog

## Problem

We want to allow the user to read and write the role_at_organization through the user API.

## Changes

This change is dependent on: https://github.com/PostHog/posthog/pull/27113

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

Cloud: yes

## How did you test this code?

In python shell i updated the role_at_organization for my user:

```
user = User.objects.first()
user.role_at_organization = 'engineering'
user.save()
```

I then verified that I can retrieve updated field from a GET endpoint using Postman:
![image](https://github.com/user-attachments/assets/7f02d791-2727-495c-8283-ae530f9d6b47)

I added tests and verified that they passed locally:
`pytest posthog/api/test/test_user.py `

2025-01-06 22:42 UTC, zlwaterfield approved these changes
There will be other places we need to do this like this invite flow. Checkout the `InviteSignupSerializer`.

Since the other PR was merged, feel free to rebase this and make it off master

2025-01-06 22:42 UTC, zlwaterfield requested changes
Sorry didn't mean to approve, can review after the invite one is added!

2025-01-07 14:26 UTC, surbhi-posthog reviewed
I'm not making changes to  `def enter_demo(self, validated_data) ` since I don't think its required for this experiment. Let me know if there are other suggestions here.

2025-01-07 16:24 UTC, surbhi-posthog commented
I've updated both user and signup APIs to read/write role_at_organization. I've also updated tests where relevant.

2025-01-07 16:30 UTC, zlwaterfield approved these changes
Looks good!

2025-01-07 19:04 UTC, merged