feat(periodic-digest): add periodic digest notification setting
PostHog/posthog pull request #27191
Opened 2024-12-30 22:00 UTC by raquelmsmith

## Problem

People need to be able to turn these digests off completely and for specific projects. 

## Changes

Added the notification settings to the user.

👉 _Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review._

## Does this work well for both Cloud and self-hosted?

## How did you test this code?

2025-01-03 15:49 UTC, zlwaterfield requested changes

2025-01-03 15:49 UTC, zlwaterfield commented on frontend/src/scenes/settings/user/UpdateEmailPreferences.tsx
> +                                    <span className="text-muted-alt mr-2">-</span>
Nit: I don't think this `-` looks great. Maybe a real bullet?

2025-01-03 15:49 UTC, zlwaterfield commented on posthog/models/notification_setting.py
> +def should_send_notification(
This isn't a mode so feels odd to be in a new model file. This might work better as a user model method.

2025-01-03 15:49 UTC, zlwaterfield commented on posthog/models/notification_setting.py
> +        if settings.get("all_weekly_digest_disabled", False):
Should this default to true like plugins?

2025-01-03 15:49 UTC, zlwaterfield commented on posthog/models/notification_setting.py
> +            return not project_settings.get(str(team_id), False)
Should this default to true?

2025-01-03 15:49 UTC, zlwaterfield commented on posthog/tasks/periodic_digest.py
> +    pha_client = Client("sTMFPsFhdP1Ssg")
So bad we are hard coding this 😑

2025-01-03 15:49 UTC, zlwaterfield commented on posthog/models/notification_setting.py
> +    Determines if a notification should be sent to a user based on their notification settings.
Maybe just added a comment that `get_members_to_notify` also exists. Also the plugin check is a bit more complex with the org role check as well so maybe isn't needed here.

2025-01-03 15:49 UTC, zlwaterfield commented on posthog/models/notification_setting.py
> +    notification_type: NotificationSetting,
This is a `str` since you're passing in `NotificationSetting.WEEKLY_PROJECT_DIGEST.value` so you can either update this or you can update the value being passed in to be `NotificationSetting.WEEKLY_PROJECT_DIGEST` and the if statement below to do the same.

2025-01-03 22:17 UTC, raquelmsmith commented on posthog/models/notification_setting.py
> +        if settings.get("all_weekly_digest_disabled", False):
No, I want them enabled by default

2025-01-03 22:18 UTC, raquelmsmith commented on posthog/models/notification_setting.py
> +        if settings.get("all_weekly_digest_disabled", False):
Oh but there is another bug here I think, good catch

2025-01-03 22:20 UTC, raquelmsmith commented on posthog/tasks/periodic_digest.py
> +    pha_client = Client("sTMFPsFhdP1Ssg")
I think we hardcode it so that we still get the intel from self-hosted projects. If it were an env var then it'd go elsewhere.

2025-01-03 22:54 UTC, raquelmsmith commented on posthog/models/notification_setting.py
> +    Determines if a notification should be sent to a user based on their notification settings.
I just moved it all to that file directly under that func, it should have been there in the first place

2025-01-04 01:15 UTC, zlwaterfield approved these changes
Nice work on all the changes

2025-01-07 17:18 UTC, merged