Add autofill for posthog props in plugin config
PostHog/posthog pull request #2838
Opened 2020-12-24 13:29 UTC by yakkomajuri

## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

2021-01-12 11:56 UTC, mariusandra requested changes
Hey, some thoughts below regarding this implementation. 

I understand this is needed for some plugins that want to talk to the API (e.g. the github annotations plugin). This will work, though a nicer solution would be to autogenerate and pre-fill this stuff in the plugin-server... and then expose some `api` object that can be called that has the right authentication already pre-filled. That's obviously more work though... :)

2021-01-12 11:56 UTC, mariusandra commented on frontend/src/scenes/plugins/pluginsLogic.ts
> +            },
The default value is an `[]` array of type `PersonalAPIKeyType[]`, yet the loader returns a single `PersonalAPIKeyType`

2021-01-12 11:56 UTC, mariusandra commented on frontend/src/types.ts
> +}
This is a shared type that you can just get with

```
import { PluginConfigSchema } from '@posthog/plugin-scaffold
```

... so we shouldn't re-define it here

2021-01-12 11:56 UTC, mariusandra commented on frontend/src/scenes/plugins/PluginDrawer.tsx
> +            }
I'd move all of this into a logic. That's where `editingPlugin.pluginConfig` comes from after all...

2021-01-19 14:21 UTC, yakkomajuri commented
Finally had a little time to come back to this - all addressed @mariusandra 

Also completely agree it is far from the best solution. I'd love to have access to more if not all of the PostHog API directly in the plugin, but while that's not the case this will just make things easier for people looking to use the GitHub and GitLab plugins (which work on Cloud!)

2021-01-22 14:34 UTC, yakkomajuri commented
This is ready for another go - it mostly just moves the logic but probably could use some selectors etc

2021-01-25 22:32 UTC, mariusandra commented
Hey! Finally had the time to review it. I made quite some changes and cleanup though. 

Playing with this now, I think we need some "secret" or "write-only" field type for plugins, so that this key wouldn't be shown all the time. As in, someone could go into "plugins" and read their boss's personal API key and do something with it. I had a need for it with the github star sync plugin for example.

2021-01-25 22:36 UTC, merged