1269 funnel trends 2
PostHog/posthog pull request #3079
Opened 2021-01-25 19:13 UTC by timgl

## Changes

Adds toggle between funnel viz and funnel trends

todo
- [ ] hide interval in funnel mode
- [ ] feature flag
- [ ] people on click (maybe another pr as this is already big)

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests

2021-01-28 22:22 UTC, EDsCODE reviewed
Initial QA to catch some bugs and see how it worked and testing on a local PG instance doesn't load a graph. Seems to timeout.

WIll follow with in depth backend review

2021-01-28 22:22 UTC, EDsCODE commented on frontend/src/scenes/funnels/funnelVizLogic.js
> +            loadResults: async (refresh = true) => {
TODO here it seems

2021-01-28 22:22 UTC, EDsCODE commented on frontend/src/scenes/insights/Insights.js
> +                                            {showIntervalFilter(allFilters) && (
Could be irrelevant as I can't reproduce it, but when i first loaded this PR, it seemed to lag before the filters were shown which could have to do with the filter logic depending on `allfilters` now

2021-02-01 16:21 UTC, timgl commented
@EDsCODE Can't reproduce your issue with loading the graph, how are you getting into it?

2021-02-02 20:56 UTC, EDsCODE reviewed
QA'd on both clickhouse and pg. Looks good. Few remaining comments

- can't seem to get a single step funnel trend to make sense. If i'm understanding funnel trends properly, I think it should be 100% on the days there are events, but it's always 0. 
- also it would be helpful to bring through the absolute numbers so the percentages have context, otherwise i'm not sure what numbers to be thinking about on the graph

2021-02-02 20:56 UTC, EDsCODE commented on frontend/src/scenes/insights/Insights.js
> +    [`${FUNNEL_VIZ}`]: FUNNEL_LABEL,
don't think the bar chart label was supposed to get tossed

2021-02-03 00:02 UTC, Twixes requested changes
How trends can be enabled here is rather unintuitive, as "Funnel" for the original viz is redundant (the user already knows they're working on a Funnel type insight) and "Line graph" for trends is much too vague. The selector is also confusing because of the inclusion of all the other, completely not applicable options. The choice here should preferably be only between "Steps" and "Trends".
<img width="121" alt="Confusing options" src="https://user-images.githubusercontent.com/4550621/106678096-4c199700-65ba-11eb-8b5f-1dda776073be.png">

The UX of analysis itself is weird due to multiple funnel steps being allowed. Unknown behavior with more than two steps also causes this to be largely incompatible with existing funnels (hard to say between which steps is the trends analysis applied, and you can't select).
To alleviate this, somewhere here could be options "From step" and "To step" (vide e.g. Mixpanel).
<img width="426" alt="Display settings" src="https://user-images.githubusercontent.com/4550621/106677895-e75e3c80-65b9-11eb-8de4-4a454911409c.png">

As a general point regarding funnels, we should not be allowing calculation of single-step funnels, as they can only result in useless and confusing behavior (Re: @EDsCODE notes).

2021-02-03 10:29 UTC, yakkomajuri commented
Flyby comment: If I click 'Linear' and then click on a saved funnel, it loads the funnel normally rather than the trend. I need to switch away and back for it to work. I guess we're expecting a funnel to load before the user flips 'Linear'

2021-02-05 09:01 UTC, timgl commented
Thanks for feedback all (and sorry for delay)

- Have simplified ChartFilter to only show Trends and Steps as options
- Now showing an error if you only have one step with trends
![image](https://user-images.githubusercontent.com/1727427/107012252-12eb4d80-6799-11eb-9bbe-6950013bba26.png)

- Will do the percentages in a different PR. I did add a little explainer of what you're looking at:
![image](https://user-images.githubusercontent.com/1727427/107012222-0830b880-6799-11eb-8325-ebfffeb0607d.png)

@yakkomajuri I think this makes sense? If you've saved a funnel as a Steps funnel you'll want to see it that way the next time?

2021-02-05 09:13 UTC, yakkomajuri commented
@timgl come to think about it that does make sense - gave the deployed env a new spin though and have been getting 500s when switching around different settings (range, steps/trends, period)

[See this link](https://posthog-1269-funnel-tre-uml3u6.herokuapp.com/api/insight/funnel/?insight=FUNNELS&properties=%5B%5D&display=FunnelViz&interval=week&actions=%5B%7B%22id%22%3A16%2C%22math%22%3Anull%2C%22name%22%3A%22Installed%20App%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A15%2C%22math%22%3Anull%2C%22name%22%3A%22Rated%20App%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%7B%22key%22%3A%22plan%22%2C%22type%22%3A%22event%22%2C%22value%22%3A%22premium%22%2C%22operator%22%3Anull%7D%5D%2C%22math_property%22%3Anull%7D%5D&date_from=all)

2021-02-05 10:21 UTC, timgl commented
@yakkomajuri actually looks like those are just redis errors, for some reason it's reaching the max number of clients https://sentry.io/organizations/hiberly-nm/issues/2200733211/?project=5624479&query=is%3Aunresolved#

2021-02-05 13:13 UTC, yakkomajuri commented
Ah yes our deployment envs use a hobby dev redis with a 20 connection limit. We reach this limit super fast - had this problem on the playground at first.

2021-02-05 13:32 UTC, merged