Plugin editor types
PostHog/posthog pull request #4468
Opened 2021-05-25 10:47 UTC by mariusandra

## Changes

- Adds `@posthog/plugin-scaffold` types into the plugin source editor for sweet TypeScript support
- Changes the default plugin to one that encourages discovery (loosely based on @Twixes 's [advanced plugin kit](https://github.com/PostHog/posthog-plugin-advanced-kit/blob/a954ce9cf06274ea6525dc6d7102948072ffb763/src/index.ts#L18))
- This is just the first step though. We should add types for all other exported packages (e.g. aws sdk, plugin contrib, ...) as well.

![2021-05-25 12 43 45](https://user-images.githubusercontent.com/53387/119485268-2970e100-bd57-11eb-8a2a-b2d081e9256b.gif)

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious

2021-05-26 13:49 UTC, Twixes requested changes
There is a problem in that this doesn't build

2021-05-26 13:49 UTC, Twixes commented on frontend/src/scenes/plugins/edit/PluginSource.tsx
> +  config: {},
This should match `defaultConfig`.

2021-06-01 08:44 UTC, mariusandra commented
So, feedback addressed and it builds now. Still some issues with this PR. Not sure if they are blockers or not:

- We only have types for anything imported from `@posthog/plugin-scaffold`. No types for `fetch` or any of the other packages like `aws-sdk` here.
- As an improvement, I'd suggest adding two things to plugin-scaffold: 1) all pinned versions of all packages that plugin authors can import from into `devDependencies`, a build script that copies the types of all those packages into the plugin scaffold package for exporting. The `posthog` would just take these types from inside scaffold, instead of requiring us to install `aws-sdk` and other large things that slow down builds.
- We need to make sure to keep posthog, plugin-server and plugin-scaffold versions in sync. Automatic github actions could help.

2021-06-01 11:06 UTC, Twixes approved these changes
Nice.
As for improvements, I'd say nothing blocking. May be worth creating issue for some e.g. ensuring `plugin-scaffold` is up to date.

2021-06-01 11:19 UTC, merged