Event query class
PostHog/posthog pull request #4649
Opened 2021-06-08 20:52 UTC by EDsCODE

## Changes

*Please describe.*  

Current Problem:
Our query building logic has bubbled into adding many repeated clauses. For example, in our `parse_prop_clause` class, for every person related property, we are adding an `IN` condition that inserts an entire person related subquery (`GET_DISTINCT_IDS_BY_PROPERTY_SQL`)

Solution:
- Create a dedicated class that will format the event query as best as possible given the entity and filter parameters. This class will generate an events query that can be then wrapped by any of the insight queries (trends, funnels, etc.) as they all rely on a subquery on events. 
- The class should guarantee the simplest format of the query so it would solve the problem mentioned above by joining in the persons table once and filtering on persons property in a non-nested manner without extra subquerying.

*If this affects the frontend, include screenshots.*  

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)

2021-06-09 12:51 UTC, buwilliams requested changes
I'm in favor of this class because it just makes sense. It's hard to approve however without some tests. The tests would help show the interface into the class and spot potential issues with it.

2021-06-09 13:42 UTC, EDsCODE commented
Yeah definitely, I didn't integrate in any of the insights yet just wanted to draft and get some feedback

2021-06-10 14:27 UTC, EDsCODE commented
There's a little more cleanup that can be done to make the cohort filtering non-repetitive but this PR is getting big and it's a good starting point to test effectiveness. I've only integrated it into trends volume queries (excluding breakdowns). Will follow-up with complete swap-over with all other insights

2021-06-10 18:15 UTC, buwilliams requested changes

2021-06-10 18:47 UTC, merged