Insights table - New UI
PostHog/posthog pull request #4700
Opened 2021-06-10 20:40 UTC by paolodamico

## Changes

This PR is a solid work in progress.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] Frontend/CSS is usable at 320px (iPhone SE) and decent at 360px (most phones)

2021-06-11 19:18 UTC, alexkim205 commented
I love these new table changes, so excited for when we roll this out!

Quick heads up, there is a bug where when we toggle the compare previous option, only one date is shown in the columns. See `We Dec 31` below

<img width="1110" alt="Screen Shot 2021-06-11 at 12 17 15 PM" src="https://user-images.githubusercontent.com/13460330/121738354-f8aade80-caae-11eb-9857-1f689875ed53.png">

2021-06-11 19:44 UTC, samwinslow approved these changes
Love this! Thank you for taking the reins here — hope some of the CSS I wrote a couple weeks ago was helpful :)

2021-06-14 11:52 UTC, paolodamico commented
Thanks for the reviews! The baseline code you both set up on tooltips and the insight table was indeed super helpful to get this moving quickly.

2021-06-14 12:12 UTC, paolodamico commented
@mariusandra FYI rebased from master post-merge of #4651. Will wait for your review before merging.

2021-06-14 12:12 UTC, mariusandra requested changes
Love the new look and feel, yet some things still to do before it sparks joy :)

1. We could add this table also below the "bar chart > time" view (and another for "bar chart > value"). 

2. This is definitely unexpected (possible reason marked out with an inline comment):
![2021-06-14 13 46 54](https://user-images.githubusercontent.com/53387/121887500-18dcd680-cd17-11eb-8c6f-3c3db1c5f62f.gif)

3. "Sessions" is broken
![2021-06-14 13 49 31](https://user-images.githubusercontent.com/53387/121887725-63f6e980-cd17-11eb-920e-b07856059034.gif)

4. It's a bit weird if I have just one line with a breakdown, I don't see the "event", only the breakdown value:
![image](https://user-images.githubusercontent.com/53387/121889185-3874fe80-cd19-11eb-89e3-ade55954da59.png)
vs multiple:
![image](https://user-images.githubusercontent.com/53387/121889237-475bb100-cd19-11eb-82bc-82dd42a9e9b1.png)

I guess it's fine if this is intentional... if not, might be worth a look. Since the table is infinitely scrollable, it's probably also fine to add more values for clarity/screenshottability.

5. The total/average column is slightly inconsistent and doesn't save its state in the URL. I guess the latter feature's not needed right now, but seeing one thing, sharing to a friend, and then having a different view (see CMD+R in the screencast) is probably not good:
![2021-06-14 14 10 06](https://user-images.githubusercontent.com/53387/121890271-70307600-cd1a-11eb-824d-afef10be2e83.gif)

2021-06-14 12:12 UTC, mariusandra commented on frontend/src/scenes/insights/InsightsTable/InsightsTableV2.tsx
> +                        <>{formatBreakdownLabel(item.breakdown_value, cohorts)}</>
nit q: why the `<>`?

2021-06-14 18:49 UTC, paolodamico commented
Thanks for the review @mariusandra. FYI comments below. If you find anything else let me know and I’ll address in the follow-up PR.
1. 👍 addressed
2. 👍 addressed
3. 👍 addressed
4. This is indeed intended, idea is making it easier to understand what’s going on. One less thing to think about? But might actually be the opposite, happy to change, anyone has any thoughts on this? @kpthatsme
5. Agreed but I won’t implement this right now because we’re already refactoring the logic to store the state in the URL and don’t want to add extra complexity for something so minor (and feature flagged) at this point.

2021-06-14 18:49 UTC, paolodamico commented on frontend/src/lib/utils.tsx
> +    const sorted = input.sort((a, b) => a - b)
Great catch, I think this indeed fixed the bug

2021-06-14 23:12 UTC, kpthatsme commented
On point #4 raised by Marius, I definitely see both sides of it. I don't think it makes a huge difference either way, and given that I think I'd opt to include the event names for consistency and erring on the side of clarity. 

One piece of feedback I did have – I feel like it was better to have the aggregate close to the event name.  I feel like the first thing you want to see on the table is usually the total sum as the chart shows the values over time.

2021-06-15 02:48 UTC, paolodamico commented
Thanks @kpthatsme, makes sense. Re location of aggregate column I actually had it as column 3 on my original mockups, but felt this wasn't very intuitive (following typical patterns), but happy to get push back on this. I'll keep it for now and we can iterate too.

2021-06-15 03:11 UTC, paolodamico commented
Ah cypress acting up again, can't seem to getting running at all. Tests were passing the final minor fixes, so merging based off of that.

2021-06-15 03:11 UTC, merged