Persons modal style updates
PostHog/posthog pull request #5040
Opened 2021-07-08 13:52 UTC by liyiy

## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

<img width="745" alt="Screen Shot 2021-07-07 at 8 21 58 PM" src="https://user-images.githubusercontent.com/25164963/124844550-95ec1c00-df62-11eb-970f-96d020efe02b.png">

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

2021-07-08 13:56 UTC, liyiy commented
@clarkus I kind of just snuck the property details expansion back in there but I don't have the best eye for design, let me know if I can clean up anything around it 😄

2021-07-08 15:50 UTC, paolodamico commented
Wow this is looking amazing so far, great stuff @liyiy !

2021-07-08 18:52 UTC, clarkus requested changes
This is looking great. I can see a few places where things could be aligned with other features. I know you're still working on this, but are you looking for feedback on the other search and filtering options? Are we still allowing for lists to be saved as new cohorts?

**Let's reuse the expand / collapse component from sessions here.** What you have works, but if we can reuse the same components from other areas that would help users build familiarity:
<img width="69" alt="Screen Shot 2021-07-08 at 11 48 13 AM" src="https://user-images.githubusercontent.com/254612/124975020-63820380-dfe2-11eb-9819-b1b33c0ec10d.png">

**Can we make the property list full width?** The column of names is going to contain the greatest amount of variability, so we could just increase the width of that column to fill the available space. What do you think?

2021-07-08 20:13 UTC, liyiy commented
> This is looking great. I can see a few places where things could be aligned with other features. I know you're still working on this, but are you looking for feedback on the other search and filtering options? Are we still allowing for lists to be saved as new cohorts?
> 
> **Let's reuse the expand / collapse component from sessions here.** What you have works, but if we can reuse the same components from other areas that would help users build familiarity:
> <img alt="Screen Shot 2021-07-08 at 11 48 13 AM" width="69" src="https://user-images.githubusercontent.com/254612/124975020-63820380-dfe2-11eb-9819-b1b33c0ec10d.png">
> 
> **Can we make the property list full width?** The column of names is going to contain the greatest amount of variability, so we could just increase the width of that column to fill the available space. What do you think?

Yes (the cohort button was there, just hidden behind a feature flag in my screenshot). I've also updated the expand icon, didn't know we built our own custom one, cool! 

As for the search bar, we're tabling that for now due to some querying complications. For the sessions filter, I haven't looked into that too much yet so that's still a TODO as I'm currently working on the time conversion histogram, perhaps we can come back to that when Alex is back? 

<img width="636" alt="Screen Shot 2021-07-08 at 4 05 25 PM" src="https://user-images.githubusercontent.com/25164963/124983914-94742f80-e006-11eb-98ac-bdf81c2c479f.png">

2021-07-08 21:56 UTC, liyiy commented
Will merge unless I'm missing anything important in this iteration :D

2021-07-09 00:12 UTC, paolodamico approved these changes
lgtm! minor comments, we can iterate from here too!

2021-07-09 00:12 UTC, paolodamico commented on frontend/src/scenes/trends/PersonModal.tsx
> +import Col from 'antd/es/grid/col'
Nit: better to import from `ant` directly

2021-07-09 00:12 UTC, paolodamico commented on frontend/src/scenes/trends/PersonModal.tsx
> +                            {featureFlags['persons-modal-search'] && (
Using hard-coded `persons-modal-search` instead of the declared constant

2021-07-09 13:57 UTC, merged