People modal Refresh button
PostHog/posthog pull request #5537
Opened 2021-08-11 08:21 UTC by Twixes

## Changes

This adds a Refresh button to the people button, which forces recomputation of the list.
![Refresh](https://user-images.githubusercontent.com/4550621/128994220-dee1eadb-2011-45c9-9006-5bf5c6f2a5a9.png)
Resolves #5161, which seems to be caused by stale persons-for-datapoint cache.

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

2021-08-11 08:40 UTC, macobo commented
Is there an issue around this? What problem does this solve? :thinking:

2021-08-11 23:02 UTC, alexkim205 commented on frontend/src/scenes/insights/Insights.tsx
> +function ComputationTimeAndRefresh({
Nice refactor! Would it be possible to move this into a separate component file? I feel like this would be a super reusable component.

2021-08-11 23:04 UTC, alexkim205 requested changes

2021-08-11 23:04 UTC, alexkim205 commented on frontend/src/scenes/insights/Insights.tsx
> +function ComputationTimeAndRefresh({
Nice refactor! Would it be possible to move this into a separate component file? I feel like this would be a super reusable component.

2021-08-11 23:07 UTC, alexkim205 commented
LGTM! Side note, if you set the target branch to `insights-refresh-improved` it might be easier to track and review changes specific to people modal stuff

2021-08-11 23:59 UTC, alexkim205 commented on frontend/src/scenes/insights/Insights.tsx
> +    })
Do you want this to run once on mount? If so, you might need a [] dependency here

2021-08-12 07:58 UTC, macobo commented
Created a linked issue: https://github.com/PostHog/posthog/issues/5559

Not sure this is actually needed. My worry is that we're subtly making the UX worse by adding more toggles - we will likely add other links to the same place as well to sessions. :)

2021-08-13 00:02 UTC, Twixes commented
Indeed since we've decided to ditch the count with #5560, there is definitely less of a need for this (really imperfect) refresh logic.  I think this modal still could be cleaned up a bit, but that may be better done in a fresh PR. :)

2021-08-13 00:02 UTC, closed without merging