Sort dashboards based on pins
PostHog/posthog pull request #5588
Opened 2021-08-13 17:06 UTC by paolodamico

## Changes

Fixes #5457 

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

2021-08-13 17:46 UTC, alexkim205 commented
Just spot tested it, but the sorting doesn't seem to be working

<img width="1131" alt="Screen Shot 2021-08-13 at 10 45 30 AM" src="https://user-images.githubusercontent.com/13460330/129399011-1a85fe00-de0b-4590-8688-035743a6ee62.png">

2021-08-13 17:46 UTC, alexkim205 requested changes

2021-08-13 17:46 UTC, alexkim205 commented on frontend/src/scenes/dashboard/Dashboards.tsx
> +                    const intValue = +a.pinned + +b.pinned
I'm kind of confused, what does this +(boolean) syntax do?

2021-08-16 14:09 UTC, paolodamico commented
Just cleaned up the code a bit to make it more clear, and tested again and seems to be working. Can you review again @alexkim205 please?

<img width="489" alt="" src="https://user-images.githubusercontent.com/5864173/129576972-5a6570fc-3300-4e08-b5a2-5032639ce6e6.png">

2021-08-18 14:12 UTC, paolodamico commented
Ping @alexkim205 and/or @kpthatsme

2021-08-18 16:40 UTC, alexkim205 commented
Looks great!

2021-08-18 16:41 UTC, alexkim205 approved these changes

2021-08-18 16:41 UTC, merged