Custom step range picker for funnels time conversion
PostHog/posthog pull request #5704
Opened 2021-08-24 04:35 UTC by alexkim205

## Changes

Fixes #5701.

![Screen Shot 2021-08-23 at 9 29 06 PM](https://user-images.githubusercontent.com/13460330/130556238-e77a8bac-204a-4e2e-8202-918ab745b1ad.png)

- [x] Give user ability to choose step ranges > 1 step long
- [x] Refactor step selector out into separate component
- [x] Consolidate data source for `histogramSteps` into `filters` in logic

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

2021-08-24 10:37 UTC, Twixes submitted a review, later dismissed
Thank you for tackling this!
I have 2 major comments:
<img width="306" alt="Screen Shot 2021-08-24 at 12 28 44" src="https://user-images.githubusercontent.com/4550621/130601473-0eb4de04-b9ff-4337-a98d-5a521162397d.png">
1. This is pretty awkwardly placed and reduces area available to the chart below. I think the Options pane may be the most natural place for these controls. Also happy to hear from @clarkus regarding UX.
2. The feature should be available for both Time to convert and Historical trends (the API is identical).

2021-08-24 17:32 UTC, alexkim205 commented
Thanks for taking a look :) agreed options might be the best place for this

2021-08-24 17:41 UTC, alexkim205 commented
How's this look? 

![Screen Shot 2021-08-24 at 10 41 15 AM](https://user-images.githubusercontent.com/13460330/130664004-d30c5575-360a-43e9-bb06-58b66853e9bb.png)

2021-08-24 18:42 UTC, clarkus commented
Agree it's best placed under options for now.

2021-08-25 04:46 UTC, liyiy commented
When I change it from days to hours or weeks or minutes nothing happens :o 

https://user-images.githubusercontent.com/25164963/130728097-ddbda800-b65e-45cf-b6f8-561d92dc135e.mov

2021-08-25 10:13 UTC, mariusandra commented
When looking at the interface, I have a hard time understanding what "between step 1 and step 3" does, and what kind of side effects it has.

I understand what is "14 days conversion window", but if I have 4 steps and set "14 days between steps 1 and 2", what happens to the other steps? They can take forever? 

I'd also reorder the two options. The one about conversion window should probably be first, as I imagine that's the one that'll be interacted with more.

2021-08-25 10:21 UTC, neilkakkar commented
Wait, wait, what? (Marius's comment made me look more carefully into this, so thanks for this). This is pretty confusing, agree!

We aren't changing the conversion window sizes here, or modifying it between steps - this isn't possible.

What we're changing is the `Steps` option on the Time to Convert graph only. So, this shouldn't show up for historical trends, nor for the ordinary funnel.

 I think this should stay as far away from the conversion window option as possible, since it's unrelated.

2021-08-25 10:54 UTC, neilkakkar commented
To add a bit to the confusion, just looked at how they're used in HistoricalTrends vs TimeToConvert, and the semantics differ slightly:

1. In Trends, looking between Step X and Step Y means you're looking at the **conversion rate** between those two steps.
2. In TimeToConvert, looking between Step X and Step Y means you're looking at the **time taken to convert** between those two steps.

While this can be obvious to someone entrenched in the 2 features and their usage, seems non-trivial to infer for newbies.

This might impact how we display the copy^

2021-08-25 11:09 UTC, Twixes requested changes, later dismissed

2021-08-25 11:09 UTC, Twixes commented on frontend/src/scenes/funnels/funnelLogic.ts
> +        changeHistogramStep: (funnel_from_step?: number, funnel_to_step?: number) => ({
Would be good to also remove the `histogram` characterization in this logic to something more general, maybe `changeStepRange` here for instance.

2021-08-25 11:09 UTC, Twixes commented on frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelStepsPicker.tsx
> +            Between
I think @mariusandra and @neilkakkar have a point. How about renaming this from just "Between X and Y" to:
- for Time to convert: "Conversion time from Step X to Step Y",
- for Historical trends: "Conversion rate from Step X to Step Y"?

2021-08-25 15:28 UTC, alexkim205 commented
> When I change it from days to hours or weeks or minutes nothing happens :o

You'll have to unfocus from the input to trigger a change. We decided triggering onChange would be expensive.

> I think this should stay as far away from the conversion window option as possible, since it's unrelated. Thoughts?

I can see how people would think that conversion windows and step ranges are interrelated if they're located in the same space, and we definitely don't want to cause any confusion. Maybe it'd make more sense to move this into the steps tab?

2021-08-25 15:58 UTC, liyiy commented
> > When I change it from days to hours or weeks or minutes nothing happens :o
> 
> Hmm I believe you'll have to unfocus from the input to trigger a change bc we saw that triggering onChange would be expensive. Does that work?

I feel like I wouldn't know to do that as a user though, can we make it unfocus automatically? And add a breakpoint if the user is changing the options too quickly

2021-08-25 16:33 UTC, alexkim205 commented
> I feel like I wouldn't know to do that as a user though, can we make it unfocus automatically? And add a breakpoint if the user is changing the options too quickly

Good idea! 👍

2021-08-25 17:10 UTC, alexkim205 commented
Pinging @Twixes and @neilkakkar for rereview. Updated copy and added a tooltip. Open to suggestions for rewording

Time to convert

![Screen Shot 2021-08-25 at 10 10 05 AM](https://user-images.githubusercontent.com/13460330/130834946-5bbdedf4-8e79-4a4e-b791-cf0b5edc84f1.png)

Trends

![Screen Shot 2021-08-25 at 10 11 48 AM](https://user-images.githubusercontent.com/13460330/130835208-4d86411c-210a-4174-b8d1-e9babd595d9a.png)

2021-08-25 18:39 UTC, clarkus commented
I caught up with @alexkim205 via slack to talk through this issue. I gave poor guidance earlier as I misunderstood the problem being solved. 

I think we should change placement. Each scenario is specific to the graph type selected, and it directly modifies the metric in the header (conversion time or conversion rate) based on the steps configured. We can place a configuration control there or just build the step selectors into the header for the visualization. In the example below you can see repeated headers for each scenario: conversion steps, time to convert, and historical trends. Thoughts?

<img width="606" alt="Screen Shot 2021-08-25 at 11 39 24 AM" src="https://user-images.githubusercontent.com/254612/130846831-12509432-073c-4780-a7a4-6f56266d3439.png">

https://www.figma.com/file/9yWtngNb1AIuf6KmXaEPJA/App-doodles?node-id=1139%3A135838

2021-08-25 18:53 UTC, neilkakkar commented
@alexkim205 the recent change is better, but I really do love Chris's suggestion! (so far away from conversion window, yay 😂) - makes the most sense to me.

2021-08-25 21:03 UTC, alexkim205 commented
Done!

Steps

![Screen Shot 2021-08-25 at 2 05 41 PM](https://user-images.githubusercontent.com/13460330/130864683-88fe331c-2bd7-4737-ae17-b731dd129367.png)


Convert

![Screen Shot 2021-08-25 at 2 03 02 PM](https://user-images.githubusercontent.com/13460330/130864361-27598190-99c7-4796-9ec3-6a16a5c15889.png)

Trends

![Screen Shot 2021-08-25 at 2 02 57 PM](https://user-images.githubusercontent.com/13460330/130864359-5f845abe-6bd3-491a-bdab-6f58800be910.png)

tagging @mariusandra and @neilkakkar and @clarkus for rereview

2021-08-27 05:11 UTC, merged