Optimize UI around session recordings
PostHog/posthog pull request #5770
Opened 2021-08-29 11:01 UTC by Twixes

## Changes

Small fixes for session recordings UI (for instance links in `Tooltip`s don't work, because tooltip content can't be clicked, the hoverable element must be a link instead).

| Before | After |
| --- | --- |
| <img width="309" alt="Screen Shot 2021-08-28 at 01 55 18" src="https://user-images.githubusercontent.com/4550621/131248021-ba532d7d-3ff2-470e-95c0-a80da2fef505.png"> | <img width="311" alt="Screen Shot 2021-08-28 at 01 49 49" src="https://user-images.githubusercontent.com/4550621/131248019-93f15bf0-eb31-4561-a5e4-454db885e759.png"> |
| <img width="462" alt="Screen Shot 2021-08-28 at 01 36 24" src="https://user-images.githubusercontent.com/4550621/131248023-58e660d7-c9ae-4483-8d77-7930954ca8ea.png"> | <img width="457" alt="Screen Shot 2021-08-28 at 01 36 46" src="https://user-images.githubusercontent.com/4550621/131248022-867de882-ad5c-4d4e-88ac-0d29c9c0a0f9.png"> |

2021-08-29 12:10 UTC, mariusandra requested changes
Changes make sense, yet found some issues:

1. The button gets cut off in the table:
![image](https://user-images.githubusercontent.com/53387/131249814-c6a2f350-b985-4063-b8a5-a48cb79be2e2.png)
![image](https://user-images.githubusercontent.com/53387/131249821-137cceb3-9bf0-46aa-9864-98b807cdd320.png)

Especially visible with smaller resolutions:

![image](https://user-images.githubusercontent.com/53387/131249827-06859c61-b192-4701-bc15-99d0151c0655.png)

2. The `ms` probably isn't useful to this precision:

![image](https://user-images.githubusercontent.com/53387/131249845-f521f82a-342e-459e-9911-20ff35a19382.png)

3. (inline comment) that we should scroll to the session recordings part of the project page when clicking the link.

2021-08-29 12:10 UTC, mariusandra commented on frontend/src/scenes/sessions/SessionsView.tsx
> +                            <Link to={urls.projectSettings()}>
Would be nice to link directly to the tab. Not sure if it should be:
```jsx
  <Link to={`${urls.projectSettings()}#session-recording`}>
```

... or `urls.projectSettings({ anchor: 'session-recording' })` 

... or any other variation.

2021-08-29 16:47 UTC, Twixes commented
Sure @mariusandra

2021-08-29 16:48 UTC, Twixes commented
Sure @mariusandra

2021-09-07 07:21 UTC, paolodamico approved these changes
lgtm!

2021-09-07 07:21 UTC, paolodamico commented on frontend/src/lib/utils.tsx
> +    s = Math.round(s)
Maybe worth adding a test that properly captures this?

2021-09-07 17:41 UTC, merged