Show potentially relevant session recordings in funnel persons modal
PostHog/posthog pull request #5771
Opened 2021-08-29 11:04 UTC by Twixes

## Changes

Resolves #5664.

<img width="618" alt="Screen Shot 2021-08-29 at 00 50 40" src="https://user-images.githubusercontent.com/4550621/131248158-6c046075-c1ec-4241-8d91-e541566a23bc.png">

## Checklist

- [x] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

2021-09-07 09:08 UTC, Twixes commented
Ready for review.

This way of correlating relevant recordings is pretty naive, but it works really efficiently. It shows all recordings that were captured between `beginning of funnel time frame` and `end of funnel time frame extended with the funnel window`.

I also attempted ways to correlate this with funnel events, but
1. it's easy to miss a tangentially related, but still relevant recording showing what the user was doing,
2. it's much more expensive to do a `JOIN` like that.

2021-09-07 09:50 UTC, macobo commented
> This way of correlating relevant recordings is pretty naive, but it works really efficiently. It shows all recordings that were captured between beginning of funnel time frame and end of funnel time frame extended with the funnel window.

While your rationale makes sense, this causes some issues:
1. We're not able to "jump to $TIME" in session recording that's most relevant
2. There'll be a lot of extra noise in the recording

Also re JOIN being expensive - AFAIK we'll be doing something extremely similar in paths to find where users went after $STEP. Will quickly sync with @neilkakkar or @EDsCODE whether the approach is applicable here.

Will take a proper look after that discussion. Given you've switched teams it might make sense to merge this even if we'll be changing the approach and doing a follow-up.

2021-09-07 18:07 UTC, Twixes commented
I think this is much better than what we've got currently (nothing), but I agree with both points.
They're both kind of tricky to resolve though:
1. As for jumping to relevant time:
	- A single session recording can easily contain multiple funnel steps being performed – do we show that session recording multiple times with different timestamps, or just take the user to the first timestamp?
2. As for only showing the most relevant recordings:
	- This is pretty straightforward for step completions, since we can only show recordings where the relevant step was performed. What about dropoffs though – how do we show the recording relevant to why the user _didn't_ perform the step? In this case only a human can judge whether the recording is noise in the context or not.

2021-09-08 05:34 UTC, paolodamico reviewed
UX-wise & frontend code look good. I'm not the right person to review the CH changes, though I agree with the discussion here, this is better than nothing, yet I don't think it's the right approach just yet. Users will not receive value if we don't show them the relevant part of the recordings easily. Particularly the entire funnel timeframe might be comprised of many sessions & long sessions too, it could be hard to find where users dropped off. Perhaps this will be easier when we combine with quant analysis too.

2021-09-09 07:00 UTC, macobo requested changes

2021-09-09 07:00 UTC, macobo commented on frontend/src/scenes/sessions/SessionRecordingsButton.tsx
> +    if (location.pathname.startsWith('/sessions')) {
Pretty sure this breaks navigation on persons page.

2021-11-02 07:31 UTC, closed without merging