New paths UI sankey card
PostHog/posthog pull request #6066
Opened 2021-09-22 05:18 UTC by liyiy

## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

<img width="1083" alt="Screen Shot 2021-09-22 at 1 18 03 AM" src="https://user-images.githubusercontent.com/25164963/134287302-3228b6ba-0d6f-467f-a4ce-8ba2758824e1.png">

## Checklist

- [ ] All querysets/queries filter by Organization, by Team, and by User
- [ ] Django backend tests
- [ ] Jest frontend tests
- [ ] Cypress end-to-end tests
- [ ] Migrations are safe to run at scale (e.g. PostHog Cloud) – present proof if not obvious
- [ ] New/changed UI is decent on smartphones (viewport width around 360px)

2021-09-23 22:01 UTC, clarkus requested changes
Nice progress! Is there anything we can do to make the path item metrics feel more connected to the path name / url? There's some space and rounding separating the items in the examples. It almost feels like a sub-menu, and really it's a fully revealed state of a single item. 

<img width="371" alt="Screen Shot 2021-09-23 at 2 56 48 PM" src="https://user-images.githubusercontent.com/254612/134589558-8bd137dd-40bc-4ae9-ab8f-cfce947dc871.png">

2021-09-23 22:20 UTC, liyiy commented
> Nice progress! Is there anything we can do to make the path item metrics feel more connected to the path name / url? There's some space and rounding separating the items in the examples. It almost feels like a sub-menu, and really it's a fully revealed state of a single item.
> 
> <img alt="Screen Shot 2021-09-23 at 2 56 48 PM" width="371" src="https://user-images.githubusercontent.com/254612/134589558-8bd137dd-40bc-4ae9-ab8f-cfce947dc871.png">

I can try to make it cleaner around the edges but I'm using antd's dropdown for this to avoid writing a whole dropdown component 😅 that's why it looks like a sub menu heh

2021-09-24 06:49 UTC, liyiy commented
update: did some finagling with the border radii and margin tops, is this better? @clarkus 

<img width="301" alt="Screen Shot 2021-09-24 at 2 48 04 AM" src="https://user-images.githubusercontent.com/25164963/134630780-1a5d4e76-ee51-491c-a1c1-900bc2c822aa.png">

2021-09-24 18:11 UTC, clarkus commented
> update: did some finagling with the border radii and margin tops, is this better? @clarkus
> 
> <img alt="Screen Shot 2021-09-24 at 2 48 04 AM" width="301" src="https://user-images.githubusercontent.com/25164963/134630780-1a5d4e76-ee51-491c-a1c1-900bc2c822aa.png">

Yeah it's definitely better! If the path item name portion were the same color as the rest of the card and had the same borders, I think it'd match the design completely.

2021-09-26 08:28 UTC, liyiy commented
yes!! good catch @clarkus <img width="276" alt="Screen Shot 2021-09-26 at 4 26 34 AM" src="https://user-images.githubusercontent.com/25164963/134800032-3d1db19c-67ae-4c8e-ab0f-6e49fedcda9c.png">

2021-09-27 13:29 UTC, EDsCODE requested changes
1. Dropdown onHover shows a cursor but clicking doesn't do anything
2. The path cards at the end are top aligned whereas all the other cards are centered vertically on the node
<img width="386" alt="Screen Shot 2021-09-27 at 9 23 21 AM" src="https://user-images.githubusercontent.com/13127476/134917347-23829caf-9752-4f59-bc47-d05cd01a02f9.png">

Follow up design considerations from my testing:
1. would be helpful to squeeze some number onto the cards (without dropping down)
2. I think we need a bit more in the label "average conversion time" that explains what the time actually is. Right now I can't tell if it's the average time it took people to get to the node or leave the node or spent at the node

Overall, the path cards look awesome. They're already way more fun to use and look better than the simple labels we had before

2021-09-27 13:29 UTC, EDsCODE commented on frontend/src/scenes/paths/Paths.js
> +                {!paths.error &&
Maybe move these inline styles to the new scss file you created?

2021-09-27 15:13 UTC, liyiy commented
@EDsCODE  The path cards at the end are top aligned otherwise they'll intersect each other, do you have suggestions for alternatives?

2021-09-27 16:52 UTC, clarkus commented
> @EDsCODE The path cards at the end are top aligned otherwise they'll intersect each other, do you have suggestions for alternatives?

This is pretty directly related to the number of steps shown consecutively and the width of the path item labels. In the designs, when they're not hovered, we just show the path. This keeps the card succinct and reduces the risk over conflicting with other cards. That doesn't prevent this happening entirely, but it does a lot to mitigate it. 

One option I tried in the most recent version was increasing the width of the item columns such that there is always sufficient space to show a card that flows left-to-right. This means that cards should always have space to the right.

<img width="487" alt="Screen Shot 2021-09-27 at 9 50 52 AM" src="https://user-images.githubusercontent.com/254612/134951979-ba12e070-6c06-4fb8-957a-380f5d7ee9b3.png">

2021-09-27 23:12 UTC, EDsCODE commented
> @EDsCODE The path cards at the end are top aligned otherwise they'll intersect each other, do you have suggestions for alternatives?

That makes sense. My first reaction was just that it seemed so far pushed to the top but I think the spacing against the other cards makes sense so should be fine.

2021-09-27 23:15 UTC, EDsCODE requested changes
Can you actually feature flag this even though changes should work with current api? I just want us to go through testing phases and make sure there aren't crazy edge cases we're missing that might come with prod

After the feature flag, should be good to merge

2021-09-28 14:50 UTC, EDsCODE approved these changes
good to go! will merge with it behind a feature flag

2021-09-28 14:50 UTC, merged