Password reset - API
PostHog/posthog pull request #6335
Opened 2021-10-08 13:22 UTC by paolodamico

## Changes

Implements the backend for password reset via API. This PR includes only additive changes and does not change/break any previously existing functionality (i.e. **safe to merge**; we'll remove legacy stuff in #6177).
- Implements endpoints to request a password reset, validate a reset token & use a reset token.

In addition, this PR improves the UI of emails **a little bit** (initial steps of https://github.com/PostHog/product-internal/issues/186). CC @corywatilo

**Gmail** (note the logo change is not reflected in these screenshots)
    <img width="1076" alt="" src="https://user-images.githubusercontent.com/5864173/137066610-cc77994e-4a39-40e0-a716-bf0f11c52b6c.png">
**Another client**
    <img width="674" alt="" src="https://user-images.githubusercontent.com/5864173/137066598-251ff0d2-7507-4f5f-bfbb-79f78b149844.png">

## How did you test this code?
- Full Django functional tests included.
- Manual email tests through Mailgun (tested with and without social auth enabled).

2021-10-13 04:29 UTC, corywatilo commented
Glanced quickly at the code but looks like the old code but slightly updated to use the background color from the new design, correct?

So we'll punt on replacing with the new HTML from #186 for now?

(Note that the new font declaration won't do anything until we reference the webfont and fix the CORS issue.)

2021-10-13 04:49 UTC, paolodamico commented
So I do hope to get soon to implement your full design but it's not the goal of this PR, just decided to do some very quick changes so that it starts looking a little bit more on-brand already (background, buttons, ...). I'm aware of the font thing, I'll fix the CORS and add it for Cloud users only, at least it might work for users who happen to have it installed.

2021-10-13 09:57 UTC, Twixes requested changes

2021-10-14 21:47 UTC, Twixes approved these changes
All good

2021-10-15 06:33 UTC, merged