Adding tooltips to insights
PostHog/posthog pull request #6405
Opened 2021-10-13 10:39 UTC by marcushyett-ph

## Changes

Added tooltip for paths

## How did you test this code?

TBD - Waiting for branch deploy

2021-10-13 17:36 UTC, liyiy approved these changes

2021-10-14 09:11 UTC, mariusandra requested changes
The `Tooltip` component loses the `data-attr`, as the antd tooltip it passes it do does nothing with it. This causes an E2E test to fail, since it can't find an element with this data attribute to click

2021-10-14 09:16 UTC, marcushyett-ph commented
Aha - good to know... so essentially the tooltips weren't there on purpose - so the E2E tests would work?

2021-10-14 09:17 UTC, closed without merging

2021-10-14 09:30 UTC, mariusandra commented
Well, no, we can surely fix it if we want to :). Just the `data-attr` needs to end up in the final rendered HTML. Just a matter of wiring things differently. 

I would have just fixed it, but you know, wouldn't want to step on any toes or anything :D.