Saved insight fixes 2
PostHog/posthog pull request #6674
Opened 2021-10-26 23:15 UTC by mariusandra

## Changes

- Another small set of improvements for https://github.com/PostHog/posthog/issues/6513#issuecomment-951870899
- Adds icons to the table
- Fixes the select box
- Also fixes a tiny alignment bug with the "save" button top-right border on the edit insight page...

Before:
![2021-10-27 01 14 26](https://user-images.githubusercontent.com/53387/138974157-d8476fb4-4a62-4135-a57f-e1cbd8ad6ec9.gif)

After:
![2021-10-27 01 08 35](https://user-images.githubusercontent.com/53387/138973990-36fa170d-83b6-49f6-b3ab-c4da6eccf249.gif)

## How did you test this code?

*Please describe.*

2021-10-26 23:28 UTC, clarkus requested changes
Seeing some rendering issues. I tried clearing my cache and rebuilding but it's persisting for me. 
 
<img width="239" alt="Screen Shot 2021-10-26 at 4 24 33 PM" src="https://user-images.githubusercontent.com/254612/138975063-02c2afed-c472-4f1a-8c4f-563fd4ece330.png">
<img width="335" alt="Screen Shot 2021-10-26 at 4 24 46 PM" src="https://user-images.githubusercontent.com/254612/138975748-0c9eb90d-5abb-4f00-958c-9170fde7ccc7.png">

It also looks like keyword filters aren't matching against insight ID. In this case I'm trying to find the insight with ID 31 but it doesn't return as a match. Also the wrong empty state is shown - it's matching for an empty set instead of a non-matching result. 

<img width="1530" alt="Screen Shot 2021-10-26 at 4 29 25 PM" src="https://user-images.githubusercontent.com/254612/138975503-783b97c2-e34a-4a78-8f21-5b06395d4ffe.png">
<img width="1544" alt="Screen Shot 2021-10-26 at 4 29 18 PM" src="https://user-images.githubusercontent.com/254612/138975507-cd6d59da-6c3e-45e5-8fe6-9ec405e79b72.png">

2021-10-27 10:01 UTC, mariusandra commented
Ended up tagging a bunch of things into this PR:

- Fixed the trend type select box
- Improved error states (not by *too* much)
- Filtering insights by typing in the ID
- Keep 2 cards next to each other in the card view, unless the resolution is >1600px
- Add profile "picture" to users
- Improve the column sorting (it's still very different from other tables, and the asc/desc up/down mapping is flipped for the two columns because it felt more natural... but good enough?)
- Improve funnels on tiny dashboard items/cards --> each step now has a 200px min width and we add a scrollbar if needed. 

Ready for another look.

2021-10-27 20:11 UTC, clarkus approved these changes

2021-10-28 06:05 UTC, mariusandra commented
@Twixes any objections for getting this in?

2021-10-28 09:53 UTC, Twixes requested changes
Only noticed two UI oddities:
- Looks like insights that have no insight type set (meaning: implicitly trends) have no icon.
  Besides, for insights that do have an icon it's not obvious which insight type each icon signifies. The buried legend is the "Type" menu, but maybe we could just have a tooltip/title on the icon for info on hover?
  <img width="155" alt="Screen Shot 2021-10-28 at 11 41 07" src="https://user-images.githubusercontent.com/4550621/139231363-5e4d2e10-1b6b-4dcb-b666-419290b85a85.png">
- I thought these should be Sentence case?
  <img width="171" alt="Screen Shot 2021-10-28 at 11 38 37" src="https://user-images.githubusercontent.com/4550621/139231370-36f00b78-7517-49d7-bad1-502a8df008e7.png">

2021-10-28 10:35 UTC, mariusandra commented
I went for the quick fixes now :)

2021-10-28 15:10 UTC, mariusandra commented
@Twixes good to merge?

2021-10-28 15:12 UTC, Twixes approved these changes

2021-10-28 16:05 UTC, merged