Resizable columns - Insights table
PostHog/posthog pull request #6965
Opened 2021-11-08 22:12 UTC by paolodamico

## Changes

This PR converts the insights table into a table with resizable columns so the user can adjust the width at will for large series. Feedback from users.

![image](https://user-images.githubusercontent.com/5864173/140826428-a116cfd7-fb3f-4989-9aeb-e8aa7286ca77.gif)

## How did you test this code?

See recording above. Manually tested by creating a trends insight with "Current URL" as a breakdown.

2021-11-08 22:13 UTC, paolodamico commented on frontend/src/lib/components/ResizableTable/ResizableTable.tsx
> +export interface ResizableColumnType<RecordType> extends Omit<ColumnType<RecordType>, 'width'> {
`width` property is set dynamically internally, therefore it shouldn't be passed.

2021-11-08 22:14 UTC, paolodamico commented on frontend/src/scenes/insights/InsightsTable/InsightsTable.tsx
> +            widthConstraints: [50, 50],
No better way to restrict sizing

2021-11-08 22:14 UTC, paolodamico commented on frontend/src/scenes/insights/InsightsTable/InsightsTable.tsx
> +                defaultWidth: 150,
`150px` for some reason translates into `96px` on initial rendering. Any other value causes the columns to jump.

2021-11-08 22:16 UTC, paolodamico commented
This implementation is still buggy because the underlying `ResizableTable` has a few issues. Opted to leave this for now as we have plans to improve tables anyways. One big issue is with the last column, and having a right-fixed column. There are in addition some other issues noted within the code. @mariusandra not sure if we plan to pick up tables soon (in which case this would be pretty useful) and if not we can close this.

**Issue with last column:**
![image](https://user-images.githubusercontent.com/5864173/140826428-a116cfd7-fb3f-4989-9aeb-e8aa7286ca77.gif)

2021-11-09 08:51 UTC, mariusandra requested changes
Since the resizable tables are inherently broken, this PR now breaks the insight tables:

![2021-11-09 09 47 34](https://user-images.githubusercontent.com/53387/140892002-07b8acf9-a91a-4eb4-89bd-a9baeaf1765a.gif)

(always, always enables fixed scrollbars on macos if you're a frontend developer)

The screencast is after a full reload of the page. What was previously a table, is now a table with two scrollbars.

Personally I'd remove all resizable tables on all pages, since they:
1. Make the entire page really slow (check how long the "feature flags" page renders if switching between sidebar items... and the flags have already been loaded)
2. Have all the unresolved UX bugs.

There's a task - https://github.com/PostHog/posthog/issues/5361 - which is in scope for @Twixes for this sprint, however with a focus on design first, and all the complicated resizing behaviour only if there's time.

2021-11-09 11:32 UTC, paolodamico commented
Will close this for now, if we do add resizing column support and this is helpful, we can reopen.

2021-11-09 11:32 UTC, closed without merging