Update person version on person updates and send value to Kafka
PostHog/posthog pull request #6982
Opened 2021-11-09 10:54 UTC by yakkomajuri

## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

We don't currently do anything with this version value in CH (because the schema change hasn't been merged), but we should start producing the messages with it before merging the change.

## How did you test this code?

*Please describe.*

2021-11-09 11:22 UTC, yakkomajuri commented
The failing tests are flakes that #6907 fixes

2021-11-10 04:27 UTC, tiina303 requested changes
Test failures seem legit.

2021-11-10 04:55 UTC, tiina303 commented on plugin-server/src/utils/db/db.ts
> +        }
We have this check in the process-event side already & I'm not sure why, but it's bypassed when we're using kafka producer i.e. Clickhouse DB.
We always pass the full person's properties to this function from `updatePersonProperties` function at least.

2021-11-10 05:52 UTC, tiina303 commented
https://github.com/PostHog/posthog/pull/7007 <= you can merge this into here if that looks good for fixing tests + making us also not send ClickHouse update if nothing changed about props

2021-11-10 14:01 UTC, tiina303 commented
Please rebase on master first as I landed the props being added during person creation, which changes version values in tests.

2021-11-12 16:28 UTC, tiina303 approved these changes
@yakkomajuri I updated it based on merge needs + tests would love to get this in before the release leaving to you for final review

2021-11-16 10:12 UTC, merged