Remove the unused function and type from migrations
PostHog/posthog pull request #7035
Opened 2021-11-10 15:26 UTC by tiina303

## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

## How did you test this code?

*Please describe.*

2021-11-11 11:59 UTC, yakkomajuri requested changes
let's get rid of the tests too

2021-11-12 09:46 UTC, yakkomajuri commented
Are there any other migrations we might also want to clear? Otherwise lgtm

2021-11-18 00:12 UTC, tiina303 commented
Nope you already did that in the past
```
> grep -r "update_person_props" posthog/migrations
posthog/migrations/0177_path_cleaning_filters.py:        ("posthog", "0176_update_person_props_function"),
posthog/migrations/0173_should_update_person_props_function.py:    # Superseded by 0175_should_update_person_props
posthog/migrations/0174_organization_slug.py:        ("posthog", "0173_should_update_person_props_function"),
posthog/migrations/0176_update_person_props_function.py:        ("posthog", "0175_should_update_person_props_function"),

> grep -r "person_property_update" posthog/migrations
```

2021-11-18 14:58 UTC, yakkomajuri approved these changes

2021-11-23 18:58 UTC, merged