Private project handling
PostHog/posthog pull request #7142
Opened 2021-11-15 20:51 UTC by Twixes

## Changes

Resolves #6896 and a few other problems:
- lemonade UI looking awkward when there's no current project and/or when project creation is unavailable for the user
- user that lost their access to the current project not being redirected away
- org/project creation modals not being helpful

## How did you test this code?

Manually by bringing the edge cases described above into the instance.

2021-11-16 08:45 UTC, mariusandra requested changes
One comment, and there's an infinite loop in jest.

2021-11-16 08:45 UTC, mariusandra commented on frontend/src/scenes/App.tsx
> -    const { sceneConfig } = useValues(sceneLogic({ scenes: appScenes }))
If you don't need the var here, can you replace this with `useMountedLogic(sceneLogic({ scenes }))` instead, as the `<LoadedSceneLogics />` below also uses sceneLogic, before AppScene. It'd be an endless game of cat and mouse, so just `useMountedValues` at the highest level will save the day.

2021-11-16 16:32 UTC, Twixes commented
Fixed. Also added some console logging – it generally doesn't make sense in production, but in this case it feels better to have this hint for various debugging purposes (in logic tests but also to know where the redirects are coming from in prod) – though I don't feel strongly about this.

2021-11-17 09:36 UTC, mariusandra approved these changes

2021-11-17 09:37 UTC, merged