Fix all time no results
PostHog/posthog pull request #725
Opened 2020-05-05 17:16 UTC by timgl

## Changes

- [Fixes this Sentry error](https://sentry.io/organizations/posthog/issues/1648291886/?project=1899813&referrer=slack)

## Checklist
- [x] All querysets/queries filter by Team (if applicable)
- [x] Backend tests (if applicable)

2020-05-06 18:23 UTC, EDsCODE reviewed
All time is returning nothing for me (on demo instance). 
Extra info that might help:
I printed values to take a quick took and `aggregates` returns the right values right before entering `_group_events_to_date`. I think there's a mismatch on datetime from python and timestamps from database. It also may have grouping by exact timestamp instead of a range. The date objects in aggregates before entering `_group_events_to_date` are datetimes on midnight of day

2020-05-11 11:15 UTC, timgl commented
@EDsCODE Fixed! Thanks for digging

2020-05-11 18:28 UTC, EDsCODE requested changes
All time looks good. Stickiness isn't working because it requires `date_to` and `date_from` but the null case for `date_to` is being handled inside `_aggregate_by_interval` and stickiness doesn't have any handling

2020-05-11 18:28 UTC, EDsCODE commented on posthog/api/action.py
> +
Handle the case where `if not filter.date_to` here and setting `filter._date_to=now().isoformat()`

2020-05-11 18:28 UTC, EDsCODE commented on posthog/api/action.py
>              date_to=filter.date_to if filter.date_to else now(),
And remove this now()

2020-05-13 10:44 UTC, timgl commented
Thanks for debugging this! Added a test case too and should be fixed now

2020-05-13 14:07 UTC, EDsCODE approved these changes

2020-05-13 14:07 UTC, merged