Funnels simple mode
PostHog/posthog pull request #7252
Opened 2021-11-22 02:56 UTC by paolodamico

## Changes

**🎯The goal of this PR is increasing funnel Discoveries, particularly in new users.** We'll run an A/B test for this.

- Closes #6776. Implements a "simple mode" for funnels in which advanced options are grouped and hidden. The rationale is that a simpler interface will incentivize more funnel creation, and advanced users will find advanced options anyways. 
- Updates general styling to match latest designs by @clarkus.
- Updates style of internal test users filter.
- Removes legacy unused styles.

**Postgres version**
<img width="399" alt="" src="https://user-images.githubusercontent.com/5864173/142794227-dc938dfa-3886-4ec7-8a2e-8f0fb827c935.png">

**Horizontal version - collapsed - no advanced options applied**
<img width="1176" alt="" src="https://user-images.githubusercontent.com/5864173/142794255-1dc95837-3e93-4ffe-9e47-dd2649a0ce54.png">

**Vertical version - collapsed - no advanced options applied**
<img width="426" alt="" src="https://user-images.githubusercontent.com/5864173/142794276-929a579c-3f80-4748-9a25-a114d7ee2352.png">

**Vertical version - expanded**
<img width="427" alt="" src="https://user-images.githubusercontent.com/5864173/142794296-ddc9621d-1d15-4907-9904-59f22c0349a5.png">

**Vertical version - collapsed - advanced options applied**
<img width="413" alt="" src="https://user-images.githubusercontent.com/5864173/142794311-1ff7f466-0a86-463b-86f8-1f642b8d7cb6.png">

## How did you test this code?
- All permutations of the following configurations: Postgres vs. Clickhouse; `funnel-simple-mode` on vs. off, `5730-funnel-horizontal-ui` on vs. off, groups functionality enabled vs. disabled.

2021-11-22 18:45 UTC, alexkim205 requested changes
Wow I love this new updated look and the separation of simple/advanced options. It makes it so much easier to get started with funnels. 

Some feedback

- It looks like the stylistic changes are also grouped in with the `funnel-simple-mode` feature. If it's not too much of a hassle I would prefer the style update to be separated out so that but up to you to decide :) 
- Opening and closing advanced options will trigger another loadResults call. Usually unnoticeable but definitely slows things down when queries are expensive.
- It feels like there should be an option to reset advanced options, especially when their "dirtiness" is exposed in a "X options applied tag"
- Some style things

<img width="347" alt="Screen Shot 2021-11-22 at 10 42 49 AM" src="https://user-images.githubusercontent.com/13460330/142917473-03c6bc63-fcac-4fd7-ab15-3a7754c2feff.png">

- Nit: removing '(s)'s in aggregation dropdown

<img width="629" alt="Screen Shot 2021-11-22 at 10 43 20 AM" src="https://user-images.githubusercontent.com/13460330/142917511-50103993-2f2d-4803-becf-8f4743b63586.png">

2021-11-22 18:45 UTC, alexkim205 commented on frontend/src/scenes/insights/AggregationSelect.tsx
> +export function AggregationSelect({ aggregationGroupTypeIndex, onChange, style }: AggregationSelectProps): JSX.Element {
Nit: can we use a classname or even better a boolean property here?

2021-11-22 18:45 UTC, alexkim205 commented on frontend/src/scenes/insights/InsightTabs/FunnelTab/FunnelTab.tsx
> +    return featureFlags[FEATURE_FLAGS.FUNNEL_SIMPLE_MODE] ? <FunnelTabWithSimpleMode /> : <FunnelTabOld />
Nice I love that you separated this for easy cleanup

2021-11-22 23:02 UTC, clarkus requested changes
![image](https://user-images.githubusercontent.com/254612/142946996-377f9a6b-f3db-4779-a82a-4f385cb7c76d.png)
- While the filter labeling is super obvious, I do think it biases filters over the actual graph series parameters. Can we use a badge instead?

- The aggregation option for non-postgres feels over-sized. Can we instead size it to the character width of the currently selected option? If not that, then the character width of the most verbose option?
- We previously had descriptions inline to help describe each section of the query options. Are those being removed or changed purposefully? 
- I feel like the conversion window could be more prominent or possibly not an advanced option. It feels as critical as aggregation method to me. 
- We call the section "advanced options" and we summarize its state with "1 setting applied". I don't know that we need to name what's applied specifically or that it's applied. Really we need to summarize things that are different than the default values. A badge or some other simple count should be enough to call out that something is applied.

2021-11-24 06:12 UTC, paolodamico commented
Thanks for the review @alexkim205 & @clarkus, ready for another look. Some pushback/clarification on a few items, everything else is addressed.

Re @alexkim205 
- _"Nit: removing '(s)'s in aggregation dropdown"_
    - Unrelated to this PR, worth checking with @macobo as this may affect other parts of the app.
- Opted for keeping the stylistic changes here for now. To avoid duplication of work, if we move forward in a couple of weeks, it won't matter anymore, and if we don't we can then rollback these changes and import the relevant style changes.

----------

Re @clarkus 
- _"The aggregation option for non-postgres feels over-sized."_
    - No changes were introduced in this PR, but agree with the premise. Given that it affects multiple insights, would you mind opening a separate PR, pls?
- "We previously had descriptions inline to help describe each section of the query options. Are those being removed or changed purposefully?"   
    - No changes to that introduced in this PR. We have those descriptions behind the info icon. Happy to change it if it makes sense.

----------

**Multiple adjustments**
<img width="430" alt="" src="https://user-images.githubusercontent.com/5864173/143183940-523c133c-84f5-4cae-a40c-7d5af6746cf9.png">

**Simplified badge**
<img width="398" alt="" src="https://user-images.githubusercontent.com/5864173/143183945-0a71d5a2-67c4-420a-bc8e-20acffaaa51e.png">

2021-11-24 17:55 UTC, alexkim205 commented on frontend/src/scenes/funnels/funnelLogic.ts
> +    urlToAction: ({ actions }) => ({
If we keep `funnel_advanced` in filters and don't persist it into a separate value, we might be able to get rid of a lot of boilerplate here.

2021-11-24 18:01 UTC, clarkus approved these changes

2021-11-24 18:01 UTC, alexkim205 commented on frontend/src/scenes/funnels/funnelLogic.ts
> +            if (funnel_advanced) {
If none of the advanced options are on (aka advancedOptionsUsedCount === 0) we should set advanced mode to false.

2021-11-24 18:47 UTC, alexkim205 commented
Overall looking pretty good! I removed some boilerplate in favor of moving `funnel_advanced` into filters and added a logic test for not triggering a load result on toggling that menu. There're still a few style bugs that already existed before this PR, so I'll leave that up to your discretion.

<img width="298" alt="Screen Shot 2021-11-24 at 10 16 47 AM" src="https://user-images.githubusercontent.com/13460330/143296024-44aa986e-5ee4-4166-a52d-076bc38ea688.png">

<img width="240" alt="Screen Shot 2021-11-24 at 10 39 31 AM" src="https://user-images.githubusercontent.com/13460330/143296019-00c180ff-0f76-4b13-80cb-a0ac0b5186be.png">

2021-11-24 18:49 UTC, alexkim205 approved these changes

2021-11-24 23:11 UTC, merged