Proposal: _always_ include default released feature flags
PostHog/posthog pull request #7356
Opened 2021-11-25 11:09 UTC by macobo

This caused pain for a client who we did a beta release for.

2021-11-25 12:02 UTC, Twixes reviewed
As far as I understand, this will also fully release these `PERSISTED_FEATURE_FLAGS` on Cloud (which currently uses the special env var value `0`), and out of 5 these flags, only 1 is currently fully rolled out on Cloud. So I'm 100% for this _if_ we do it in a way that keeps `PERSISTED_FEATURE_FLAGS` empty on Cloud to avoid disrupting things for now.

2021-11-25 12:02 UTC, Twixes commented on posthog/settings.py
>  PERSISTED_FEATURE_FLAGS = []
I suppose the latter `PERSISTED_FEATURE_FLAGS` shouldn't be here?

2021-11-25 12:11 UTC, macobo commented
Why are we releasing features on self-hosted and not in cloud? :thinking: 

All of this kind of sounds like our feature release process is smelly and needs simplifications to keep the release and cloud released features in sync. After all, we want the logic if "something is released" to be a simple question.

The solution can be this PR or it can be deleting feature flags in a more timely manner. /shrug

2021-11-25 12:37 UTC, mariusandra approved these changes
LGTM. [We've had issues](https://github.com/PostHog/posthog/pull/5296#issuecomment-899125238) with this already before.

2021-11-25 13:54 UTC, Twixes commented
I totally agree @macobo Just that we should do the full simplification separately from this PR. CC @paolodamico

2021-11-25 14:19 UTC, Twixes requested changes
Also just noticed that, as noted in `# These flags will be force-enabled on the frontend **and OVERRIDE all** flags from decide`, as-is this change causes all flags that aren't in `PERSISTED_FEATURE_FLAGS` to be disabled, which force-disables all our WIP or Cloud-only features (e.g. groups, the announcement bar).

2021-11-25 18:24 UTC, paolodamico approved these changes
I don't think this is the right approach. Here are some arguments as to the benefits of cloud and self-hosted **not** being in sync:
1. On Cloud we run A/B tests aside from phased roll-outs to test improvements and no regressions. We would essentially lose our ability to A/B test by doing this.
2. Cloud is often used as a sandbox for phased roll-outs, we test new features / improvements with a % of Cloud users, and if they work we include them in a self-hosted release. The reason for this is that we can correct course in Cloud much faster if something goes wrong.
3. We have other functionality on Cloud that relies on FF for logic (e.g. in-product announcements)

-------

Based on what prompted this (i.e. the problem we're trying to solve is for self-hosted users being able to easily enable alpha/beta features for their instance), I've pushed a counter proposal. We solve the problem that prompted this, but not what @mariusandra brings up, we will still need to have good stewardship in FF management.

-------

Finally, the proposal also fixes for using FFs in development.

2021-11-26 07:49 UTC, macobo commented
:+1: from me

2021-11-29 14:06 UTC, merged