Closes #714 allow multiple filters with same key
PostHog/posthog pull request #738
Opened 2020-05-08 20:10 UTC by timgl

## Changes

- Add Property model in array form: `[{key, value, operator, type}]`
  - Type will become important for #737
- Make PropertyFilters use new format
- Backwards compatibility with the old format
- Added filtering by person property in backend (not yet in frontend to avoid PR getting too big)

## Checklist
- [x] All querysets/queries filter by Team (if applicable)
- [x] Backend tests (if applicable)

2020-05-11 12:39 UTC, mariusandra commented
I'm getting an error saving and then loading funnels with this.

```
AttributeError at /api/funnel/1/ --> 'list' object has no attribute 'items'
  File "/Users/marius/Projects/PostHog/[posthog/posthog/utils.py](https://github.com/PostHog/posthog/blob/d4df76250632f84b830b76b0ec48caaafbed568f/posthog/utils.py#L76)", line 76, in properties_to_Q
    for key, value in properties.items():
```

2020-05-11 12:46 UTC, mariusandra requested changes
So like I wrote in the comment, funnels are broken.

Since funnels store these properties as JSON, all the old funnels still work, but if I save any of them, they will break.

2020-05-11 15:26 UTC, timgl commented
Should be good now 👍

2020-05-11 15:40 UTC, mariusandra approved these changes
Works much better with funnels! I just found this issue now when I removed filters:
![screencast 2020-05-11 17-37-42](https://user-images.githubusercontent.com/53387/81580827-38842b80-93ae-11ea-9ae4-b825d5d41712.gif)
It would save and work fine, just it would show two "new filter" boxes

2020-05-12 10:42 UTC, timgl commented
good catch, that's fixed now

2020-05-12 12:59 UTC, merged