772 add  is true and is false
PostHog/posthog pull request #777
Opened 2020-05-15 11:33 UTC by timgl

## Changes
Needs #760 to be merged first.

- Correctly allow filtering of true/false properties
- Allow filtering whether a property is set or not

## Checklist
- [x] All querysets/queries filter by Team (if applicable)
- [x] Backend tests (if applicable)

2020-05-19 15:37 UTC, EDsCODE requested changes
Person filtering works well. Few thoughts on reviewing/QA'ing is set

3 findings: 

1. There's a NIT with the symbol below.
2. Empty value that can be filtered out
<img width="782" alt="Screen Shot 2020-05-19 at 11 31 56 AM" src="https://user-images.githubusercontent.com/13127476/82346456-7db6e780-99c4-11ea-9b57-10f690391a29.png">
3. Bug where the true/false values don't change if you try using different filter
<img width="844" alt="Screen Shot 2020-05-19 at 11 36 48 AM" src="https://user-images.githubusercontent.com/13127476/82346999-2107fc80-99c5-11ea-9c30-09442cb1f3bc.png">

- Add a filter that would expect boolean values (ex: `is_demo`). 
- Apply is set as the filter operator.
- Change the filter property to something else and change the oeprator type away from isset
- The value options will still be true/false

I noted below where the fix can happen

2020-05-19 15:37 UTC, EDsCODE commented on frontend/src/lib/components/PropertyFilters/PropertyValue.js
>      }
componentWillReceiveProps can solve the missing values issue here

2020-05-19 15:37 UTC, EDsCODE commented on frontend/src/lib/components/PropertyFilters/PropertyValue.js
> +        if (this.props.operator !== 'is_set') {
This is only checking during initialization, but the operator can change while the component is still mounted and the options won't be refreshed

2020-05-19 18:06 UTC, timgl commented on frontend/src/lib/utils.js
> +    is_set: '! is set',
Yeah much prefer that

2020-05-20 11:20 UTC, timgl commented
@EDsCODE Fixed all comments, and also fixed cohorts and funnels (both were broken with person properties)

2020-05-20 14:14 UTC, EDsCODE approved these changes

2020-05-20 16:03 UTC, merged