Make the EventsTable poll less
PostHog/posthog pull request #7860
Opened 2021-12-31 23:54 UTC by pauldambra

## Changes

Includes two changes

1) always give the `eventsTableLogic` a key to avoid having two copies running and both polling
2) listens to the page visibility change event and pause polling when the page is hidden

### logics polling before

<img width="588" alt="Screenshot 2021-12-31 at 23 32 42" src="https://user-images.githubusercontent.com/984817/147841051-402a15de-6491-4dba-a361-a0ac390fc290.png">

### logics polling after

<img width="578" alt="Screenshot 2021-12-31 at 22 32 23" src="https://user-images.githubusercontent.com/984817/147841058-87b26924-97b8-46a0-851c-c75ead80a724.png">

### new behaviour

![events-polling](https://user-images.githubusercontent.com/984817/147841238-4ccea2f3-507a-4ec4-9592-5ba4b7cea584.gif)

## How did you test this code?

Adding unit tests for changes.

Also running the site locally and opening developer tools network view in a separate window. Watch that the events table is polling, and then minimise the browser or switch tabs and see that the event table stops polling

2022-01-03 18:06 UTC, Twixes requested changes
Good improvement, but behavior is wonky with `afterMount`!

2022-01-04 11:21 UTC, neilkakkar commented on frontend/src/scenes/events/EventsTable.tsx
> +    }, [])
Not sure if similar enough, but I built a visibilitySensor a while back for something else: https://github.com/PostHog/posthog/blob/master/frontend/src/lib/components/VisibilitySensor/VisibilitySensor.tsx#L1

Perhaps you can reuse it here?

2022-01-05 05:31 UTC, pauldambra commented on frontend/src/scenes/events/EventsTable.tsx
> +    }, [])
If I'm reading that correctly the `VisibilitySensor` is whether a given element is within the viewport. Whereas the `usePageVisibility` is whether the browser tab/page is currently visible

2022-01-05 10:50 UTC, neilkakkar commented on frontend/src/scenes/events/EventsTable.tsx
> +    }, [])
Ah, my bad! Makes sense

2022-01-05 12:06 UTC, Twixes approved these changes
Works perfect now! Only issue is something (erm #7855) merged a few minutes ago caused merge conflicts…

2022-01-05 13:51 UTC, pauldambra commented
@Twixes couple of small changes on confirming that #7855 and this work together

@macobo FYI we've overlapped - I've checked that the Actions page doesn't poll and my pausing still work now merged together. 

It's tempting to refactor the naming and overlap between `disableActions` and `setPollingActive`. But I'd suggest we do that as a follow-up (if at all)

![after-merge](https://user-images.githubusercontent.com/984817/148228424-9222d2d5-3865-48e3-bc97-9299f0f1b55c.gif)

2022-01-06 10:58 UTC, Twixes approved these changes
All good after merge

2022-01-06 10:58 UTC, merged