Default bar chart yesterday
PostHog/posthog pull request #7931
Opened 2022-01-06 18:47 UTC by paolodamico

## Changes

- Whenever selecting yesterday or today as the date range filters and not viewing hourly stuff, we default to showing the insight as a bar chart instead of a linear chart (this is because as the line chart is a single data point, there's no line to create and the result looks blank).
- We also disable the linear option when you have these settings.

## How did you test this code?
- Navigating through the different intervals and date ranges.
- Made sure linear was only disabled when applicable.

2022-01-10 12:40 UTC, mariusandra requested changes
If I read this right, after this PR you:

1. See a line chart for 7 days
2. Click "yesterday"
3. See a bar chart for yesterday
4. Click "last 7 days"
5. See a bar chart for the last 7 days

This will work I guess, but I think the automatic change in the chart type will be unexpected to the users.

Instead could we treat the "linear chart with just one time unit" as a separate case and e.g. do the switch to the bar chart in React at the last moment, not by overriding the filter?

2022-01-10 12:40 UTC, mariusandra commented on frontend/src/scenes/insights/utils/cleanFilters.ts
> -        return cleanFilters({ insight: InsightType.TRENDS })
This is an unrelated change... It might be good to keep this "legacy" check around as well... Maybe 🤷

2022-01-10 20:29 UTC, EDsCODE commented
Would push back on automatic switching. Maybe if there's only one point we could display the point in the center rather than off to the side. This would make it very clear there's relevant data for that one timeframe

2022-01-15 00:34 UTC, paolodamico commented
While I do think there's value in switching the visualization options automatically when it makes sense (but make it clear for the user, and maybe give them a one-click option to revert), I agree we can tackle this particular problem in a different way (following what @EDsCODE suggested of having the point in the middle I would still paint the line, just with slope 0). Opening an issue for this.

2022-01-15 00:34 UTC, closed without merging