Dashboard edit mode
PostHog/posthog pull request #7937
Opened 2022-01-06 22:09 UTC by paolodamico

## Changes

From a [user suggestion](https://posthog.slack.com/archives/C02SSBZQ0RE/p1641418537014600), we get rid of the edit toast in dashboards and instead signal edit mode with the wobliness of items (like iOS). The toast doesn't seem consistent with the rest of the app anymore. 

<img width="1189" alt="" src="https://user-images.githubusercontent.com/5864173/148459163-1a1bca72-f21f-4d62-b6e8-ff974cd374ae.png">

## How did you test this code?
- Open dashboard, type `e`.

2022-01-06 22:32 UTC, clarkus requested changes
I don't think we should do this. While it is learnable and established for iOS operating systems, it isn't universally meaningful or approachable. While the toast isn't optimal either, it is more obvious. Dashboard editing is in need of updates, so we should track this as a problem in https://github.com/PostHog/posthog/issues/7517.

2022-01-06 23:38 UTC, clarkus commented
There are some in-progress ideas for editing dashboard layouts at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=6342:63028#137918205. This moves way from an edit mode and instead reuses the inline-editing patterns from insights. Instead dashboard items can have their layout edited - this triggers and alternate mode where they can be resized horizontally or be dragged to another row, or to a position within the same row. There is a real constraint with the viewport width and the number of items in each row. For narrower viewports, we would wrap dashboard items to mitigate the need to scroll horizontally. When the dashboard item is wider than the available viewport area, the user would still need to scroll horizontally to see the full item.

2022-01-07 00:03 UTC, paolodamico commented
Deferring to you @clarkus, if you already have this covered in the new dashboards layout and you don't think this is an improvement while that's in progress, we can close this.

2022-01-07 00:03 UTC, closed without merging

2022-01-07 00:30 UTC, clarkus commented
To be clear, I just don't think it's enough on it's own to be obvious. It could be a good change to help reinforce which items are editable, but we still need some means of communicating those different states and confirming when things are successfully changed. I'm going to track it as part of the dashboard changes for sure.