Redesigned person page
PostHog/posthog pull request #7988
Opened 2022-01-11 19:08 UTC by Twixes

## Changes

Implements new person page layout based on a [design](https://github.com/PostHog/posthog/issues/7776#issuecomment-996906613) by @clarkus. Closes #7928.

![2022-01-11 19 56 34](https://user-images.githubusercontent.com/4550621/149005589-ab48f2e3-8a7a-4b2f-9403-72a3df6c617f.gif)

Also added a person 404 page instead of the confusing eternal loading screen that shows up now.

<img width="399" alt="Screen Shot 2022-01-11 at 19 55 36" src="https://user-images.githubusercontent.com/4550621/149005601-0f31eea2-e590-4992-9e75-ea2520ca175a.png">

2022-01-12 09:19 UTC, macobo requested changes
We should keep the groups page design in sync with person page. In this case we're diverging these two pages due to an oversight - please keep this feature in mind going forward!

2022-01-12 23:58 UTC, clarkus commented
Somewhat related https://github.com/PostHog/posthog/issues/8011

2022-01-17 15:58 UTC, Twixes commented
Good point @macobo. Reworked the group page too. See person + group flow:
![2022-01-17 16 53 17](https://user-images.githubusercontent.com/4550621/149802094-feef2d8e-8448-44af-8f50-d4754f1b40dd.gif)

2022-01-17 19:10 UTC, macobo approved these changes
Took a look code-wise! Good job, the changes are easy to follow :)

2022-01-17 19:10 UTC, macobo commented on frontend/src/scenes/groups/groupLogic.ts
> +                    name: groupDisplayId(groupKey, groupData?.group_properties || {}),
Great catch :)

2022-01-18 14:42 UTC, paolodamico approved these changes
Seeing @macobo reviewed the code, I did a UX review. Some minor improvements but nothing blocking.

1. The alignment of the button to remove props seems strange, I would consider putting at the right most place of the entire table.
<img width="493" alt="Screen Shot 2022-01-18 at 8 36 38 AM" src="https://user-images.githubusercontent.com/5864173/149958008-908e634d-0a23-42a5-a89d-2f73ab0e0cb8.png">
2. Update copy for empty state on recordings (e.g. "This user doesn't have any recordings yet. Old recordings are removed after X weeks from your account.")
3. Cohorts list doesn't get recalculated unless I reload the page. I added a cohort that matched a user, went back to the user page and the cohort didn't show up.

2022-01-18 17:55 UTC, clarkus commented
Agree that actions should be in the right most column. We use trashcan icons for removal / delete actions, not `x`. Typically I have been reserving `x` icons for clearing state / removing temporary things in a non-destructive way.

2022-01-18 19:46 UTC, Twixes commented
Good points! This is properties now:
![Person properties](https://user-images.githubusercontent.com/4550621/150003024-8edeac17-f7f1-416e-86c9-1b97ba153606.png)
Only used a slightly different empty recordings message as I _think_ they're not deletable on ClickHouse currently @paolodamico.

2022-01-18 20:24 UTC, merged