Fix selecting filters
PostHog/posthog pull request #844
Opened 2020-05-25 19:42 UTC by timgl

## Changes

- Previously, if you selected a filter on the /trends page without touching the entities, it would just go blank and you'd have to reselect $pageview event

## Checklist
- [x] All querysets/queries filter by Team (if applicable)
- [x] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

2020-05-26 12:24 UTC, mariusandra commented
Unfortunately this breaks the back button. I can have a crack at this if you like.

![screencast 2020-05-26 14-23-25](https://user-images.githubusercontent.com/53387/82900271-8d05da00-9f5c-11ea-862b-7a3f51c80a5a.gif)

Aside: It might be wise to have some cypress tests that check the back/forward buttons are working as well.

2020-05-26 12:25 UTC, mariusandra requested changes
...

2020-05-26 12:29 UTC, mariusandra commented
To add a bit of context, on the Trends page, the state is synced differently from other pages (e.g. actions/events). Here the state is always written to and read from the URL, allowing different parts of the page (e.g. property filters and trends logic) to interact with each other through that. Adding the `onChange` callback breaks this contract.

2020-05-26 19:35 UTC, timgl commented
Thanks for catching that! I've fixed it in urlToAction, though what's weird is `BreakdownFilter` etc  do use onChange, any idea why?

2020-05-28 10:22 UTC, timgl commented
@mariusandra Bump ;)

2020-06-01 14:07 UTC, mariusandra approved these changes

2020-06-01 14:08 UTC, mariusandra commented
LGTM

2020-06-01 14:08 UTC, merged