fix optimize table timeout on 0002
PostHog/posthog pull request #8520
Opened 2022-02-09 13:09 UTC by yakkomajuri

## Changes

*Please describe.*  
*If this affects the frontend, include screenshots.*  

OPTIMIZE TABLE times out for larger customers. 

## How did you test this code?

*Please describe.*

2022-02-09 19:47 UTC, tiina303 reviewed
as discussed lets make default timeout configurable

2022-02-15 16:28 UTC, tiina303 requested changes

2022-02-15 16:28 UTC, tiina303 commented on posthog/async_migrations/definition.py
> +        timeout_seconds: int = getattr(config, "ASYNC_MIGRATIONS_DEFAULT_TIMEOUT"),
change it above too :55

2022-02-15 16:28 UTC, tiina303 commented on posthog/async_migrations/migrations/0002_events_sample_by.py
> +            sync_execute(
we're missing query ID here too + any other future changes there, so instead add additional_setting or sth like that to `execute_op_clickhouse` and use that fn here too.

2022-02-15 16:28 UTC, tiina303 commented on posthog/async_migrations/migrations/0002_events_sample_by.py
> +            AsyncMigrationOperation.simple_op(database=AnalyticsDBMS.CLICKHOUSE, fn=optimize_table_fn, rollback=""),
This isn't `simple_op` anymore & add something as `debug_context` too, I just landed that PR.
```suggestion
            AsyncMigrationOperation(fn=optimize_table_fn),
```

2022-02-15 18:32 UTC, yakkomajuri commented
I think we should try catch this damn thing actually

2022-02-16 22:32 UTC, tiina303 approved these changes

2022-02-17 15:25 UTC, merged