Dashboard creation modal
PostHog/posthog pull request #8581
Opened 2022-02-14 15:33 UTC by Twixes

## Changes

Dashboard creation reimplemented as a modal instead of a drawer, based on [design in Figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7397%3A36520).
| Before | After |
| --- | --- |
| ![Zrzut ekranu 2022-02-14 o 16 22 23](https://user-images.githubusercontent.com/4550621/153894191-7976523a-cb9e-405d-97fc-b56d2a239207.png) | ![Zrzut ekranu 2022-02-14 o 16 33 24](https://user-images.githubusercontent.com/4550621/153894443-fc09becc-674a-43b4-ace1-a8dd0251b378.png) |

## How did you test this code?

This is covered by Cypress tests.

2022-02-14 17:03 UTC, pauldambra approved these changes

2022-02-14 20:25 UTC, clarkus requested changes
The `*` pattern for indicating required fields is contrary to those we've been using elsewhere. We should indicate optional fields, and establish that all fields are required unless indicated otherwise. In this context, descriptions and tags are optional, but all other fields are required. 

<img width="731" alt="Screen Shot 2022-02-14 at 12 24 34 PM" src="https://user-images.githubusercontent.com/254612/153940672-0ccfcf38-d162-4207-b365-5f91536c342f.png">

2022-02-15 00:31 UTC, Twixes commented
Good point @clarkus, I actually thought this'd be somewhat complex to achieve but after looking into it a bit more turned out to be trivial.
<img width="505" alt="Screen Shot" src="https://user-images.githubusercontent.com/4550621/153969762-28abbc65-dd93-4701-a9e8-6f71dc9e08f3.png">

2022-02-15 00:32 UTC, clarkus approved these changes

2022-02-15 01:05 UTC, merged

2022-02-15 09:45 UTC, pauldambra commented
The empty dashboard commit intrigued me

https://app.posthog.com/insights/kb65zZYV#filters=%7B%22insight%22%3A%22TRENDS%22%2C%22interval%22%3A%22day%22%2C%22display%22%3A%22ActionsBarValue%22%2C%22actions%22%3A%5B%7B%22id%22%3A%2214890%22%2C%22name%22%3A%22select%20empty%20dashboard%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%2C%7B%22id%22%3A%2214891%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22name%22%3A%22Select%20Deafult%20Dashboard%22%7D%5D%2C%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%2C%22filter_test_accounts%22%3Atrue%2C%22new_entity%22%3A%5B%5D%2C%22date_from%22%3A%22-90d%22%2C%22date_to%22%3Anull%7D

Looks like more people select empty dashboard than default dashboard 🤔