Add recordings table for homepage
PostHog/posthog pull request #8775
Opened 2022-02-28 23:26 UTC by rcmarron

## Changes

Adds recording table to the homepage. (Homepage is behind ff `project-homepage`)

The bulk of this is adding a prop that disables filtering on the recording list.

*Stay up-to-date with our [coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

*Briefly describe the steps you took.*

2022-03-01 17:54 UTC, alexkim205 requested changes

2022-03-01 17:54 UTC, alexkim205 commented on frontend/src/scenes/project-homepage/ProjectHomepage.tsx
I think we need to export a scene object here

2022-03-01 17:54 UTC, alexkim205 commented on frontend/src/scenes/session-recordings/SessionPlayerDrawer.tsx
> +                        <ArrowLeftOutlined /> Back
Nice I like the generalization here. Thought this was too specific in the first place.

2022-03-01 17:54 UTC, alexkim205 commented on frontend/src/scenes/session-recordings/sessionRecordingsTableLogic.ts
> +    key: (props) => props.personUUID || props.tableLocation || 'global',
Can this align with the pageKey defined in the component?

2022-03-01 17:54 UTC, alexkim205 commented on frontend/src/scenes/session-recordings/sessionRecordingsTableLogic.ts
> +            console.log(props, Object.keys(values.filterQueryParams).length === 0)
leftovers

2022-03-24 11:32 UTC, EDsCODE commented
Follow up:

- Make the empty table more encouraging to users who might not have recordings enabled. 
- Allow people to remove that module if it's useless to them

2022-04-26 17:28 UTC, closed without merging