Remove instance settings from sidebar
PostHog/posthog pull request #8790
Opened 2022-03-01 17:19 UTC by paolodamico

## Changes

Addresses #8749. Removes "Instance status and settings" from sidebar and keeps settings in the site popover per design.

<img width="354" alt="" src="https://user-images.githubusercontent.com/5864173/156216924-70bbc193-72f5-43b6-96ba-86f31dd8a1d6.png">

**With tooltip:**
<img width="364" alt="" src="https://user-images.githubusercontent.com/5864173/156216938-6b2fea4b-19be-404e-9171-99c3f6beaafa.png">

## How did you test this code?
Not applicable.

2022-03-01 17:22 UTC, clarkus requested changes
This doesn't match the solution designed. The idea was to show org and project settings via the icons, but there was a secondary prominent link to the instance settings. 

![Utility navigation](https://user-images.githubusercontent.com/254612/156217382-670318f3-8a31-489d-8fe9-6ce72fae80d9.png)
 
https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7768%3A39486

2022-03-01 19:10 UTC, paolodamico commented
@clarkus I was trying to follow the patterns of the other elements. The design is missing the other elements that we have in that section (instance version & license information), do we still want to include the other menu item there? Are you open for feedback on the design?

2022-03-01 19:42 UTC, clarkus commented
> @clarkus I was trying to follow the patterns of the other elements. The design is missing the other elements that we have in that section (instance version & license information), do we still want to include the other menu item there? Are you open for feedback on the design?

It's literally the big blue instance settings link at the bottom. That other stuff is conditionally shown and the asset I linked isn't representative of all possible states. The problem that's been communicated to me is discoverability, which is why I'm suggesting this change for this specific issue.

2022-03-01 20:02 UTC, clarkus commented
I updated the navigation diagrams to include all the states in case that helps unblock this change. The instance settings are more prominent here because this is the only place we link to them. The other settings are repeated in various places or can be accessed via multiple paths.

![user   utility menu diagram](https://user-images.githubusercontent.com/254612/156240125-9a2b668e-6744-4260-bde2-af3472fdb311.png)

https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7807%3A47508

2022-03-02 00:40 UTC, paolodamico commented
> It's literally the big blue instance settings link at the bottom. That other stuff is conditionally shown and the asset I linked isn't representative of all possible states. The problem that's been communicated to me is discoverability, which is why I'm suggesting this change for this specific issue.

Chris, I've updated to match the blue link at the bottom. However I think the way you provided feedback above and in the PR could be more constructive and mindful of other perspectives. Not entirely sure if my points above were at all considered. Happy to chat sync if it helps.


<img width="351" alt="" src="https://user-images.githubusercontent.com/5864173/156272230-ed1dc848-e0de-4105-a8ae-696a1e804248.png">

2022-03-02 01:10 UTC, clarkus commented
Thanks for updating. Apologies if my comments didn't feel constructive. I was trying to be clear, not aggressive. This is a great example of why looping in a designer for a review on UI changes can save us iterations in the future. Given a clear problem, we can speak factually and objectively about whether a problem is adequately solved or not. I appreciate you making these short term changes. Longer term we will clean this area up as it's somewhat becoming an instance management menu.

2022-03-02 04:32 UTC, clarkus commented
Is the "instance status" link adjacent to the system status necessary? It's technically an accessibility concern when we link to the same asset multiple times using inconsistent labels. Could that link adjacent to the system status actually point to http://status.posthog.com/? If not, can we remove it and only show the big bold discoverable "instance settings" link at the bottom? I just don't think we need both links in this context.

2022-03-02 14:18 UTC, tiina303 approved these changes
LGTM

2022-03-02 14:58 UTC, Twixes requested changes
All for this, but this introduces some UI inconsistencies in `SitePopover` (like "Invite members" and "Instance settings" behaving differently)

2022-03-02 14:58 UTC, Twixes commented on frontend/src/layout/navigation/TopBar/SitePopover.tsx
> +                <Link
This should be a `LemonButton` for better interactivity. It also supports the `to` prop, so there's no need for wrapping it with a link. The icon should be in the `icon` prop.

2022-03-02 14:58 UTC, Twixes commented on frontend/src/layout/navigation/TopBar/SitePopover.tsx
> +                    <Link
Should be a button like above

2022-03-02 14:58 UTC, Twixes commented on frontend/src/layout/navigation/TopBar/SitePopover.tsx
> +            <Tooltip title="Account settings">
This tooltip should be placed on the left:
<img width="164" alt="Screen Shot 2022-03-02 at 15 55 04" src="https://user-images.githubusercontent.com/4550621/156386408-50ea9e2e-f144-43f0-ba24-69e343aba7db.png">

2022-03-02 14:58 UTC, Twixes commented on frontend/src/layout/navigation/TopBar/SitePopover.tsx
> +                <Tooltip title="Organization settings">
Tooltip should be to the left

2022-03-02 14:58 UTC, Twixes commented on frontend/src/layout/navigation/TopBar/SitePopover.tsx
> +        <Link to={urls.instanceSettings()}>
This should be a `LemonButton` just like "Invite members" above.

2022-03-02 15:09 UTC, Twixes approved these changes
Fixed the inconsistencies in implementation to move this forward faster. The design is essentially the same though. As for remaining UX concerns, I'm also not sure about having both "Instance status" and "Instance settings", but don't know what's the best solution (for "Instance status" we _can_ link to https://status.posthog.com on Cloud, but not on self-hosted).

2022-03-02 15:20 UTC, tiina303 commented
Could we also update the image in https://posthog.com/blog/the-posthog-array-1-33-0 so users know how to find it.

2022-03-02 18:50 UTC, paolodamico commented
Thanks @clarkus for understanding and the feedback too. We all want to create the best product so really appreciate you pushing forward the quality. Thanks @Twixes too for the consistency fixes. For everyone else's context this is how the final version looks (when hovering over the instance settings menu item)

<img width="365" alt="Screen Shot 2022-03-02 at 12 48 38 PM" src="https://user-images.githubusercontent.com/5864173/156428396-dba68be9-fbcf-4411-a092-b25cf0018237.png">


Before merging this do we want to use the space for status to take to https://status.posthog.com on Cloud and remove the label on self-hosted? Or keep the label as is?

Sure thing @tiina303 I'll update once we finalize what to do with the instance status label.

2022-03-02 18:53 UTC, clarkus commented
> Before merging this do we want to use the space for status to take to https://status.posthog.com/ on Cloud and remove the label on self-hosted? Or keep the label as is?

The label seems applicable regardless of how it's hosted, so maybe just show the status link for cloud users?

2022-03-02 18:57 UTC, paolodamico commented
I really like the idea of having the status for PostHog Cloud in there but I just realized to properly show the "All systems operational" or something like "Downgraded experience" we would have to integrate with status.posthog.com to fetch any operational issues, so I would suggest keeping this for a subsequent improvement. Thoughts? Also for context, we would need to add the section to Cloud (this is how a normal Cloud user sees the popover now)

<img width="371" alt="" src="https://user-images.githubusercontent.com/5864173/156429476-d0a985ce-5cc8-426f-a29a-7e68f923ddcb.png">


So for self-hosted for now we'll keep the label as it is today, right?

2022-03-02 19:03 UTC, clarkus commented
I could see us swapping to use consistent icons for the management links, but I don't think it's critical at this stage especially if this won't be released for a while. Probably fine for a follow up iteration.

2022-03-02 19:12 UTC, clarkus requested changes
Let's make the management / settings links for the the currently logged in users, and the current organization consistent with gear icons and tooltips. Other than that, my main concern is limiting to a single instance settings link and dropping the link adjacent to "all systems operational". 

Here's a quick redraw of a cloud utility menu and a hosted utility menu if it helps clarify intent. https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=7768%3A39486

<img width="792" alt="Screen Shot 2022-03-02 at 11 11 10 AM" src="https://user-images.githubusercontent.com/254612/156431781-3f062f6a-1c58-426a-bb94-057256f20228.png">

2022-03-02 19:29 UTC, tiina303 commented
why are we dropping the link from all systems operational - I want to be able to click and get to the place, where we show which systems are operational and which aren't. It should take me to the `/instance/status` page.

2022-03-02 19:31 UTC, clarkus commented
> why are we dropping the link from all systems operational - I want to be able to click and get to the place, where we show which systems are operational and which aren't. It should take me to the `/instance/status` page system overview tab.

Because the target of the Instance settings link goes to the same URL. It's an accessibility concern if we link to the same place in multiple ways using varying text labels. I am optimizing for linking to that location via one prominent link so we can improve discoverability.

2022-03-02 19:52 UTC, tiina303 commented
> Because the target of the Instance settings link goes to the same URL. It's an accessibility concern if we link to the same place in multiple ways using varying text labels. I am optimizing for linking to that location via one prominent link so we can improve discoverability.

It should be different - instance settings should go to `/instance/status` but settings tab

2022-03-02 19:54 UTC, tiina303 commented
furthermore currently if I see there's a problem and there isn't a link next to it I wouldn't know to click on the link below

<img width="280" alt="Screen Shot 2022-03-02 at 20 53 56" src="https://user-images.githubusercontent.com/890921/156439245-f2fc3024-86c1-4646-8b97-52a065d42b26.png">

^ here if we remove the link from next to the red error it will be very confusing to the users imho

2022-03-02 20:44 UTC, clarkus commented
> It should be different - instance settings should go to /instance/status but settings tab

In my usage of the feature this is not how it works. It always goes to the default tab. Could it be a bug or some other issue? Even then, I'm not sure the targets are distinguishable enough to justify multiple links. 

> furthermore currently if I see there's a problem and there isn't a link next to it I wouldn't know to click on the link below
> ^ here if we remove the link from next to the red error it will be very confusing to the users imho

Thanks for the feedback, but I disagree. The need for going to this link isn't just in situations where there are errors. Those errors are conditionally show, so having a consistent place where we link to the page would be a better experience. For now, this feels like a clear enough improvement that's discoverable and placed in the page hierarchy accurately. Can we ship this iteration that improves discoverability and hierarchy concerns, and then queue up an iteration where we really try to nail instance management? I'm sure there are more problems to solve in here, so if we can track and describe those, we'll be in a better position to iterate and make more improvements.

2022-03-03 21:28 UTC, paolodamico commented
Ok based on the conversation above I believe the conclusion was let's merge this in as it's already an improvement and continue the conversation on how to improve in the issue that @clarkus opened, so merging and we can keep working on the other issue.

2022-03-03 21:28 UTC, merged