891 temporary token errors in app
PostHog/posthog pull request #894
Opened 2020-05-29 11:04 UTC by timgl

## Changes

- Compare netloc to netloc, ignore http or https
This will fix errors where people haven't set `IS_BEHIND_PROXY`

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

2020-05-29 15:52 UTC, EDsCODE requested changes
Few small things

2020-06-01 08:35 UTC, timgl commented on posthog/api/test/test_action.py
> +        }, content_type='application/json', HTTP_ORIGIN='https://testserver/')
Yep

2020-06-01 08:35 UTC, timgl commented
spillover fixed

2020-06-01 14:58 UTC, EDsCODE approved these changes

2020-06-01 15:00 UTC, merged

2020-06-02 13:19 UTC, janbaykara commented
This has broken multiple heroku deploys I'm working with. Investigating...

2020-06-02 14:43 UTC, EDsCODE commented
@janbaykara Hi, thanks for the heads up! Is the action creator not appearing now or are you hitting the AuthError`No temporary_token set...` when trying to create an action from it

2020-06-02 15:43 UTC, timgl commented
@janbaykara Just wanted to let you know that we've fixed this in #909. Let me know if you run into any other issues.