Events table antd
PostHog/posthog pull request #895
Opened 2020-05-29 11:34 UTC by timgl

## Changes

- events table to antd (including date break rows)
- Use antd tabs for properties/events when clicking on an event
- PropertiesTable to antd

## Checklist
- [ ] All querysets/queries filter by Team (if applicable)
- [ ] Backend tests (if applicable)
- [ ] Cypress E2E tests (if applicable)

2020-05-29 15:36 UTC, EDsCODE requested changes
A few small changes regarding the event table itself. This might be PR creep but I'd consider wrapping in a live action table refactor since it's very similar to the events table and it's looking like this rn: 
<img width="1159" alt="Screen Shot 2020-05-29 at 11 35 16 AM" src="https://user-images.githubusercontent.com/13127476/83277800-94b5c080-a1a0-11ea-84b9-38b1ddb55a66.png">

Also, once these two tables are done the antd coverage is pretty much complete (component wise). There's still a decent amount of bootstrap class styling being used but most if not all of the components will be on the antd standard

2020-05-29 15:36 UTC, EDsCODE commented on frontend/src/scenes/events/EventsTable.js
> +                    if (row.date_break) return 'event-day-separator'
I have been proven wrong!

2020-05-29 15:36 UTC, EDsCODE commented on frontend/src/scenes/events/EventRow.js
> -            <td data-attr={'event-name-' + index}>
The cypress test just needs this to be brought back

2020-05-29 18:57 UTC, timgl commented
@EDsCODE Done! That live actions page should also be a lot quicker now

2020-06-01 14:24 UTC, mariusandra commented
Looks pretty cool! 

Some comments below, all UX nits and can be solved outside this PR:

- For added UX points, I'd add some "filter" button next to the properties, so that I could get all events with Browser=Chrome easily.

![image](https://user-images.githubusercontent.com/53387/83418318-af4b9c00-a423-11ea-95a8-8a56d9b15409.png)

- The top in the "Person" page looks rather cramped. It's somehow not immediately clear if you click "test@email.com" in the table that the events are now scoped to the person from the slight header change.

![image](https://user-images.githubusercontent.com/53387/83418519-02255380-a424-11ea-8418-432bb2671f72.png)

2020-06-01 14:55 UTC, EDsCODE approved these changes

2020-06-01 14:56 UTC, EDsCODE commented
Agree with @mariusandra! I added a cursor pointer but otherwise looks good and the adjustments can be made as a followup

2020-06-01 16:37 UTC, timgl commented
Updated the spacing and header size, left the clicking on property table for now as that's slightly more involved. #902 created for that.

2020-06-01 16:37 UTC, merged