feat: Export insights table as CSV
PostHog/posthog pull request #9024
Opened 2022-03-14 21:19 UTC by timgl

## Problem

As a user i want to be able to export the insights table as csv to do further analysis on

## Changes

- add trend.csv endpoint to export as csv
- add button to frontend

<img width="604" alt="image" src="https://user-images.githubusercontent.com/1727427/158263107-26cac147-e73f-47b4-9e8d-1442350918e5.png">
👉 *Stay up-to-date with [PostHog coding conventions](https://posthog.com/docs/contribute/coding-conventions) for a smoother review.*

## How did you test this code?

unit tests
create insight, export as csv

2022-03-14 21:25 UTC, clarkus requested changes
The placement of the export action is problematic as it potentially interferes with placement for bulk actions. Bulk actions don't exist in this context, but as a system pattern I think we should reserve this area for those actions. The export action could also be more discoverable if we included a text label for the action. 

I think you could follow this pattern from the recent taxonomy and events work. The export action is placed above the table, in a secondary position with a clear label. You might need to include a header for the table just to balance that placement of the export icon. 

<img width="1223" alt="Screen Shot 2022-03-14 at 2 23 36 PM" src="https://user-images.githubusercontent.com/254612/158263736-0a59ef9e-6dae-4af7-b776-f4feaec7c795.png">

2022-03-15 11:17 UTC, Twixes requested changes
This feature definitely makes sense, but I do agree with Chris that the placement of the button isn't great.

2022-03-15 11:17 UTC, Twixes commented on posthog/api/insight.py
> +            ] = 'attachment; filename="posthog - {name} ({date_from} - {date_to}).csv"'.format(
Proposal for a subjectively slightly nicer/more helpful filename (putting "PostHog" at the end):
```suggestion
            ] = 'attachment; filename="{name} ({date_from}-{date_to}) from PostHog.csv"'.format(
```

2022-03-15 12:49 UTC, timgl commented on posthog/api/insight.py
> +                export = "{}/insights/{}/\n".format(SITE_URL, request.GET["export_insight_id"]).encode() + export
Hm yeah I think that's fair. Our friends at Ampl. include this in their export which i thought was smart as it makes it really easy to find where the data came from. Maybe the answer is to put it as the last column name?

2022-03-15 13:22 UTC, timgl commented
Thanks both! Think the export button looks okay without a header in there but happy to add one if you think it needs it?
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/1727427/158386793-85aa88cf-4d3a-4999-aab3-d87d024454ad.png">

2022-03-15 14:48 UTC, clarkus approved these changes
:shipit: Don't think we need a header to ship this. Longer term I'd like to expand on the table patterns to include some proper reusable filtering and exporting controls. Was talking to @alexkim205 about this earlier since he did some of this work recently for data management / live events. It'd just be nice to have some reusable components that always work with card or list views.

2022-03-15 15:11 UTC, alexkim205 commented
> It'd just be nice to have some reusable components that always work with card or list views.

Made an issue here https://github.com/PostHog/posthog/issues/9035 to capture this initiative, but non blocking for this PR.

2022-03-16 19:11 UTC, merged