fix(property-filter): use a subscription to update the page title
PostHog/posthog pull request #9385
Opened 2022-04-11 15:19 UTC by mariusandra

## Problem

Do not ask me how, but this fixes the following.

## Changes

With this fix:

![2022-04-11 17 18 04](https://user-images.githubusercontent.com/53387/162771723-de531d1c-d9e1-48f4-be0d-f2b45e2a9c3c.gif)

On master:

![2022-04-11 17 18 38](https://user-images.githubusercontent.com/53387/162771805-79e025fa-6581-448f-82e1-eabbb9383fab.gif)

## How did you test this code?

Eyes closed.

2022-04-11 15:28 UTC, EDsCODE approved these changes
I'm also not 100% certain why moving the logic here solves it but it fixes the bug and keeps more logic in kea so I'm ok with this

2022-04-11 15:28 UTC, EDsCODE commented on frontend/src/layout/navigation/Breadcrumbs/breadcrumbsLogic.tsx
> +            if (typeof document !== 'undefined') {
Maybe this solved it? Otherwise it seems like the logic would be the same

2022-04-11 15:34 UTC, Twixes requested changes

2022-04-11 18:27 UTC, mariusandra commented
Your hunch might be right, though it's still weird how this happens. It's possible adding another selector and using `[stringTitle]` for `useEffect` might have solved things. However I was too committed, and refactored this further... and added a test.

Unfortunately the `sceneBreadcrumbs` selector is recalculated way too often. Somebody also [requested a fix](https://github.com/keajs/kea/issues/143) for this. For us, for now, just having `documentTitle` a string seems to work.

2022-04-12 09:52 UTC, Twixes approved these changes
Looks proper 👌

2022-04-12 09:52 UTC, merged