refactor(scenes): automatically bind props to logic in scenes
PostHog/posthog pull request #9451
Opened 2022-04-19 10:53 UTC by mariusandra

## Problem

Trying to make our lives easier by binding each scene's keyed logic to the scene automatically.

Each `SceneExport` has a `paramsToProps` function, which specifies how to build a logic from the URL. Despite this function existing, you had to convert the params to props a second time when getting values/actions from the scene's logic.

## Changes

- This PR automatically binds the scene's logic to the scene's component
- Moves a few props to selectors where it makes sense
- Removes some `<BindLogic>` that's no longer needed
- Updates the "how to build a scene" page
- Small TODO outside the scope here to work better with kea-forms (the forms should use the bound props as well)
- I didn't modify the cohorts page, since I know work is happening there.

## How did you test this code?

- Clicked around in each of the affected pages (dashboard, experiment, feature flag, persons, actions), saw that things still worked

2022-05-03 22:26 UTC, mariusandra commented on frontend/src/scenes/dashboard/Dashboard.tsx
>  export function Dashboard({ id, shareToken, placement }: Props = {}): JSX.Element {
I thought about it, and had actually removed it... but put it back. It felt weird that the shared dashboard "scene" needs to know this deeply about dashboard internals. This tiny wrapper and the naming around it is not that ideal either... 🤔

2022-05-03 22:26 UTC, mariusandra commented on frontend/src/scenes/experiments/Experiment.tsx
> +export function Experiment_(): JSX.Element {
I think `Experiment` was a type that was imported...

2022-05-04 13:24 UTC, Twixes requested changes
All good except I get this when I open the project homepage with no home dashboard selected:
![Uploading localhost_8000_home.png…]()

2022-05-04 16:10 UTC, Twixes approved these changes
Let's gooo

2022-05-04 16:10 UTC, merged