fix: paginate dashboards list at 100
PostHog/posthog pull request #9910
Opened 2022-05-23 13:44 UTC by pauldambra

## Problem

closes #9906 

Dashboard list page did not have pagination set for LemonTable. The API pages at 100. The search only queries dashboards loaded into kea. This meant if you had more than 100 dashboards you couldn't find the ones after the first page

## Changes

Sets pagination to 100 to match the API default

### example with pagination set to 4

![2022-05-23 14 40 32](https://user-images.githubusercontent.com/984817/169832720-6a3df396-6bea-4670-87a4-1d6063b24b34.gif)

## How did you test this code?

ran it locally with and without pagination set to 4 to see the behaviour change

2022-05-23 13:44 UTC, timgl approved these changes

2022-05-23 14:35 UTC, Twixes requested changes
The issue is, this will do nothing, because the API endpoint still uses the default `PAGE_SIZE` of 100. We can either fix this the hacky way, like we did with cohorts some time ago by just slapping a higher limit on the API call (https://github.com/PostHog/posthog/blob/master/frontend/src/lib/api.ts#L487), or the proper way, by integrating `LemonTable` pagination with `loadDashboards` (perhaps making `onForward` and `onBackward` available with `PaginationAuto`).

2022-05-23 16:00 UTC, pauldambra commented
> The issue is, this will do nothing, because the API endpoint still uses the default PAGE_SIZE of 100.

Doesn't it workaround by matching a page of 100 in the UI? 

> or the proper way, by integrating LemonTable pagination with loadDashboards (perhaps making onForward and onBackward available with PaginationAuto).

Is there an example of that somewhere or does it need building?

2022-05-23 17:55 UTC, Twixes commented
> Doesn't it workaround by matching a page of 100 in the UI?

Not actually, because the API doesn't return more than 100 items anyway, so table pagination can't kick in.

> or the proper way, by integrating LemonTable pagination with loadDashboards (perhaps making onForward and onBackward available with PaginationAuto).

Not really (so it's probably _okay_ to just use `?limit=300` for now).

2022-05-23 18:44 UTC, pauldambra commented
> Not actually, because the API doesn't return more than 100 items anyway,

Ah, so the local example worked because it was paginating at 4 with an API returning more than 4 🤯

2022-05-24 09:53 UTC, Twixes approved these changes
:thisisfine:

2022-05-24 09:53 UTC, merged

2022-05-24 14:36 UTC, timgl commented
Hm this isn't good enough. We have a user on cloud with 596 dashboards. Can we put a more permanent fix in? I'm ok if the solution is "load unlimited dashboards" in the api

2022-05-24 16:39 UTC, pauldambra commented
Yep, this definitely only a workaround!

2022-05-24 16:42 UTC, pauldambra commented
Logged https://github.com/PostHog/posthog/issues/9959 so we don't lose sight of this